/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * diagDocumentoIdentidadBusqueda.java
 *
 * Created on 17/08/2011, 09:26:02
 */
package vistas.investigadores;

import entidades.persona.DocumentoIdentidad;
import entidades.persona.TipoDocumento;
import facade.TipoDocumentoFacade;
import includes.Comunes;
import org.apache.commons.validator.routines.LongValidator;

/**
 *
 * @author Carlos
 */
public class diagDocumentoIdentidadBusqueda extends javax.swing.JDialog {

    DocumentoIdentidad documentoIdentidad;

    /** Creates new form diagDocumentoIdentidadBusqueda */
    public diagDocumentoIdentidadBusqueda(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        inicializarComponentes();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cboTiposDocumentos = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        tfNumeroDocumento = new javax.swing.JTextField();
        btAceptar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText(org.openide.util.NbBundle.getMessage(diagDocumentoIdentidadBusqueda.class, "diagDocumentoIdentidadBusqueda.jLabel1.text")); // NOI18N

        jLabel2.setText(org.openide.util.NbBundle.getMessage(diagDocumentoIdentidadBusqueda.class, "diagDocumentoIdentidadBusqueda.jLabel2.text")); // NOI18N

        tfNumeroDocumento.setText(org.openide.util.NbBundle.getMessage(diagDocumentoIdentidadBusqueda.class, "diagDocumentoIdentidadBusqueda.tfNumeroDocumento.text")); // NOI18N

        btAceptar.setText(org.openide.util.NbBundle.getMessage(diagDocumentoIdentidadBusqueda.class, "diagDocumentoIdentidadBusqueda.btAceptar.text")); // NOI18N
        btAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfNumeroDocumento)
                            .addComponent(cboTiposDocumentos, 0, 113, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(btAceptar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cboTiposDocumentos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfNumeroDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btAceptar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAceptarActionPerformed
        aceptar();
    }//GEN-LAST:event_btAceptarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                diagDocumentoIdentidadBusqueda dialog = new diagDocumentoIdentidadBusqueda(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAceptar;
    private javax.swing.JComboBox cboTiposDocumentos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField tfNumeroDocumento;
    // End of variables declaration//GEN-END:variables

    private void inicializarComponentes() {
        cargarTiposDocumentos();
    }

    private void cargarTiposDocumentos() {
        Comunes.cargarJCombo(cboTiposDocumentos, TipoDocumentoFacade.getInstance().listarTodosTipoDocumento());
    }

    private void aceptar() {
        documentoIdentidad = new DocumentoIdentidad();
        if (cboTiposDocumentos.getSelectedIndex() != -1) {
            documentoIdentidad.setTipoDocumento((TipoDocumento) cboTiposDocumentos.getSelectedItem());
        }
        if (LongValidator.getInstance().isValid(tfNumeroDocumento.getText())) {
            documentoIdentidad.setNumero(Long.parseLong(tfNumeroDocumento.getText()));
        }
    }

    public DocumentoIdentidad getDocumentoIdentidad() {
        return documentoIdentidad;
    }
}
