/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas.investigadores;

import entidades.persona.investigador.Acceso;
import facade.AccesoFacade;
import includes.ModeloTablaNoEditable;
import java.text.SimpleDateFormat;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author franco
 */
public class DiagAccesoWeb extends javax.swing.JDialog {

    ModeloTablaNoEditable modeloTabla = new ModeloTablaNoEditable();

    /**
     * Creates new form DiagLogProyecto
     */
    public DiagAccesoWeb(java.awt.Frame parent, boolean modal) {
        super(parent, modal);

        initComponents();
        cargarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tbLog = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tbLog.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tbLog);

        jLabel1.setText(org.openide.util.NbBundle.getMessage(DiagAccesoWeb.class, "DiagAccesoWeb.jLabel1.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(419, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 542, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(21, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(275, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(32, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbLog;
    // End of variables declaration//GEN-END:variables

    private void cargarTabla() {
        modeloTabla = new ModeloTablaNoEditable();
        cargarEncabezadosTablaLog(modeloTabla);
        for (Acceso acceso : AccesoFacade.getInstance().getTodos()) {
            cargar(acceso);
        }
    }

    private void cargarEncabezadosTablaLog(DefaultTableModel model) {
        model.addColumn("Codigo");
        model.addColumn("Fecha");
        model.addColumn("Investigador");
        tbLog.setModel(model);

    }

    private void cargar(Acceso acceso) {
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy hh:mm:ss");

        Object[] fila = new Object[3];
        fila[0] = acceso.getId();
        try {
            fila[1] = formato.format(acceso.getFecha());
        } catch (java.lang.NullPointerException ex) {
            fila[1] = "-";
        }
        try {
            fila[2] = acceso.getInvestigador();
        } catch (java.lang.NullPointerException ex) {
            fila[2] = "-";
        }
       
        modeloTabla.addRow(fila);


    }
}
