/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.proyectos.resultado;

import entidades.operaciones.Operacion;
import entidades.proyecto.Participacion;
import entidades.proyecto.Proyecto;
import entidades.proyecto.resultado.FormacionRRHH;
import entidades.proyecto.vinculacion.ParticipacionVinculacion;
import entidades.proyecto.vinculacion.ProyectoVinculacion;
import entidades.usuario.Usuario;
import facade.FormacionRRHHFacade;
import facade.OperacionFacade;
import includes.Comunes;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author hugo
 */
public class diagProyectoResultadoFormacionRRHH extends javax.swing.JDialog {

    private String tipoOperacion;
    private Proyecto proyecto;
    private ProyectoVinculacion proyectoVinculacion;
    private Usuario usuario;
    private FormacionRRHH formacionRRHH;

    public FormacionRRHH getFormacionRRHH() {
        return formacionRRHH;
    }

    /**
     * Creates new form diagProyectoResultadoFormacionRRHH
     */
    public diagProyectoResultadoFormacionRRHH(java.awt.Frame parent, boolean modal, String tipoOperacion, Proyecto proyecto, Usuario usuario) {
        super(parent, modal);
        this.tipoOperacion = tipoOperacion;
        this.proyecto = proyecto;
        this.usuario = usuario;
        initComponents();
        this.btnBuscarProyectoFormacionRRHH.setVisible(false);
        inicializarComponentes();
        taProyectoFormacionRRHH.setText(proyecto.toString());

    }

    public diagProyectoResultadoFormacionRRHH(java.awt.Frame parent, boolean modal, String tipoOperacion, Proyecto proyecto, FormacionRRHH formacionRRHH, Usuario usuario) {
        super(parent, modal);
        this.tipoOperacion = tipoOperacion;
        this.proyecto = proyecto;
        this.usuario = usuario;
        this.formacionRRHH = formacionRRHH;
        initComponents();
        this.btnBuscarProyectoFormacionRRHH.setVisible(false);
        inicializarComponentes();
        taProyectoFormacionRRHH.setText(proyecto.toString());

    }

    public diagProyectoResultadoFormacionRRHH(java.awt.Frame parent, boolean modal, String tipoOperacion, ProyectoVinculacion proyectoVinculacion, Usuario usuario) {
        super(parent, modal);
        this.tipoOperacion = tipoOperacion;
        this.proyectoVinculacion = proyectoVinculacion;
        this.usuario = usuario;
        initComponents();
        this.btnBuscarProyectoFormacionRRHH.setVisible(false);
        inicializarComponentes();
        taProyectoFormacionRRHH.setText(proyectoVinculacion.toString());

    }

    public diagProyectoResultadoFormacionRRHH(java.awt.Frame parent, boolean modal, String tipoOperacion, ProyectoVinculacion proyectoVinculacion, FormacionRRHH formacionRRHH, Usuario usuario) {
        super(parent, modal);
        this.tipoOperacion = tipoOperacion;
        this.proyectoVinculacion = proyectoVinculacion;
        this.usuario = usuario;
        this.formacionRRHH = formacionRRHH;
        initComponents();
        this.btnBuscarProyectoFormacionRRHH.setVisible(false);
        inicializarComponentes();
        taProyectoFormacionRRHH.setText(proyectoVinculacion.toString());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taProyectoFormacionRRHH = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        btnBuscarProyectoFormacionRRHH = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        tfDirectorProyecto = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tfCodigoProyecto = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        tfBecariosAlumnos = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tfBecariosGraduados = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tfTesisDirigidas = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tfTesisMaestria = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        tfTesisDoctorado = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        tfTesinasDeGrado = new javax.swing.JTextField();
        jxdpFecha = new org.jdesktop.swingx.JXDatePicker();
        jLabel11 = new javax.swing.JLabel();
        btnAceptar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(diagProyectoResultadoFormacionRRHH.class, "diagProyectoResultadoFormacionRRHH.jPanel1.border.title"))); // NOI18N

        taProyectoFormacionRRHH.setColumns(20);
        taProyectoFormacionRRHH.setEditable(false);
        taProyectoFormacionRRHH.setFont(new java.awt.Font("Monospaced", 0, 11)); // NOI18N
        taProyectoFormacionRRHH.setRows(5);
        jScrollPane1.setViewportView(taProyectoFormacionRRHH);

        jLabel1.setText(org.openide.util.NbBundle.getMessage(diagProyectoResultadoFormacionRRHH.class, "diagProyectoResultadoFormacionRRHH.jLabel1.text")); // NOI18N

        btnBuscarProyectoFormacionRRHH.setText(org.openide.util.NbBundle.getMessage(diagProyectoResultadoFormacionRRHH.class, "diagProyectoResultadoFormacionRRHH.btnBuscarProyectoFormacionRRHH.text")); // NOI18N
        btnBuscarProyectoFormacionRRHH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarProyectoFormacionRRHHActionPerformed(evt);
            }
        });

        jLabel2.setText(org.openide.util.NbBundle.getMessage(diagProyectoResultadoFormacionRRHH.class, "diagProyectoResultadoFormacionRRHH.jLabel2.text")); // NOI18N

        tfDirectorProyecto.setText(org.openide.util.NbBundle.getMessage(diagProyectoResultadoFormacionRRHH.class, "diagProyectoResultadoFormacionRRHH.tfDirectorProyecto.text")); // NOI18N

        jLabel3.setText(org.openide.util.NbBundle.getMessage(diagProyectoResultadoFormacionRRHH.class, "diagProyectoResultadoFormacionRRHH.jLabel3.text")); // NOI18N

        tfCodigoProyecto.setText(org.openide.util.NbBundle.getMessage(diagProyectoResultadoFormacionRRHH.class, "diagProyectoResultadoFormacionRRHH.tfCodigoProyecto.text")); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfCodigoProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfDirectorProyecto))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(btnBuscarProyectoFormacionRRHH, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarProyectoFormacionRRHH))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfDirectorProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfCodigoProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(diagProyectoResultadoFormacionRRHH.class, "diagProyectoResultadoFormacionRRHH.jPanel2.border.title"))); // NOI18N

        jLabel4.setText(org.openide.util.NbBundle.getMessage(diagProyectoResultadoFormacionRRHH.class, "diagProyectoResultadoFormacionRRHH.jLabel4.text")); // NOI18N

        tfBecariosAlumnos.setText(org.openide.util.NbBundle.getMessage(diagProyectoResultadoFormacionRRHH.class, "diagProyectoResultadoFormacionRRHH.tfBecariosAlumnos.text")); // NOI18N

        jLabel5.setText(org.openide.util.NbBundle.getMessage(diagProyectoResultadoFormacionRRHH.class, "diagProyectoResultadoFormacionRRHH.jLabel5.text")); // NOI18N

        tfBecariosGraduados.setText(org.openide.util.NbBundle.getMessage(diagProyectoResultadoFormacionRRHH.class, "diagProyectoResultadoFormacionRRHH.tfBecariosGraduados.text")); // NOI18N

        jLabel6.setText(org.openide.util.NbBundle.getMessage(diagProyectoResultadoFormacionRRHH.class, "diagProyectoResultadoFormacionRRHH.jLabel6.text")); // NOI18N

        tfTesisDirigidas.setText(org.openide.util.NbBundle.getMessage(diagProyectoResultadoFormacionRRHH.class, "diagProyectoResultadoFormacionRRHH.tfTesisDirigidas.text")); // NOI18N

        jLabel7.setText(org.openide.util.NbBundle.getMessage(diagProyectoResultadoFormacionRRHH.class, "diagProyectoResultadoFormacionRRHH.jLabel7.text")); // NOI18N

        jLabel8.setText(org.openide.util.NbBundle.getMessage(diagProyectoResultadoFormacionRRHH.class, "diagProyectoResultadoFormacionRRHH.jLabel8.text")); // NOI18N

        tfTesisMaestria.setText(org.openide.util.NbBundle.getMessage(diagProyectoResultadoFormacionRRHH.class, "diagProyectoResultadoFormacionRRHH.tfTesisMaestria.text")); // NOI18N

        jLabel9.setText(org.openide.util.NbBundle.getMessage(diagProyectoResultadoFormacionRRHH.class, "diagProyectoResultadoFormacionRRHH.jLabel9.text")); // NOI18N

        tfTesisDoctorado.setText(org.openide.util.NbBundle.getMessage(diagProyectoResultadoFormacionRRHH.class, "diagProyectoResultadoFormacionRRHH.tfTesisDoctorado.text")); // NOI18N

        jLabel10.setText(org.openide.util.NbBundle.getMessage(diagProyectoResultadoFormacionRRHH.class, "diagProyectoResultadoFormacionRRHH.jLabel10.text")); // NOI18N

        tfTesinasDeGrado.setText(org.openide.util.NbBundle.getMessage(diagProyectoResultadoFormacionRRHH.class, "diagProyectoResultadoFormacionRRHH.tfTesinasDeGrado.text")); // NOI18N

        jLabel11.setText(org.openide.util.NbBundle.getMessage(diagProyectoResultadoFormacionRRHH.class, "diagProyectoResultadoFormacionRRHH.jLabel11.text")); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfBecariosGraduados, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(tfBecariosAlumnos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(tfTesisDirigidas, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(38, 38, 38)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel10)
                                    .addGap(18, 18, 18)
                                    .addComponent(tfTesinasDeGrado, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(jLabel11)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jxdpFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel7)
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addGroup(jPanel2Layout.createSequentialGroup()
                                                    .addComponent(jLabel8)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(tfTesisMaestria, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(jPanel2Layout.createSequentialGroup()
                                                    .addComponent(jLabel9)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(tfTesisDoctorado, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                    .addGap(41, 41, 41))))))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(tfBecariosAlumnos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(tfBecariosGraduados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jxdpFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(tfTesisMaestria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(tfTesisDoctorado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(tfTesinasDeGrado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(tfTesisDirigidas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(160, 160, 160))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnAceptar.setText(org.openide.util.NbBundle.getMessage(diagProyectoResultadoFormacionRRHH.class, "diagProyectoResultadoFormacionRRHH.btnAceptar.text")); // NOI18N
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 725, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(292, 292, 292)
                        .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAceptar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarProyectoFormacionRRHHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarProyectoFormacionRRHHActionPerformed
   }//GEN-LAST:event_btnBuscarProyectoFormacionRRHHActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        aceptar();
    }//GEN-LAST:event_btnAceptarActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnBuscarProyectoFormacionRRHH;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private org.jdesktop.swingx.JXDatePicker jxdpFecha;
    private javax.swing.JTextArea taProyectoFormacionRRHH;
    private javax.swing.JTextField tfBecariosAlumnos;
    private javax.swing.JTextField tfBecariosGraduados;
    private javax.swing.JTextField tfCodigoProyecto;
    private javax.swing.JTextField tfDirectorProyecto;
    private javax.swing.JTextField tfTesinasDeGrado;
    private javax.swing.JTextField tfTesisDirigidas;
    private javax.swing.JTextField tfTesisDoctorado;
    private javax.swing.JTextField tfTesisMaestria;
    // End of variables declaration//GEN-END:variables

    private void inicializarComponentes() {
        Comunes.formatearJXdatePicker(jxdpFecha);
        this.taProyectoFormacionRRHH.setEditable(false);
        this.tfDirectorProyecto.setEditable(false);
        this.tfCodigoProyecto.setEditable(false);
        Comunes.autoAjusteTextArea(taProyectoFormacionRRHH);
        //cargo el director de proyecto

        if (proyecto != null) {
        tfCodigoProyecto.setText(proyecto.getCodigo());
        
            
            
            List<Participacion> participantes = proyecto.getParticipaciones();
            for (Participacion investigador : participantes) {
                if (investigador.getRol().getDescripcion().equals("Director")) {
                    tfDirectorProyecto.setText(investigador.getInvestigador().toString());

                }
            }
        }
        if (proyectoVinculacion != null) {
            
            tfCodigoProyecto.setText(proyectoVinculacion.getCodigo());
        
            
            List<ParticipacionVinculacion> participantes = proyectoVinculacion.getParticipaciones();
            for (ParticipacionVinculacion investigador : participantes) {
                if (investigador.getRol().getDescripcion().equals("Director")) {
                    
                    tfDirectorProyecto.setText(investigador.getInvestigador().toString());

                }
            }
        }

        
        if (tipoOperacion.equals("Modificación")) {
            if (formacionRRHH.getBecariosAlumnos() > -1) {
                tfBecariosAlumnos.setText(String.valueOf(formacionRRHH.getBecariosAlumnos()));
            } else {
                tfBecariosAlumnos.setText(null);
            }
            if (formacionRRHH.getBecariosGraduados() > -1) {
                tfBecariosGraduados.setText(String.valueOf(formacionRRHH.getBecariosGraduados()));
            } else {
                tfBecariosGraduados.setText(null);
            }
            if (formacionRRHH.getTesisDirigidas() > -1) {
                tfTesisDirigidas.setText(String.valueOf(formacionRRHH.getTesisDirigidas()));
            } else {
                tfTesisDirigidas.setText(null);
            }
            if (formacionRRHH.getTesisAprobadasMaestria() > -1) {
                tfTesisMaestria.setText(String.valueOf(formacionRRHH.getTesisAprobadasMaestria()));
            } else {
                tfTesisMaestria.setText(null);
            }
            if (formacionRRHH.getTesisAprobadasDoctorado() > -1) {
                tfTesisDoctorado.setText(String.valueOf(formacionRRHH.getTesisAprobadasDoctorado()));
            } else {
                tfTesisDoctorado.setText(null);
            }
            if (formacionRRHH.getTesinasGradoAprobadas() > -1) {
                tfTesinasDeGrado.setText(String.valueOf(formacionRRHH.getTesinasGradoAprobadas()));
            } else {
                tfTesinasDeGrado.setText(null);
            }
            try {
                jxdpFecha.setDate(formacionRRHH.getFecha());
            } catch (Exception ex) {
            }

        }


    }

    private void aceptar() {
        if (validar()) {
            if (tipoOperacion.equals("Alta")) {
                formacionRRHH = new FormacionRRHH();
                if (proyecto != null) {
                    formacionRRHH.setProyecto(proyecto);

                }
                if (proyectoVinculacion != null) {
                    formacionRRHH.setProyectoVinculacion(proyectoVinculacion);

                }
                if (!tfBecariosAlumnos.getText().isEmpty()) {
                    formacionRRHH.setBecariosAlumnos(Integer.parseInt(tfBecariosAlumnos.getText()));
                } else {
                    formacionRRHH.setBecariosAlumnos(0);
                }
                if (!tfBecariosGraduados.getText().isEmpty()) {
                    formacionRRHH.setBecariosGraduados(Integer.parseInt(tfBecariosGraduados.getText()));
                } else {
                    formacionRRHH.setBecariosGraduados(0);
                }
                if (!tfTesisDirigidas.getText().isEmpty()) {
                    formacionRRHH.setTesisDirigidas(Integer.parseInt(tfTesisDirigidas.getText()));
                } else {
                    formacionRRHH.setTesisDirigidas(0);
                }
                if (!tfTesisMaestria.getText().isEmpty()) {
                    formacionRRHH.setTesisAprobadasMaestria(Integer.parseInt(tfTesisMaestria.getText()));
                } else {
                    formacionRRHH.setTesisAprobadasMaestria(0);
                }
                if (!tfTesisDoctorado.getText().isEmpty()) {
                    formacionRRHH.setTesisAprobadasDoctorado(Integer.parseInt(tfTesisDoctorado.getText()));
                } else {
                    formacionRRHH.setTesisAprobadasDoctorado(0);
                }
                if (!tfTesinasDeGrado.getText().isEmpty()) {
                    formacionRRHH.setTesinasGradoAprobadas(Integer.parseInt(tfTesinasDeGrado.getText()));
                } else {
                    formacionRRHH.setTesinasGradoAprobadas(0);
                }
                if (jxdpFecha.getDate() != null) {
                    formacionRRHH.setFecha(jxdpFecha.getDate());
                } else {
                    formacionRRHH.setFecha(null);
                }

                try {
                    FormacionRRHHFacade.getInstance().alta(formacionRRHH);
                    Operacion operacion = new Operacion();
                    operacion.setFecha(Comunes.obtenerFechaActualDesdeDB());
                    operacion.setOperacion("Alta de Resultado Formacion RRHH");
                    operacion.setUsuario(usuario);
                    OperacionFacade.getInstance().alta(operacion);
                    JOptionPane.showMessageDialog(null, "Operacion Realizada");
                    this.dispose();
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(null, "Error al intentar cargar los datos" + ex);
                }

            }
            if (tipoOperacion.equals("Modificación")) {
                if (proyecto != null) {
                    formacionRRHH.setProyecto(proyecto);

                }
                if (proyectoVinculacion != null) {
                    formacionRRHH.setProyectoVinculacion(proyectoVinculacion);

                }
                if (!tfBecariosAlumnos.getText().isEmpty()) {
                    formacionRRHH.setBecariosAlumnos(Integer.parseInt(tfBecariosAlumnos.getText()));
                } else {
                    formacionRRHH.setBecariosAlumnos(0);
                }
                if (!tfBecariosGraduados.getText().isEmpty()) {
                    formacionRRHH.setBecariosGraduados(Integer.parseInt(tfBecariosGraduados.getText()));
                } else {
                    formacionRRHH.setBecariosGraduados(0);
                }
                if (!tfTesisDirigidas.getText().isEmpty()) {
                    formacionRRHH.setTesisDirigidas(Integer.parseInt(tfTesisDirigidas.getText()));
                } else {
                    formacionRRHH.setTesisDirigidas(0);
                }
                if (!tfTesisMaestria.getText().isEmpty()) {
                    formacionRRHH.setTesisAprobadasMaestria(Integer.parseInt(tfTesisMaestria.getText()));
                } else {
                    formacionRRHH.setTesisAprobadasMaestria(0);
                }
                if (!tfTesisDoctorado.getText().isEmpty()) {
                    formacionRRHH.setTesisAprobadasDoctorado(Integer.parseInt(tfTesisDoctorado.getText()));
                } else {
                    formacionRRHH.setTesisAprobadasDoctorado(0);
                }
                if (!tfTesinasDeGrado.getText().isEmpty()) {
                    formacionRRHH.setTesinasGradoAprobadas(Integer.parseInt(tfTesinasDeGrado.getText()));
                } else {
                    formacionRRHH.setTesinasGradoAprobadas(0);
                }
                if (jxdpFecha.getDate() != null) {
                    formacionRRHH.setFecha(jxdpFecha.getDate());
                } else {
                    formacionRRHH.setFecha(null);
                }
                try {
                    FormacionRRHHFacade.getInstance().modificar(formacionRRHH);
                    Operacion operacion = new Operacion();
                    operacion.setFecha(Comunes.obtenerFechaActualDesdeDB());
                    operacion.setOperacion("modificacion de Resultado Formacion RRHH");
                    operacion.setUsuario(usuario);
                    OperacionFacade.getInstance().alta(operacion);
                    JOptionPane.showMessageDialog(null, "Modificacion Realizada");
                    this.dispose();
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(null, "Error al intentar cargar los datos" + ex);
                }

            }

        }

    }

    private boolean validar() {
        boolean flag = false;
        if (proyecto != null || proyectoVinculacion != null) {
            if (tfBecariosAlumnos.getText().isEmpty() || Comunes.validarInteger(tfBecariosAlumnos.getText())) {
                if (tfBecariosGraduados.getText().isEmpty() || Comunes.validarInteger(tfBecariosGraduados.getText())) {
                    if (tfTesisDirigidas.getText().isEmpty() || Comunes.validarInteger(tfTesisDirigidas.getText())) {
                        if (tfTesisMaestria.getText().isEmpty() || Comunes.validarInteger(tfTesisMaestria.getText())) {
                            if (tfTesisDoctorado.getText().isEmpty() || Comunes.validarInteger(tfTesisDoctorado.getText())) {
                                if (tfTesinasDeGrado.getText().isEmpty() || Comunes.validarInteger(tfTesinasDeGrado.getText())) {
                                    flag = true;
                                } else {
                                    JOptionPane.showMessageDialog(null, "Debe escribir solo numeros, sin decimales");
                                    tfTesinasDeGrado.requestFocus();
                                }

                            } else {
                                JOptionPane.showMessageDialog(null, "Debe escribir solo numeros, sin decimales");
                                tfTesisDoctorado.requestFocus();
                            }
                        } else {
                            JOptionPane.showMessageDialog(null, "Debe escribir solo numeros, sin decimales");
                            tfTesisMaestria.requestFocus();
                        }

                    } else {
                        JOptionPane.showMessageDialog(null, "Debe escribir solo numeros, sin decimales");
                        tfTesisDirigidas.requestFocus();
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Debe escribir solo numeros, sin decimales");
                    tfBecariosGraduados.requestFocus();
                }

            } else {
                JOptionPane.showMessageDialog(null, "Debe escribir solo numeros, sin decimales");
                tfBecariosAlumnos.requestFocus();
            }
        } else {
            JOptionPane.showMessageDialog(null, "No selecciono un proyecto");
            btnBuscarProyectoFormacionRRHH.requestFocus();
        }
        return flag;
    }
}
