/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.proyectos.resultado;

import entidades.operaciones.Operacion;
import entidades.persona.investigador.Investigador;
import entidades.proyecto.Proyecto;
import entidades.proyecto.resultado.*;
import entidades.proyecto.vinculacion.ProyectoVinculacion;
import entidades.usuario.Usuario;
import facade.InvestigadorFacade;
import facade.OperacionFacade;
import facade.PropiedadFacade;
import facade.ProyectoFacade;
import facade.ProyectoVinculacionFacade;
import includes.Comunes;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author hugo
 */
public class diagProyectoResultadoPIndustrial extends javax.swing.JDialog {

    private String tipoOperacion;
    private Usuario usuario;
    private Proyecto proyectoPIndustrial;
        private ProyectoVinculacion proyectoVinculacionPIndustrial;

    private Industrial pIndustrial;
    private List<Investigador> participantesDentroPIndustrial = new ArrayList<Investigador>();

    /**
     * Creates new form dialogProyectoResultadoPIntelectual
     */
    public diagProyectoResultadoPIndustrial(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public diagProyectoResultadoPIndustrial(java.awt.Frame parent, boolean modal, String tipoOperacion, Usuario usuario) {
        super(parent, modal);
        this.tipoOperacion = tipoOperacion;
        this.usuario = usuario;
        initComponents();
        inicializarComponentes();
        btnBuscarProyectoPIndustrial.setVisible(true);
    }

    public diagProyectoResultadoPIndustrial(java.awt.Frame parent, boolean modal, String tipoOperacion, Proyecto proyecto, Usuario usuario) {
        super(parent, modal);
        this.tipoOperacion = tipoOperacion;
        this.usuario = usuario;
        this.proyectoPIndustrial = proyecto;
        initComponents();
        inicializarComponentes();
        btnBuscarProyectoPIndustrial.setVisible(false);
                taProyectoPIndustrial.setText(proyectoPIndustrial.toString());

    }

    public diagProyectoResultadoPIndustrial(java.awt.Frame parent, boolean modal, String tipoOperacion, Proyecto proyecto, Industrial industrial, Usuario usuario) {
        super(parent, modal);
        this.tipoOperacion = tipoOperacion;
        this.usuario = usuario;
        this.proyectoPIndustrial = proyecto;
        this.pIndustrial = industrial;
        initComponents();
        inicializarComponentes();
        btnBuscarProyectoPIndustrial.setVisible(false);
                taProyectoPIndustrial.setText(proyectoPIndustrial.toString());

    }
    
    public diagProyectoResultadoPIndustrial(java.awt.Frame parent, boolean modal, String tipoOperacion, ProyectoVinculacion proyectoVinculacion, Usuario usuario) {
        super(parent, modal);
        this.tipoOperacion = tipoOperacion;
        this.usuario = usuario;
        this.proyectoVinculacionPIndustrial = proyectoVinculacion;
        initComponents();
        inicializarComponentes();
        btnBuscarProyectoPIndustrial.setVisible(false);
                taProyectoPIndustrial.setText(proyectoVinculacionPIndustrial.toString());

    }

    public diagProyectoResultadoPIndustrial(java.awt.Frame parent, boolean modal, String tipoOperacion, ProyectoVinculacion proyectoVinculacion, Industrial industrial, Usuario usuario) {
        super(parent, modal);
        this.tipoOperacion = tipoOperacion;
        this.usuario = usuario;
        this.proyectoVinculacionPIndustrial = proyectoVinculacion;
        this.pIndustrial = industrial;
        initComponents();
        inicializarComponentes();
        btnBuscarProyectoPIndustrial.setVisible(false);
                taProyectoPIndustrial.setText(proyectoVinculacionPIndustrial.toString());

    }

    public Industrial getpIndustrial() {
        return pIndustrial;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taProyectoPIndustrial = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        btnBuscarProyectoPIndustrial = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        tfTituloPIndustrial = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        cboTipoRegistro = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        tfTitularesRegistro = new javax.swing.JTextField();
        jPanelAsesores2 = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        lstIntegrantesDentroPIndustrial = new javax.swing.JList();
        btnAgregarIntegrantePIndustrial = new javax.swing.JButton();
        btnQuitarIntegrantePIndustrial = new javax.swing.JButton();
        jScrollPane8 = new javax.swing.JScrollPane();
        lstIntegrantesFueraPIndustrial = new javax.swing.JList();
        jLabel15 = new javax.swing.JLabel();
        tfBuscarIntegrantePIndustrial = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tfNroRegistro = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jxdpFecha = new org.jdesktop.swingx.JXDatePicker();
        jLabel6 = new javax.swing.JLabel();
        tfPais = new javax.swing.JTextField();
        btnAceptar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(diagProyectoResultadoPIndustrial.class, "diagProyectoResultadoPIndustrial.jPanel1.border.title"))); // NOI18N

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        taProyectoPIndustrial.setColumns(20);
        taProyectoPIndustrial.setEditable(false);
        taProyectoPIndustrial.setFont(new java.awt.Font("Monospaced", 0, 11)); // NOI18N
        taProyectoPIndustrial.setRows(5);
        jScrollPane1.setViewportView(taProyectoPIndustrial);

        jLabel1.setText(org.openide.util.NbBundle.getMessage(diagProyectoResultadoPIndustrial.class, "diagProyectoResultadoPIntelectual.jLabel1.text")); // NOI18N

        btnBuscarProyectoPIndustrial.setText(org.openide.util.NbBundle.getMessage(diagProyectoResultadoPIndustrial.class, "diagProyectoResultadoPIntelectual.btnBuscarProyectoPIntelectual.text")); // NOI18N
        btnBuscarProyectoPIndustrial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarProyectoPIndustrialActionPerformed(evt);
            }
        });

        jLabel3.setText(org.openide.util.NbBundle.getMessage(diagProyectoResultadoPIndustrial.class, "diagProyectoResultadoPIntelectual.jLabel3.text")); // NOI18N

        tfTituloPIndustrial.setText(org.openide.util.NbBundle.getMessage(diagProyectoResultadoPIndustrial.class, "diagProyectoResultadoPIntelectual.tfTituloPIntelectual.text")); // NOI18N

        jLabel23.setText(org.openide.util.NbBundle.getMessage(diagProyectoResultadoPIndustrial.class, "diagProyectoResultadoPIntelectual.jLabel23.text")); // NOI18N

        jLabel2.setText(org.openide.util.NbBundle.getMessage(diagProyectoResultadoPIndustrial.class, "diagProyectoResultadoPIntelectual.jLabel2.text")); // NOI18N

        tfTitularesRegistro.setText(org.openide.util.NbBundle.getMessage(diagProyectoResultadoPIndustrial.class, "diagProyectoResultadoPIntelectual.tfTitularesRegistro.text")); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel23, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfTituloPIndustrial)
                            .addComponent(cboTipoRegistro, 0, 480, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(3, 3, 3)
                        .addComponent(tfTitularesRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnBuscarProyectoPIndustrial, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarProyectoPIndustrial))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfTituloPIndustrial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(cboTipoRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfTitularesRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanelAsesores2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), org.openide.util.NbBundle.getMessage(diagProyectoResultadoPIndustrial.class, "diagProyectoResultadoPIntelectual.jPanelAsesores2.border.title"))); // NOI18N

        jScrollPane7.setViewportView(lstIntegrantesDentroPIndustrial);

        btnAgregarIntegrantePIndustrial.setText(org.openide.util.NbBundle.getMessage(diagProyectoResultadoPIndustrial.class, "diagProyectoResultadoPIntelectual.btnAgregarIntegrantePIntelectual.text")); // NOI18N
        btnAgregarIntegrantePIndustrial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarIntegrantePIndustrialActionPerformed(evt);
            }
        });

        btnQuitarIntegrantePIndustrial.setText(org.openide.util.NbBundle.getMessage(diagProyectoResultadoPIndustrial.class, "diagProyectoResultadoPIntelectual.btnQuitarIntegrantePIntelectual.text")); // NOI18N
        btnQuitarIntegrantePIndustrial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitarIntegrantePIndustrialActionPerformed(evt);
            }
        });

        jScrollPane8.setViewportView(lstIntegrantesFueraPIndustrial);

        jLabel15.setText(org.openide.util.NbBundle.getMessage(diagProyectoResultadoPIndustrial.class, "diagProyectoResultadoPIntelectual.jLabel15.text")); // NOI18N

        tfBuscarIntegrantePIndustrial.setText(org.openide.util.NbBundle.getMessage(diagProyectoResultadoPIndustrial.class, "diagProyectoResultadoPIntelectual.tfBuscarIntegrantePIntelectual.text")); // NOI18N
        tfBuscarIntegrantePIndustrial.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfBuscarIntegrantePIndustrialKeyPressed(evt);
            }
        });

        jLabel16.setText(org.openide.util.NbBundle.getMessage(diagProyectoResultadoPIndustrial.class, "diagProyectoResultadoPIntelectual.jLabel16.text")); // NOI18N

        jLabel17.setText(org.openide.util.NbBundle.getMessage(diagProyectoResultadoPIndustrial.class, "diagProyectoResultadoPIntelectual.jLabel17.text")); // NOI18N

        javax.swing.GroupLayout jPanelAsesores2Layout = new javax.swing.GroupLayout(jPanelAsesores2);
        jPanelAsesores2.setLayout(jPanelAsesores2Layout);
        jPanelAsesores2Layout.setHorizontalGroup(
            jPanelAsesores2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAsesores2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelAsesores2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelAsesores2Layout.createSequentialGroup()
                        .addGroup(jPanelAsesores2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelAsesores2Layout.createSequentialGroup()
                                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)
                                .addGroup(jPanelAsesores2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnAgregarIntegrantePIndustrial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnQuitarIntegrantePIndustrial, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAsesores2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel15)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(jPanelAsesores2Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(352, 352, 352)))
                .addGroup(jPanelAsesores2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel17)
                    .addComponent(tfBuscarIntegrantePIndustrial)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelAsesores2Layout.setVerticalGroup(
            jPanelAsesores2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAsesores2Layout.createSequentialGroup()
                .addGroup(jPanelAsesores2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelAsesores2Layout.createSequentialGroup()
                        .addGroup(jPanelAsesores2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(tfBuscarIntegrantePIndustrial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelAsesores2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelAsesores2Layout.createSequentialGroup()
                                .addComponent(btnAgregarIntegrantePIndustrial)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnQuitarIntegrantePIndustrial))
                            .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelAsesores2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel4.setText(org.openide.util.NbBundle.getMessage(diagProyectoResultadoPIndustrial.class, "diagProyectoResultadoPIntelectual.jLabel4.text")); // NOI18N

        tfNroRegistro.setText(org.openide.util.NbBundle.getMessage(diagProyectoResultadoPIndustrial.class, "diagProyectoResultadoPIntelectual.tfNroRegistro.text")); // NOI18N

        jLabel5.setText(org.openide.util.NbBundle.getMessage(diagProyectoResultadoPIndustrial.class, "diagProyectoResultadoPIntelectual.jLabel5.text")); // NOI18N

        jxdpFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jxdpFechaActionPerformed(evt);
            }
        });

        jLabel6.setText(org.openide.util.NbBundle.getMessage(diagProyectoResultadoPIndustrial.class, "diagProyectoResultadoPIntelectual.jLabel6.text")); // NOI18N

        tfPais.setText(org.openide.util.NbBundle.getMessage(diagProyectoResultadoPIndustrial.class, "diagProyectoResultadoPIntelectual.tfPais.text")); // NOI18N

        btnAceptar.setText(org.openide.util.NbBundle.getMessage(diagProyectoResultadoPIndustrial.class, "diagProyectoResultadoPIntelectual.btnAceptar.text")); // NOI18N
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanelAsesores2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(2, 2, 2)
                                        .addComponent(tfNroRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(28, 28, 28)
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jxdpFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(46, 46, 46)
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tfPais, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(311, 311, 311)
                        .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelAsesores2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfNroRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jxdpFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(tfPais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAceptar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarProyectoPIndustrialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarProyectoPIndustrialActionPerformed
   }//GEN-LAST:event_btnBuscarProyectoPIndustrialActionPerformed

    private void btnAgregarIntegrantePIndustrialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarIntegrantePIndustrialActionPerformed
        agregarIntegrantePIndustrial();
    }//GEN-LAST:event_btnAgregarIntegrantePIndustrialActionPerformed

    private void btnQuitarIntegrantePIndustrialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitarIntegrantePIndustrialActionPerformed
        quitarIntegrantePIndustrial();
    }//GEN-LAST:event_btnQuitarIntegrantePIndustrialActionPerformed

    private void tfBuscarIntegrantePIndustrialKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfBuscarIntegrantePIndustrialKeyPressed
        buscarIntegrantePIntelectual();
    }//GEN-LAST:event_tfBuscarIntegrantePIndustrialKeyPressed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        aceptar();
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void jxdpFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jxdpFechaActionPerformed
        Comunes.validarjxdatepicker(jxdpFecha);
    }//GEN-LAST:event_jxdpFechaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(diagProyectoResultadoPIntelectual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(diagProyectoResultadoPIntelectual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(diagProyectoResultadoPIntelectual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(diagProyectoResultadoPIntelectual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the dialog
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                diagProyectoResultadoPIndustrial dialog = new diagProyectoResultadoPIndustrial(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnAgregarIntegrantePIndustrial;
    private javax.swing.JButton btnBuscarProyectoPIndustrial;
    private javax.swing.JButton btnQuitarIntegrantePIndustrial;
    private javax.swing.JComboBox cboTipoRegistro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelAsesores2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private org.jdesktop.swingx.JXDatePicker jxdpFecha;
    private javax.swing.JList lstIntegrantesDentroPIndustrial;
    private javax.swing.JList lstIntegrantesFueraPIndustrial;
    private javax.swing.JTextArea taProyectoPIndustrial;
    private javax.swing.JTextField tfBuscarIntegrantePIndustrial;
    private javax.swing.JTextField tfNroRegistro;
    private javax.swing.JTextField tfPais;
    private javax.swing.JTextField tfTitularesRegistro;
    private javax.swing.JTextField tfTituloPIndustrial;
    // End of variables declaration//GEN-END:variables

    private void inicializarComponentes() {
        Comunes.formatearJXdatePicker(jxdpFecha);
        Comunes.autoAjusteTextArea(taProyectoPIndustrial);
        cboTipoRegistro.setModel(new javax.swing.DefaultComboBoxModel(TipoRegistroIndustrial.values()));
        if (tipoOperacion.equals("Alta")) {
            cargarIntegrantesProyecto();
        } else if (tipoOperacion.equals("Modificación")) {
            tfTituloPIndustrial.setText(pIndustrial.getTitulo());
            cboTipoRegistro.setSelectedItem(pIndustrial.getTipoRegistroIndustrial());
            tfTitularesRegistro.setText(pIndustrial.getTitulares());
            cargarIntegrantesPIndustrial();
            tfNroRegistro.setText(pIndustrial.getNroRegistro());
            try{
                jxdpFecha.setDate(pIndustrial.getFecha());
            }catch(Exception e){
                
            }
            
            tfPais.setText(pIndustrial.getPais());
        }
    }

    private void cargarIntegrantesProyecto() {
        List<Investigador> lista = new ArrayList<Investigador>();
        if(proyectoPIndustrial != null){
        lista = ProyectoFacade.getInstance().getTodosIntegrantes(proyectoPIndustrial);
            
        }
        if(proyectoVinculacionPIndustrial != null){
        lista = ProyectoVinculacionFacade.getInstance().getTodosIntegrantes(proyectoVinculacionPIndustrial);
            
        }
        
        for (Object objeto : lista) {
            participantesDentroPIndustrial.add((Investigador) objeto);
        }
        Comunes.cargarJList(lstIntegrantesDentroPIndustrial, participantesDentroPIndustrial);
        List<Investigador> participanteFueraPIndustrial = InvestigadorFacade.getInstance().getTodosInvestigador();
        participanteFueraPIndustrial.removeAll(participantesDentroPIndustrial);
        Comunes.cargarJList(lstIntegrantesFueraPIndustrial, participanteFueraPIndustrial);
    }

    private void cargarIntegrantesPIndustrial() {
        participantesDentroPIndustrial = pIndustrial.getInvestigadores();
        Comunes.cargarJList(lstIntegrantesDentroPIndustrial, participantesDentroPIndustrial);
        List<Investigador> participanteFueraPIndustrial = InvestigadorFacade.getInstance().getTodosInvestigador();
        participanteFueraPIndustrial.removeAll(participantesDentroPIndustrial);
        Comunes.cargarJList(lstIntegrantesFueraPIndustrial, participanteFueraPIndustrial);
    }

    private void buscarIntegrantePIntelectual() {
    }

    private void agregarIntegrantePIndustrial() {
       if (lstIntegrantesFueraPIndustrial.getSelectedIndex() != -1) {

            participantesDentroPIndustrial.add((Investigador) lstIntegrantesFueraPIndustrial.getSelectedValue());
            List<Investigador> participantesFuera = InvestigadorFacade.getInstance().getTodosInvestigador();
            participantesFuera.removeAll(participantesDentroPIndustrial);
            Comunes.cargarJList(lstIntegrantesFueraPIndustrial, participantesFuera);

            Comunes.cargarJList(lstIntegrantesDentroPIndustrial, participantesDentroPIndustrial);

        } else {
            JOptionPane.showMessageDialog(rootPane, "Debe escoger un Integrante", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void quitarIntegrantePIndustrial() {
        if (lstIntegrantesDentroPIndustrial.getSelectedIndex() != -1) {

            participantesDentroPIndustrial.remove((Investigador) lstIntegrantesDentroPIndustrial.getSelectedValue());
            List<Investigador> participantesFuera = InvestigadorFacade.getInstance().getTodosInvestigador();
            participantesFuera.removeAll(participantesDentroPIndustrial);
            Comunes.cargarJList(lstIntegrantesFueraPIndustrial, participantesFuera);

            Comunes.cargarJList(lstIntegrantesDentroPIndustrial, participantesDentroPIndustrial);

        }
    }

    private void aceptar() {
        Industrial pIndustria = new Industrial();
        PropiedadFacade.getInstance().alta(pIndustria);
        if (validar()) {
            if (tipoOperacion.equals("Alta")) {
                pIndustrial = new Industrial();
                
                if(proyectoPIndustrial != null){
                    
                List<Proyecto> proyecto = new ArrayList<Proyecto>();
                proyecto.add(proyectoPIndustrial);
                pIndustrial.setProyectos(proyecto);
                
                }
                
                if(proyectoVinculacionPIndustrial != null){
                    
                List<ProyectoVinculacion> proyectoVinculacion = new ArrayList<ProyectoVinculacion>();
                proyectoVinculacion.add(proyectoVinculacionPIndustrial);
                pIndustrial.setProyectosVinculacion(proyectoVinculacion);
                
                }
                if (!tfTituloPIndustrial.getText().equals("")) {
                    pIndustrial.setTitulo(tfTituloPIndustrial.getText());
                } else {
                    pIndustrial.setTitulo(null);
                }
                pIndustrial.setTipoRegistroIndustrial((TipoRegistroIndustrial)cboTipoRegistro.getSelectedItem());
                if (!tfTitularesRegistro.getText().equals("")) {
                    pIndustrial.setTitulares(tfTitularesRegistro.getText());
                } else {
                    pIndustrial.setTitulares(null);
                }
                if (participantesDentroPIndustrial.size() > 0) {
                    pIndustrial.setInvestigadores(participantesDentroPIndustrial);
                } else {
                    pIndustrial.setInvestigadores(null);
                }
                if (!tfNroRegistro.getText().equals("")) {
                    pIndustrial.setNroRegistro(tfNroRegistro.getText());
                } else {
                    pIndustrial.setNroRegistro(null);
                }
                pIndustrial.setFecha(jxdpFecha.getDate());
                if (!tfPais.getText().equals("")) {
                    pIndustrial.setPais(tfPais.getText());
                } else {
                    pIndustrial.setPais(null);
                }
                PropiedadFacade.getInstance().alta(pIndustrial);
                /*Operacion operacion = new Operacion();
                operacion.setUsuario(usuario);
                operacion.setOperacion("Alta de Propiedad intelectual");
                operacion.setFecha(Comunes.obtenerFechaActualDesdeDB());
                OperacionFacade.getInstance().alta(operacion);*/

                JOptionPane.showMessageDialog(null, "Propiedad industrial agregada");
                this.dispose();
            }else if(tipoOperacion.equals("Modificación")){
                
                if(!tfTituloPIndustrial.getText().equals("")){
                    pIndustrial.setTitulo(tfTituloPIndustrial.getText());
                }else{
                    pIndustrial.setTitulo(null);
                }
                pIndustrial.setTipoRegistroIndustrial((TipoRegistroIndustrial)cboTipoRegistro.getSelectedItem());
                if (!tfTitularesRegistro.getText().equals("")){
                    pIndustrial.setTitulares(tfTitularesRegistro.getText());
                }else{
                    pIndustrial.setTitulares(null);
                }
                if(participantesDentroPIndustrial.size()>0){
                    pIndustrial.setInvestigadores(participantesDentroPIndustrial);
                }else{
                    pIndustrial.setInvestigadores(null);
                }
                if(!tfNroRegistro.getText().equals("")){
                    pIndustrial.setNroRegistro(tfNroRegistro.getText());
                }else{
                    pIndustrial.setNroRegistro(null);
                }
                pIndustrial.setFecha(jxdpFecha.getDate());
                if(!tfPais.getText().equals("")){
                    pIndustrial.setPais(tfPais.getText());
                }else{
                    pIndustrial.setPais(null);
                }
                try {
                    PropiedadFacade.getInstance().modificar(pIndustrial);

                   /* Operacion operacion = new Operacion();
                    operacion.setUsuario(usuario);
                    operacion.setOperacion("Modificación de Propiedad intelectual");
                    operacion.setFecha(Comunes.obtenerFechaActualDesdeDB());
                    OperacionFacade.getInstance().alta(operacion);*/

                    JOptionPane.showMessageDialog(null, "Propiedad industri modificada");

                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(null, "Error Modificando Propiedad industriall\n " + ex);
                }
                this.dispose();
            }

        }
    }

    private boolean validar() {
        boolean flag = false;
        if (proyectoPIndustrial != null || proyectoVinculacionPIndustrial != null) {
            if (!tfTituloPIndustrial.getText().isEmpty()) {
                if (!participantesDentroPIndustrial.isEmpty()) {
                    flag = true;
                } else {
                    JOptionPane.showMessageDialog(null, "Debe seleccionar algun integrante");
                }

            } else {
                JOptionPane.showMessageDialog(null, "Debe poseer un titulo");
                tfTituloPIndustrial.requestFocus();
            }
        }
        return flag;
    }

    
}
