/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.proyectos.resultado;

import entidades.operaciones.Operacion;
import entidades.proyecto.Proyecto;
import entidades.proyecto.resultado.Contrato;
import entidades.proyecto.resultado.TipoContrato;
import entidades.proyecto.vinculacion.ProyectoVinculacion;
import entidades.usuario.Usuario;
import facade.ContratoFacade;
import includes.Comunes;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author hugo
 */
public class diagProyectoResultadoContrato extends javax.swing.JDialog {

    private String TipoOperacion;
    private Proyecto proyectoContrato;
    private ProyectoVinculacion proyectoVinculacionContrato;
    private Usuario usuario;
    private Contrato contrato;

    public Contrato getContrato() {
        return contrato;
    }

    /**
     * Creates new form diagProyectoResultadoContrato
     */
    public diagProyectoResultadoContrato(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public diagProyectoResultadoContrato(java.awt.Frame parent, boolean modal, String tipoOperacion, Usuario usuario) {
        super(parent, modal);
        this.TipoOperacion = tipoOperacion;
        this.usuario = usuario;
        initComponents();
        inicializarComponentes();
        btnBuscarProyectoContrato.setVisible(true);
    }

    public diagProyectoResultadoContrato(java.awt.Frame parent, boolean modal, String tipoOperacion, Proyecto proyecto, Usuario usuario) {
        super(parent, modal);
        this.TipoOperacion = tipoOperacion;
        this.proyectoContrato = proyecto;
        this.usuario = usuario;
        initComponents();
        inicializarComponentes();
        btnBuscarProyectoContrato.setVisible(false);
        taProyectoContrato.setText(proyectoContrato.toString());

    }

    public diagProyectoResultadoContrato(java.awt.Frame parent, boolean modal, String tipoOperacion, Proyecto proyecto, Contrato contrato, Usuario usuario) {
        super(parent, modal);
        this.TipoOperacion = tipoOperacion;
        this.proyectoContrato = proyecto;
        this.contrato = contrato;
        this.usuario = usuario;
        initComponents();
        inicializarComponentes();
        btnBuscarProyectoContrato.setVisible(false);
        taProyectoContrato.setText(proyectoContrato.toString());

    }

    public diagProyectoResultadoContrato(java.awt.Frame parent, boolean modal, String tipoOperacion, ProyectoVinculacion proyectoVinculacion, Usuario usuario) {
        super(parent, modal);
        this.TipoOperacion = tipoOperacion;
        this.proyectoVinculacionContrato = proyectoVinculacion;
        this.usuario = usuario;
        initComponents();
        inicializarComponentes();
        btnBuscarProyectoContrato.setVisible(false);
        taProyectoContrato.setText(proyectoVinculacionContrato.toString());

    }

    public diagProyectoResultadoContrato(java.awt.Frame parent, boolean modal, String tipoOperacion, ProyectoVinculacion proyectoVinculacion, Contrato contrato, Usuario usuario) {
        super(parent, modal);
        this.TipoOperacion = tipoOperacion;
        this.proyectoVinculacionContrato = proyectoVinculacion;
        this.contrato = contrato;
        this.usuario = usuario;
        initComponents();
        inicializarComponentes();
        btnBuscarProyectoContrato.setVisible(false);
        taProyectoContrato.setText(proyectoVinculacionContrato.toString());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taProyectoContrato = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        btnBuscarProyectoContrato = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        tfDestinatarios = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        cboTipoContrato = new javax.swing.JComboBox();
        tfMontoObtenido = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jxdpFechaContrato = new org.jdesktop.swingx.JXDatePicker();
        jLabel6 = new javax.swing.JLabel();
        tfObjeto = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(diagProyectoResultadoContrato.class, "diagProyectoResultadoContrato.jPanel2.border.title"))); // NOI18N

        taProyectoContrato.setColumns(20);
        taProyectoContrato.setEditable(false);
        taProyectoContrato.setFont(new java.awt.Font("Monospaced", 0, 11)); // NOI18N
        taProyectoContrato.setRows(5);
        jScrollPane1.setViewportView(taProyectoContrato);

        jLabel1.setText(org.openide.util.NbBundle.getMessage(diagProyectoResultadoContrato.class, "diagProyectoResultadoContrato.jLabel1.text")); // NOI18N

        btnBuscarProyectoContrato.setText(org.openide.util.NbBundle.getMessage(diagProyectoResultadoContrato.class, "diagProyectoResultadoContrato.btnBuscarProyectoContrato.text")); // NOI18N
        btnBuscarProyectoContrato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarProyectoContratoActionPerformed(evt);
            }
        });

        jLabel3.setText(org.openide.util.NbBundle.getMessage(diagProyectoResultadoContrato.class, "diagProyectoResultadoContrato.jLabel3.text")); // NOI18N

        tfDestinatarios.setText(org.openide.util.NbBundle.getMessage(diagProyectoResultadoContrato.class, "diagProyectoResultadoContrato.tfDestinatarios.text")); // NOI18N

        jLabel23.setText(org.openide.util.NbBundle.getMessage(diagProyectoResultadoContrato.class, "diagProyectoResultadoContrato.jLabel23.text")); // NOI18N

        tfMontoObtenido.setText(org.openide.util.NbBundle.getMessage(diagProyectoResultadoContrato.class, "diagProyectoResultadoContrato.tfMontoObtenido.text")); // NOI18N

        jLabel2.setText(org.openide.util.NbBundle.getMessage(diagProyectoResultadoContrato.class, "diagProyectoResultadoContrato.jLabel2.text")); // NOI18N

        jLabel4.setText(org.openide.util.NbBundle.getMessage(diagProyectoResultadoContrato.class, "diagProyectoResultadoContrato.jLabel4.text")); // NOI18N

        jLabel5.setText(org.openide.util.NbBundle.getMessage(diagProyectoResultadoContrato.class, "diagProyectoResultadoContrato.jLabel5.text")); // NOI18N

        jxdpFechaContrato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jxdpFechaContratoActionPerformed(evt);
            }
        });

        jLabel6.setText(org.openide.util.NbBundle.getMessage(diagProyectoResultadoContrato.class, "diagProyectoResultadoContrato.jLabel6.text")); // NOI18N

        tfObjeto.setText(org.openide.util.NbBundle.getMessage(diagProyectoResultadoContrato.class, "diagProyectoResultadoContrato.tfObjeto.text")); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel23)
                                    .addComponent(jLabel3)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel4))
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tfDestinatarios, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)
                                    .addComponent(cboTipoContrato, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfMontoObtenido, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jxdpFechaContrato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfObjeto))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addComponent(btnBuscarProyectoContrato, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarProyectoContrato))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cboTipoContrato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfDestinatarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfObjeto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfMontoObtenido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jxdpFechaContrato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
        );

        jButton1.setText(org.openide.util.NbBundle.getMessage(diagProyectoResultadoContrato.class, "diagProyectoResultadoContrato.jButton1.text")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(325, 325, 325)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarProyectoContratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarProyectoContratoActionPerformed
   }//GEN-LAST:event_btnBuscarProyectoContratoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        aceptar();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jxdpFechaContratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jxdpFechaContratoActionPerformed
        Comunes.validarjxdatepicker(jxdpFechaContrato);
    }//GEN-LAST:event_jxdpFechaContratoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(diagProyectoResultadoContrato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(diagProyectoResultadoContrato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(diagProyectoResultadoContrato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(diagProyectoResultadoContrato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the dialog
         */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                diagProyectoResultadoContrato dialog = new diagProyectoResultadoContrato(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarProyectoContrato;
    private javax.swing.JComboBox cboTipoContrato;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private org.jdesktop.swingx.JXDatePicker jxdpFechaContrato;
    private javax.swing.JTextArea taProyectoContrato;
    private javax.swing.JTextField tfDestinatarios;
    private javax.swing.JTextField tfMontoObtenido;
    private javax.swing.JTextField tfObjeto;
    // End of variables declaration//GEN-END:variables

    private void inicializarComponentes() {
        Comunes.formatearJXdatePicker(jxdpFechaContrato);
        Comunes.autoAjusteTextArea(taProyectoContrato);
        cboTipoContrato.setModel(new javax.swing.DefaultComboBoxModel(TipoContrato.values()));
        if (TipoOperacion.equals("Modificación")) {
            cboTipoContrato.setSelectedItem(contrato.getTipoContrato());
            if (contrato.getDestinatarios() != null) {
                tfDestinatarios.setText(contrato.getDestinatarios());
            } else {
                tfDestinatarios.setText("");
            }
            if (contrato.getObjeto() != null) {
                tfObjeto.setText(contrato.getObjeto());
            } else {
                tfObjeto.setText("");
            }
            if (contrato.getMontoObtenido() != null) {
                tfMontoObtenido.setText(contrato.getMontoObtenido().toString());
            } else {
                tfMontoObtenido.setText("");
            }
            try {
                jxdpFechaContrato.setDate(contrato.getFechaContrato());
            } catch (Exception e) {
            }

        }
    }

    private void aceptar() {
        if (validar()) {
            switch (TipoOperacion) {
                case "Alta":
                    contrato = new Contrato();

                    if (proyectoContrato != null) {
                        List<Proyecto> proyectos = new ArrayList<Proyecto>();
                        proyectos.add(proyectoContrato);
                        contrato.setProyectos(proyectos);

                    }
                    if (proyectoVinculacionContrato != null) {
                        List<ProyectoVinculacion> proyectosVinculacion = new ArrayList<ProyectoVinculacion>();
                        proyectosVinculacion.add(proyectoVinculacionContrato);
                        contrato.setProyectosVinculacion(proyectosVinculacion);
                    }
                    contrato.setTipoContrato((TipoContrato) cboTipoContrato.getSelectedItem());
                    if (!tfDestinatarios.getText().isEmpty()) {
                        contrato.setDestinatarios(tfDestinatarios.getText());
                    } else {
                        contrato.setDestinatarios(null);
                    }
                    if (!tfObjeto.getText().isEmpty()) {
                        contrato.setObjeto(tfObjeto.getText());
                    } else {
                        contrato.setDestinatarios(null);
                    }
                    if (!tfMontoObtenido.getText().isEmpty()) {
                        contrato.setMontoObtenido(BigDecimal.valueOf(Double.parseDouble(tfMontoObtenido.getText())));
                    } else {
                        contrato.setMontoObtenido(null);
                    }
                    contrato.setFechaContrato(jxdpFechaContrato.getDate());
                    ContratoFacade.getInstance().alta(contrato);
                    JOptionPane.showMessageDialog(null, "Contrato agregado");
                    this.dispose();
                    break;
                case "Modificación":
                    contrato.setTipoContrato((TipoContrato) cboTipoContrato.getSelectedItem());
                    if (!tfDestinatarios.getText().equals("")) {
                        contrato.setDestinatarios(tfDestinatarios.getText());
                    } else {
                        contrato.setDestinatarios(null);
                    }
                    if (!tfObjeto.getText().equals("")) {
                        contrato.setObjeto(tfObjeto.getText());
                    } else {
                        contrato.setObjeto(null);
                    }
                    if (!tfMontoObtenido.getText().equals("")) {
                        contrato.setMontoObtenido(BigDecimal.valueOf(Double.parseDouble(tfMontoObtenido.getText())));
                    } else {
                        contrato.setMontoObtenido(null);
                    }
                    contrato.setFechaContrato(jxdpFechaContrato.getDate());
                    try {
                        ContratoFacade.getInstance().modificar(contrato);
                        Operacion operacion = new Operacion();
                        operacion.setFecha(Comunes.obtenerFechaActualDesdeDB());
                        operacion.setOperacion("Modificacion de Contrato");
                        operacion.setUsuario(usuario);
                        JOptionPane.showMessageDialog(null, "Contrato Modificado");
                    } catch (Exception ex) {
                        JOptionPane.showMessageDialog(null, "Error al modificar el contrato" + ex);
                    }
                    this.dispose();
                    break;
            }
        }
    }

    private boolean validar() {
        boolean flag = false;
        if (proyectoContrato != null || proyectoVinculacionContrato != null) {
            if (!tfDestinatarios.getText().isEmpty()) {
                if (!tfObjeto.getText().isEmpty()) {
                    if (!tfMontoObtenido.getText().isEmpty()
                            && Comunes.validarBigDecimal(tfMontoObtenido.getText())) {
                        flag = true;
                    } else {
                        JOptionPane.showMessageDialog(null, "Debe escribir importe solo con numeros");
                        tfMontoObtenido.requestFocus();
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Debe escribir Objeto del Contrato");
                    tfObjeto.requestFocus();
                }
            } else {
                JOptionPane.showMessageDialog(null, "Debe escribir Destinatarios del contrato");
                tfDestinatarios.requestFocus();
            }
        }
        return flag;

    }
}
