/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.proyectos.resultado;

import entidades.operaciones.Operacion;
import entidades.persona.investigador.Investigador;
import entidades.proyecto.Proyecto;
import entidades.proyecto.resultado.CapituloLibro;
import entidades.proyecto.resultado.Libro;
import entidades.proyecto.resultado.TipoEdicion;
import entidades.proyecto.vinculacion.ProyectoVinculacion;
import entidades.usuario.Usuario;
import facade.InvestigadorFacade;
import facade.OperacionFacade;
import facade.ProyectoFacade;
import facade.ProyectoVinculacionFacade;
import facade.PublicacionFacade;
import includes.Comunes;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author hugo
 */
public class diagProyectoResultadoCapitulo extends javax.swing.JDialog {

    private Proyecto proyectoCapitulo;
    private ProyectoVinculacion proyectoVinculacionCapitulo;
    private CapituloLibro capitulo;
    private List<Investigador> integrantesDentroCapitulo = new ArrayList<Investigador>();
    private List<Investigador> integrantesFueraCapitulo = new ArrayList<Investigador>();
    private Libro libro;
    private String tipoOperacion;
    private Usuario usuario;

    /**
     * Creates new form diagProyectoResultadoCapitulo
     */
    public diagProyectoResultadoCapitulo(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        inicializarComponentes();
    }

    public diagProyectoResultadoCapitulo(java.awt.Frame parent, boolean modal, String tipoOperacion, Proyecto proyecto, Usuario usuario) {
        super(parent, modal);
        this.proyectoCapitulo = proyecto;
        this.tipoOperacion = tipoOperacion;
        this.usuario = usuario;
        initComponents();
        inicializarComponentes();
        btnBuscarProyectoCapitulo.setVisible(false);
        taProyectoCapitulo.setText(proyectoCapitulo.toString());

    }

    public diagProyectoResultadoCapitulo(java.awt.Frame parent, boolean modal, String tipoOperacion, Proyecto proyecto, CapituloLibro capitulo, Usuario usuario) {
        super(parent, modal);
        this.proyectoCapitulo = proyecto;
        this.capitulo = capitulo;
        this.tipoOperacion = tipoOperacion;
        this.usuario = usuario;
        initComponents();
        inicializarComponentes();
        btnBuscarProyectoCapitulo.setVisible(false);
        taProyectoCapitulo.setText(proyectoCapitulo.toString());

    }
    
    public diagProyectoResultadoCapitulo(java.awt.Frame parent, boolean modal, String tipoOperacion, ProyectoVinculacion proyectoVinculacion, Usuario usuario) {
        super(parent, modal);
        this.proyectoVinculacionCapitulo = proyectoVinculacion;
        this.tipoOperacion = tipoOperacion;
        this.usuario = usuario;
        initComponents();
        inicializarComponentes();
        btnBuscarProyectoCapitulo.setVisible(false);
        taProyectoCapitulo.setText(proyectoVinculacionCapitulo.toString());

    }

    public diagProyectoResultadoCapitulo(java.awt.Frame parent, boolean modal, String tipoOperacion, ProyectoVinculacion proyectoVinculacion, CapituloLibro capitulo, Usuario usuario) {
        super(parent, modal);
        this.proyectoVinculacionCapitulo = proyectoVinculacion;
        this.capitulo = capitulo;
        this.tipoOperacion = tipoOperacion;
        this.usuario = usuario;
        initComponents();
        inicializarComponentes();
        btnBuscarProyectoCapitulo.setVisible(false);
        taProyectoCapitulo.setText(proyectoVinculacionCapitulo.toString());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanelAsesores2 = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        lstIntegrantesDentroCapitulo = new javax.swing.JList();
        btnAgregarAutorCapitulo = new javax.swing.JButton();
        btnQuitarAutorCapitulo = new javax.swing.JButton();
        jScrollPane8 = new javax.swing.JScrollPane();
        lsIntegrantesFueraCapitulo = new javax.swing.JList();
        jLabel15 = new javax.swing.JLabel();
        tfBuscarAutorCapitulo = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        tfLibro = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnBuscarLibro = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        taProyectoCapitulo = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        btnBuscarProyectoCapitulo = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        tfcapitulo = new javax.swing.JTextField();
        tfEditorCapitulo = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        tfNombreLibro = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jxdpEnviadoCapitulo = new org.jdesktop.swingx.JXDatePicker();
        jLabel14 = new javax.swing.JLabel();
        jxdpAceptadoCapitulo = new org.jdesktop.swingx.JXDatePicker();
        jLabel18 = new javax.swing.JLabel();
        jxdpPublicadoCapitulo = new org.jdesktop.swingx.JXDatePicker();
        jLabel19 = new javax.swing.JLabel();
        cboEdicionCapitulo = new javax.swing.JComboBox();
        jLabel20 = new javax.swing.JLabel();
        tfISBNCapitulo = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        tfAnioCapitulo = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        tfLugarCapitulo = new javax.swing.JTextField();
        btnAgregarCapitulo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(diagProyectoResultadoCapitulo.class, "diagProyectoResultadoCapitulo.jPanel1.border.title"))); // NOI18N

        jPanelAsesores2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), org.openide.util.NbBundle.getMessage(diagProyectoResultadoCapitulo.class, "diagProyectoResultadoCapitulo.jPanelAsesores2.border.title"))); // NOI18N

        jScrollPane7.setViewportView(lstIntegrantesDentroCapitulo);

        btnAgregarAutorCapitulo.setText(org.openide.util.NbBundle.getMessage(diagProyectoResultadoCapitulo.class, "diagProyectoResultadoCapitulo.btnAgregarAutorCapitulo.text")); // NOI18N
        btnAgregarAutorCapitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarAutorCapituloActionPerformed(evt);
            }
        });

        btnQuitarAutorCapitulo.setText(org.openide.util.NbBundle.getMessage(diagProyectoResultadoCapitulo.class, "diagProyectoResultadoCapitulo.btnQuitarAutorCapitulo.text")); // NOI18N
        btnQuitarAutorCapitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitarAutorCapituloActionPerformed(evt);
            }
        });

        jScrollPane8.setViewportView(lsIntegrantesFueraCapitulo);

        jLabel15.setText(org.openide.util.NbBundle.getMessage(diagProyectoResultadoCapitulo.class, "diagProyectoResultadoCapitulo.jLabel15.text")); // NOI18N

        tfBuscarAutorCapitulo.setText(org.openide.util.NbBundle.getMessage(diagProyectoResultadoCapitulo.class, "diagProyectoResultadoCapitulo.tfBuscarAutorCapitulo.text")); // NOI18N
        tfBuscarAutorCapitulo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfBuscarAutorCapituloKeyPressed(evt);
            }
        });

        jLabel16.setText(org.openide.util.NbBundle.getMessage(diagProyectoResultadoCapitulo.class, "diagProyectoResultadoCapitulo.jLabel16.text")); // NOI18N

        jLabel17.setText(org.openide.util.NbBundle.getMessage(diagProyectoResultadoCapitulo.class, "diagProyectoResultadoCapitulo.jLabel17.text")); // NOI18N

        javax.swing.GroupLayout jPanelAsesores2Layout = new javax.swing.GroupLayout(jPanelAsesores2);
        jPanelAsesores2.setLayout(jPanelAsesores2Layout);
        jPanelAsesores2Layout.setHorizontalGroup(
            jPanelAsesores2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAsesores2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelAsesores2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelAsesores2Layout.createSequentialGroup()
                        .addGroup(jPanelAsesores2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelAsesores2Layout.createSequentialGroup()
                                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(68, 68, 68)
                                .addGroup(jPanelAsesores2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnAgregarAutorCapitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnQuitarAutorCapitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAsesores2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel15)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(jPanelAsesores2Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(352, 352, 352)))
                .addGroup(jPanelAsesores2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel17)
                    .addComponent(tfBuscarAutorCapitulo)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelAsesores2Layout.setVerticalGroup(
            jPanelAsesores2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAsesores2Layout.createSequentialGroup()
                .addGroup(jPanelAsesores2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelAsesores2Layout.createSequentialGroup()
                        .addGroup(jPanelAsesores2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(tfBuscarAutorCapitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelAsesores2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelAsesores2Layout.createSequentialGroup()
                                .addComponent(btnAgregarAutorCapitulo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnQuitarAutorCapitulo))
                            .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelAsesores2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tfLibro.setText(org.openide.util.NbBundle.getMessage(diagProyectoResultadoCapitulo.class, "diagProyectoResultadoCapitulo.tfLibro.text")); // NOI18N

        jLabel2.setText(org.openide.util.NbBundle.getMessage(diagProyectoResultadoCapitulo.class, "diagProyectoResultadoCapitulo.jLabel2.text")); // NOI18N

        btnBuscarLibro.setText(org.openide.util.NbBundle.getMessage(diagProyectoResultadoCapitulo.class, "diagProyectoResultadoCapitulo.btnBuscarLibro.text")); // NOI18N
        btnBuscarLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarLibroActionPerformed(evt);
            }
        });

        taProyectoCapitulo.setColumns(20);
        taProyectoCapitulo.setEditable(false);
        taProyectoCapitulo.setFont(new java.awt.Font("Monospaced", 0, 11)); // NOI18N
        taProyectoCapitulo.setRows(5);
        jScrollPane1.setViewportView(taProyectoCapitulo);

        jLabel1.setText(org.openide.util.NbBundle.getMessage(diagProyectoResultadoCapitulo.class, "diagProyectoResultadoCapitulo.jLabel1.text")); // NOI18N

        btnBuscarProyectoCapitulo.setText(org.openide.util.NbBundle.getMessage(diagProyectoResultadoCapitulo.class, "diagProyectoResultadoCapitulo.btnBuscarProyectoCapitulo.text")); // NOI18N

        jLabel3.setText(org.openide.util.NbBundle.getMessage(diagProyectoResultadoCapitulo.class, "diagProyectoResultadoCapitulo.jLabel3.text")); // NOI18N

        tfcapitulo.setText(org.openide.util.NbBundle.getMessage(diagProyectoResultadoCapitulo.class, "diagProyectoResultadoCapitulo.tfcapitulo.text")); // NOI18N

        tfEditorCapitulo.setText(org.openide.util.NbBundle.getMessage(diagProyectoResultadoCapitulo.class, "diagProyectoResultadoCapitulo.tfEditorCapitulo.text")); // NOI18N

        jLabel23.setText(org.openide.util.NbBundle.getMessage(diagProyectoResultadoCapitulo.class, "diagProyectoResultadoCapitulo.jLabel23.text")); // NOI18N

        tfNombreLibro.setText(org.openide.util.NbBundle.getMessage(diagProyectoResultadoCapitulo.class, "diagProyectoResultadoCapitulo.tfNombreLibro.text")); // NOI18N

        jLabel4.setText(org.openide.util.NbBundle.getMessage(diagProyectoResultadoCapitulo.class, "diagProyectoResultadoCapitulo.jLabel4.text")); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel23))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfcapitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 502, Short.MAX_VALUE)
                            .addComponent(tfEditorCapitulo)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfLibro, javax.swing.GroupLayout.DEFAULT_SIZE, 502, Short.MAX_VALUE)
                            .addComponent(tfNombreLibro)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 504, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnBuscarProyectoCapitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(36, 36, 36))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnBuscarLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(24, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(btnBuscarProyectoCapitulo)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(btnBuscarLibro))
                .addGap(7, 7, 7)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfNombreLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfcapitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfEditorCapitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23)))
        );

        jLabel13.setText(org.openide.util.NbBundle.getMessage(diagProyectoResultadoCapitulo.class, "diagProyectoResultadoCapitulo.jLabel13.text")); // NOI18N

        jxdpEnviadoCapitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jxdpEnviadoCapituloActionPerformed(evt);
            }
        });

        jLabel14.setText(org.openide.util.NbBundle.getMessage(diagProyectoResultadoCapitulo.class, "diagProyectoResultadoCapitulo.jLabel14.text")); // NOI18N

        jxdpAceptadoCapitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jxdpAceptadoCapituloActionPerformed(evt);
            }
        });

        jLabel18.setText(org.openide.util.NbBundle.getMessage(diagProyectoResultadoCapitulo.class, "diagProyectoResultadoCapitulo.jLabel18.text")); // NOI18N

        jxdpPublicadoCapitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jxdpPublicadoCapituloActionPerformed(evt);
            }
        });

        jLabel19.setText(org.openide.util.NbBundle.getMessage(diagProyectoResultadoCapitulo.class, "diagProyectoResultadoCapitulo.jLabel19.text")); // NOI18N

        cboEdicionCapitulo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel20.setText(org.openide.util.NbBundle.getMessage(diagProyectoResultadoCapitulo.class, "diagProyectoResultadoCapitulo.jLabel20.text")); // NOI18N

        tfISBNCapitulo.setText(org.openide.util.NbBundle.getMessage(diagProyectoResultadoCapitulo.class, "diagProyectoResultadoCapitulo.tfISBNCapitulo.text")); // NOI18N

        jLabel21.setText(org.openide.util.NbBundle.getMessage(diagProyectoResultadoCapitulo.class, "diagProyectoResultadoCapitulo.jLabel21.text")); // NOI18N

        tfAnioCapitulo.setText(org.openide.util.NbBundle.getMessage(diagProyectoResultadoCapitulo.class, "diagProyectoResultadoCapitulo.tfAnioCapitulo.text")); // NOI18N

        jLabel22.setText(org.openide.util.NbBundle.getMessage(diagProyectoResultadoCapitulo.class, "diagProyectoResultadoCapitulo.jLabel22.text")); // NOI18N

        tfLugarCapitulo.setText(org.openide.util.NbBundle.getMessage(diagProyectoResultadoCapitulo.class, "diagProyectoResultadoCapitulo.tfLugarCapitulo.text")); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jxdpEnviadoCapitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel14)
                        .addGap(4, 4, 4)
                        .addComponent(jxdpAceptadoCapitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jxdpPublicadoCapitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cboEdicionCapitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfISBNCapitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfAnioCapitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addGap(18, 18, 18)
                        .addComponent(tfLugarCapitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jxdpEnviadoCapitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(jxdpAceptadoCapitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(jxdpPublicadoCapitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(cboEdicionCapitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20)
                    .addComponent(tfISBNCapitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21)
                    .addComponent(tfAnioCapitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(tfLugarCapitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 15, Short.MAX_VALUE))
        );

        btnAgregarCapitulo.setText(org.openide.util.NbBundle.getMessage(diagProyectoResultadoCapitulo.class, "diagProyectoResultadoCapitulo.btnAgregarCapitulo.text")); // NOI18N
        btnAgregarCapitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarCapituloActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanelAsesores2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnAgregarCapitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(325, 325, 325))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelAsesores2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAgregarCapitulo)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(40, 40, 40))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarAutorCapituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarAutorCapituloActionPerformed
        agregarAutorCapitulo();
    }//GEN-LAST:event_btnAgregarAutorCapituloActionPerformed

    private void btnQuitarAutorCapituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitarAutorCapituloActionPerformed
        quitarAutorCapitulo();
    }//GEN-LAST:event_btnQuitarAutorCapituloActionPerformed

    private void tfBuscarAutorCapituloKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfBuscarAutorCapituloKeyPressed
        buscarAutorCapitulo();
    }//GEN-LAST:event_tfBuscarAutorCapituloKeyPressed

    private void btnBuscarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarLibroActionPerformed
        buscarLibro();
    }//GEN-LAST:event_btnBuscarLibroActionPerformed

    private void btnAgregarCapituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarCapituloActionPerformed
        agregarCapitulo();
    }//GEN-LAST:event_btnAgregarCapituloActionPerformed

    private void jxdpEnviadoCapituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jxdpEnviadoCapituloActionPerformed
        Comunes.validarjxdatepicker(jxdpEnviadoCapitulo);
    }//GEN-LAST:event_jxdpEnviadoCapituloActionPerformed

    private void jxdpAceptadoCapituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jxdpAceptadoCapituloActionPerformed
        Comunes.validarjxdatepicker(jxdpAceptadoCapitulo);
    }//GEN-LAST:event_jxdpAceptadoCapituloActionPerformed

    private void jxdpPublicadoCapituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jxdpPublicadoCapituloActionPerformed
        Comunes.validarjxdatepicker(jxdpPublicadoCapitulo);
    }//GEN-LAST:event_jxdpPublicadoCapituloActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(diagProyectoResultadoCapitulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(diagProyectoResultadoCapitulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(diagProyectoResultadoCapitulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(diagProyectoResultadoCapitulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the dialog
         */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                diagProyectoResultadoCapitulo dialog = new diagProyectoResultadoCapitulo(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarAutorCapitulo;
    private javax.swing.JButton btnAgregarCapitulo;
    private javax.swing.JButton btnBuscarLibro;
    private javax.swing.JButton btnBuscarProyectoCapitulo;
    private javax.swing.JButton btnQuitarAutorCapitulo;
    private javax.swing.JComboBox cboEdicionCapitulo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelAsesores2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private org.jdesktop.swingx.JXDatePicker jxdpAceptadoCapitulo;
    private org.jdesktop.swingx.JXDatePicker jxdpEnviadoCapitulo;
    private org.jdesktop.swingx.JXDatePicker jxdpPublicadoCapitulo;
    private javax.swing.JList lsIntegrantesFueraCapitulo;
    private javax.swing.JList lstIntegrantesDentroCapitulo;
    private javax.swing.JTextArea taProyectoCapitulo;
    private javax.swing.JTextField tfAnioCapitulo;
    private javax.swing.JTextField tfBuscarAutorCapitulo;
    private javax.swing.JTextField tfEditorCapitulo;
    private javax.swing.JTextField tfISBNCapitulo;
    private javax.swing.JTextField tfLibro;
    private javax.swing.JTextField tfLugarCapitulo;
    private javax.swing.JTextField tfNombreLibro;
    private javax.swing.JTextField tfcapitulo;
    // End of variables declaration//GEN-END:variables

    private void inicializarComponentes() {
        //formatear jxdpicker
        Comunes.formatearJXdatePicker(jxdpAceptadoCapitulo);
        Comunes.formatearJXdatePicker(jxdpEnviadoCapitulo);
        Comunes.formatearJXdatePicker(jxdpPublicadoCapitulo);
        Comunes.autoAjusteTextArea(taProyectoCapitulo);
        cboEdicionCapitulo.setModel(new javax.swing.DefaultComboBoxModel(TipoEdicion.values()));
        tfLibro.setEditable(false);
        /*
         tfEditorCapitulo.setEditable(false);
         jxdpAceptadoCapitulo.setEditable(false);
         jxdpEnviadoCapitulo.setEditable(false);
         jxdpPublicadoCapitulo.setEditable(false);
         cboEdicionCapitulo.setEditable(false);
         tfISBNCapitulo.setEditable(false);
         tfAnioCapitulo.setEditable(false);
         tfLugarCapitulo.setEditable(false);*/
        switch (tipoOperacion) {
            case "Alta":
                if(proyectoCapitulo != null){
                                    cargarIntegrantesdelProyecto();

                }
                if(proyectoVinculacionCapitulo != null){
                    cargarIntegrantesdelProyectoVinculacion();
                }
                break;
            case "Modificación":
                if (capitulo.getLibro() != null) {
                    tfLibro.setText(capitulo.getLibro().getTitulo());
                    libro = capitulo.getLibro();
                }
                if (capitulo.getNombreLibro() != null) {
                    tfNombreLibro.setText(capitulo.getNombreLibro());
                } else {
                    tfNombreLibro.setText("");
                }
                if (!capitulo.getTitulo().isEmpty()) {
                    tfcapitulo.setText(capitulo.getTitulo());
                } else {
                    tfcapitulo.setText("");
                }
                if (capitulo.getEditor() != null) {
                    tfEditorCapitulo.setText(capitulo.getEditor());
                } else {
                    tfEditorCapitulo.setText(" ");
                }
                if (capitulo.getInvestigadores() != null) {
                    integrantesDentroCapitulo = capitulo.getInvestigadores();
                    Comunes.cargarJList(lstIntegrantesDentroCapitulo, integrantesDentroCapitulo);
                    integrantesFueraCapitulo = InvestigadorFacade.getInstance().getTodosInvestigador();
                    integrantesFueraCapitulo.removeAll(integrantesDentroCapitulo);
                    Comunes.cargarJList(lsIntegrantesFueraCapitulo, integrantesFueraCapitulo);
                }
                try {
                    jxdpEnviadoCapitulo.setDate(capitulo.getFechaEnviado());
                } catch (Exception ex) {
                }
                try {
                    jxdpAceptadoCapitulo.setDate(capitulo.getFechaAceptado());
                } catch (Exception ex) {
                }
                try {
                    jxdpPublicadoCapitulo.setDate(capitulo.getFechaPublicado());
                } catch (Exception ex) {
                }


                cboEdicionCapitulo.setSelectedItem(capitulo.getTipoEdicion());
                if (capitulo.getISBN() != null) {
                    tfISBNCapitulo.setText(capitulo.getISBN());
                } else {
                    tfISBNCapitulo.setText(" ");
                }
                if (capitulo.getAnioPublicacion() != null) {
                    tfAnioCapitulo.setText(capitulo.getAnioPublicacion());
                } else {
                    tfAnioCapitulo.setText(" ");
                }
                if (capitulo.getLugarPublicacion() != null) {
                    tfLugarCapitulo.setText(capitulo.getLugarPublicacion());
                } else {
                    tfLugarCapitulo.setText(" ");
                }
                break;
        }



    }

    public CapituloLibro getCapitulo() {
        return capitulo;
    }

    private void buscarLibro() {
            diagProyectoResultadoBusquedaLibro busquedaLibro = new diagProyectoResultadoBusquedaLibro(null, true);
            busquedaLibro.setLocation(Comunes.centrarDialog(busquedaLibro));
            busquedaLibro.setVisible(true);
            if (busquedaLibro.getLibro() != null) {
                libro = busquedaLibro.getLibro();
                cargarDatosLibro();
            }




    }

    private void cargarIntegrantesdelProyectoVinculacion() {
        List<Investigador> lista = ProyectoVinculacionFacade.getInstance().getTodosIntegrantes(proyectoVinculacionCapitulo);

        for (Object objeto : lista) {
            integrantesDentroCapitulo.add((Investigador) objeto);
        }
        Comunes.cargarJList(lstIntegrantesDentroCapitulo, lista);
        integrantesFueraCapitulo = InvestigadorFacade.getInstance().getTodosInvestigador();
        integrantesFueraCapitulo.removeAll(integrantesDentroCapitulo);
        Comunes.cargarJList(lsIntegrantesFueraCapitulo, integrantesFueraCapitulo);
    }

    private void cargarIntegrantesdelProyecto() {
        List<Investigador> lista = ProyectoFacade.getInstance().getTodosIntegrantes(proyectoCapitulo);

        for (Object objeto : lista) {
            integrantesDentroCapitulo.add((Investigador) objeto);
        }
        Comunes.cargarJList(lstIntegrantesDentroCapitulo, ProyectoFacade.getInstance().getTodosIntegrantes(proyectoCapitulo));
        integrantesFueraCapitulo = InvestigadorFacade.getInstance().getTodosInvestigador();
        integrantesFueraCapitulo.removeAll(integrantesDentroCapitulo);
        Comunes.cargarJList(lsIntegrantesFueraCapitulo, integrantesFueraCapitulo);
    }

    private void agregarAutorCapitulo() {
        if (lsIntegrantesFueraCapitulo.getSelectedIndex() != -1) {

            integrantesDentroCapitulo.add((Investigador) lsIntegrantesFueraCapitulo.getSelectedValue());
            List<Investigador> integrantesFuera = InvestigadorFacade.getInstance().getTodosInvestigador();
            integrantesFuera.removeAll(integrantesDentroCapitulo);
            Comunes.cargarJList(lsIntegrantesFueraCapitulo, integrantesFuera);

            Comunes.cargarJList(lstIntegrantesDentroCapitulo, integrantesDentroCapitulo);

        } else {
            JOptionPane.showMessageDialog(rootPane, "Debe escoger un Autor", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void quitarAutorCapitulo() {
        if (lstIntegrantesDentroCapitulo.getSelectedIndex() != -1) {

            integrantesDentroCapitulo.remove((Investigador) lstIntegrantesDentroCapitulo.getSelectedValue());
            List<Investigador> integrantesFuera = InvestigadorFacade.getInstance().getTodosInvestigador();
            integrantesFuera.removeAll(integrantesDentroCapitulo);
            Comunes.cargarJList(lsIntegrantesFueraCapitulo, integrantesFuera);

            Comunes.cargarJList(lstIntegrantesDentroCapitulo, integrantesDentroCapitulo);

        }
    }

    private void buscarAutorCapitulo() {
        if (!tfBuscarAutorCapitulo.getText().equals("")) {
            Comunes.cargarJList(lsIntegrantesFueraCapitulo, InvestigadorFacade.getInstance().buscarPorApellidoNombre(tfBuscarAutorCapitulo.getText()));
        } else {
            Comunes.cargarJList(lsIntegrantesFueraCapitulo, InvestigadorFacade.getInstance().getTodosInvestigador());
        }

    }

    private void agregarCapitulo() {
        if (validar()) {
            if (tipoOperacion.equals("Alta")) {
                capitulo = new CapituloLibro();
                
                if(proyectoCapitulo != null){
                List<Proyecto> proyectos = new ArrayList<Proyecto>();
                proyectos.add(proyectoCapitulo);
                capitulo.setProyectos(proyectos);
                    
                }
                if(proyectoVinculacionCapitulo != null){
                    
                List<ProyectoVinculacion> proyectosVinculacion = new ArrayList<ProyectoVinculacion>();
                proyectosVinculacion.add(proyectoVinculacionCapitulo);
                capitulo.setProyectosVinculacion(proyectosVinculacion);
                }
                
                if (!tfLibro.getText().isEmpty()) {
                    capitulo.setLibro(libro);
                } else {
                    capitulo.setLibro(null);
                }
                if (!tfNombreLibro.getText().isEmpty()) {
                    capitulo.setNombreLibro(tfNombreLibro.getText());
                } else {
                    capitulo.setNombreLibro("");
                }

                if (!tfcapitulo.getText().isEmpty()) {
                    capitulo.setTitulo(tfcapitulo.getText());
                } else {
                    capitulo.setTitulo(null);
                }
                if (integrantesDentroCapitulo.size() > 0) {
                    capitulo.setInvestigadores(integrantesDentroCapitulo);
                } else {
                    capitulo.setInvestigadores(null);
                }
                if (!tfEditorCapitulo.getText().isEmpty()) {
                    capitulo.setEditor(tfEditorCapitulo.getText());
                } else {
                    capitulo.setEditor(null);
                }
                capitulo.setFechaEnviado(jxdpEnviadoCapitulo.getDate());
                capitulo.setFechaAceptado(jxdpAceptadoCapitulo.getDate());
                capitulo.setFechaPublicado(jxdpPublicadoCapitulo.getDate());
                capitulo.setTipoEdicion((TipoEdicion) cboEdicionCapitulo.getSelectedItem());
                if (!tfISBNCapitulo.getText().isEmpty()) {
                    capitulo.setISBN(tfISBNCapitulo.getText());
                } else {
                    capitulo.setISBN(null);
                }
                if (!tfAnioCapitulo.getText().isEmpty()) {
                    capitulo.setAnioPublicacion(tfAnioCapitulo.getText());
                } else {
                    capitulo.setAnioPublicacion(null);
                }
                if (!tfLugarCapitulo.getText().isEmpty()) {
                    capitulo.setLugarPublicacion(tfLugarCapitulo.getText());
                } else {
                    capitulo.setLugarPublicacion(null);
                }


                PublicacionFacade.getInstance().alta(capitulo);
                Operacion operacion = new Operacion();
                operacion.setUsuario(usuario);
                operacion.setFecha(Comunes.obtenerFechaActualDesdeDB());
                operacion.setOperacion("Alta Capitulo Libro");
                OperacionFacade.getInstance().alta(operacion);
                JOptionPane.showMessageDialog(null, "Capitulo del libro " + capitulo.toString() + "\n, agregado!");
                this.dispose();

            } else if (tipoOperacion.equals("Modificación")) {

                if(proyectoCapitulo != null){
                    
                List<Proyecto> proyectos = new ArrayList<Proyecto>();
                proyectos.add(proyectoCapitulo);
                capitulo.setProyectos(proyectos);
                }
                if(proyectoVinculacionCapitulo != null){
                    
                List<ProyectoVinculacion> proyectosVinculacion = new ArrayList<ProyectoVinculacion>();
                proyectosVinculacion.add(proyectoVinculacionCapitulo);
                capitulo.setProyectosVinculacion(proyectosVinculacion);
                }
                if (!tfLibro.getText().isEmpty()) {
                    capitulo.setLibro(libro);
                } else {
                    capitulo.setLibro(null);
                }
                if (!tfNombreLibro.getText().isEmpty()) {
                    capitulo.setNombreLibro(tfNombreLibro.getText());
                } else {
                    capitulo.setNombreLibro("");
                }


                if (!tfcapitulo.getText().isEmpty()) {
                    capitulo.setTitulo(tfcapitulo.getText());
                } else {
                    capitulo.setTitulo(null);
                }
                if (integrantesDentroCapitulo.size() > 0) {
                    capitulo.setInvestigadores(integrantesDentroCapitulo);
                } else {
                    capitulo.setInvestigadores(null);
                }
                if (!tfEditorCapitulo.getText().isEmpty()) {
                    capitulo.setEditor(tfEditorCapitulo.getText());
                } else {
                    capitulo.setEditor(null);
                }
                capitulo.setFechaEnviado(jxdpEnviadoCapitulo.getDate());
                capitulo.setFechaAceptado(jxdpAceptadoCapitulo.getDate());
                capitulo.setFechaPublicado(jxdpPublicadoCapitulo.getDate());
                capitulo.setTipoEdicion((TipoEdicion) cboEdicionCapitulo.getSelectedItem());
                if (!tfISBNCapitulo.getText().isEmpty()) {
                    capitulo.setISBN(tfISBNCapitulo.getText());
                } else {
                    capitulo.setISBN(null);
                }
                if (!tfAnioCapitulo.getText().isEmpty()) {
                    capitulo.setAnioPublicacion(tfAnioCapitulo.getText());
                } else {
                    capitulo.setAnioPublicacion(null);
                }
                if (!tfLugarCapitulo.getText().isEmpty()) {
                    capitulo.setLugarPublicacion(tfLugarCapitulo.getText());
                } else {
                    capitulo.setLugarPublicacion(null);
                }

                PublicacionFacade.getInstance().modificar(capitulo);
                Operacion operacion = new Operacion();
                operacion.setUsuario(usuario);
                operacion.setFecha(Comunes.obtenerFechaActualDesdeDB());
                operacion.setOperacion("modificación Capitulo Libro");
                OperacionFacade.getInstance().alta(operacion);
                JOptionPane.showMessageDialog(null, "Capitulo " + capitulo.toString() + "\n, "
                        + "del libro Modificado!");
                this.dispose();
            }


        }
    }

    private boolean validar() {
        boolean flag = false;
        if (proyectoCapitulo != null || proyectoVinculacionCapitulo != null) {
            if (!tfNombreLibro.getText().isEmpty()) {
                if (!tfcapitulo.getText().isEmpty()) {
                    if (!integrantesDentroCapitulo.isEmpty()) {
                        flag = true;
                    } else {
                        JOptionPane.showMessageDialog(null, "Debe seleccionar al menos un autor");
                    }

                } else {
                    JOptionPane.showMessageDialog(null, "El Capitulo del libro debe tener un nombre");
                }
            } else {
                JOptionPane.showMessageDialog(null, "El Libro debe tener un Nombre");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Debe seleccionar un proyecto");
        }
        return flag;
    }

    private void cargarDatosLibro() {
        tfLibro.setText(libro.toString());
        tfNombreLibro.setText(libro.toString());
        tfNombreLibro.setEditable(false);
        tfEditorCapitulo.setText(libro.getEditor());
        jxdpEnviadoCapitulo.setDate(libro.getFechaEnviado());
        jxdpAceptadoCapitulo.setDate(libro.getFechaAceptado());
        jxdpPublicadoCapitulo.setDate(libro.getFechaPublicado());
        cboEdicionCapitulo.setSelectedItem(libro.getTipoEdicion());
        tfISBNCapitulo.setText(libro.getISBN());
        tfAnioCapitulo.setText(libro.getAnioPublicacion());
        tfLugarCapitulo.setText(libro.getLugarPublicacion());
    }
}
