/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.editorial.stock;

import entidades.operaciones.Operacion;
import entidades.proyecto.editorial.EditorialCientifica;
import entidades.proyecto.editorial.ExpedienteEditorial;
import entidades.proyecto.editorial.FormatoLibro;
import entidades.proyecto.editorial.Stock;
import entidades.usuario.Usuario;
import facade.OperacionFacade;
import facade.editorial.FormatoFacade;
import facade.editorial.StockFacade;
import includes.Comunes;
import javax.swing.JOptionPane;
import vista.editorial.diagBuscarEditorial;

/**
 *
 * @author Francisco
 */
public class diagStock extends javax.swing.JDialog {

    private Usuario usuario;
    private String tipoOperacion;
    private Stock stock;
    private String origen;
    private EditorialCientifica editorial;

    /**
     * Creates new form diagStock
     */
    public diagStock(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    // Entra por aca cuando viene de editorial y se esta creando por primera vez.
    public diagStock(java.awt.Frame parent, boolean modal,
            Usuario usuario, String tipoOperacion, String origen) {
        super(parent, modal);
        initComponents();
        this.usuario = usuario;
        this.tipoOperacion = tipoOperacion;
        this.origen = origen;
        inicializarComponentes();

    }

    public diagStock(java.awt.Frame parent, boolean modal,
            Usuario usuario, String tipoOperacion, String origen,
            EditorialCientifica editorial) {
        super(parent, modal);
        initComponents();
        this.usuario = usuario;
        this.tipoOperacion = tipoOperacion;
        this.origen = origen;
        
        this.editorial = editorial;
        inicializarComponentes();
    }

    public diagStock(java.awt.Frame parent, boolean modal,
            Stock stock, Usuario usuario, String tipoOperacion) {
        super(parent, modal);
        initComponents();
        this.usuario = usuario;
        this.stock = stock;
        this.tipoOperacion = tipoOperacion;
        inicializarComponentes();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tfCodigo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tfPublicacion = new javax.swing.JTextField();
        btnCancelar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        cboFormato = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jButtonPublicacionBuscar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(diagStock.class, "diagStock.jPanel1.border.title"))); // NOI18N

        jLabel2.setText(org.openide.util.NbBundle.getMessage(diagStock.class, "diagStock.jLabel2.text")); // NOI18N

        jLabel4.setText(org.openide.util.NbBundle.getMessage(diagStock.class, "diagStock.jLabel4.text")); // NOI18N

        tfCodigo.setText(org.openide.util.NbBundle.getMessage(diagStock.class, "diagStock.tfCodigo.text")); // NOI18N
        tfCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfCodigoKeyTyped(evt);
            }
        });

        jLabel5.setText(org.openide.util.NbBundle.getMessage(diagStock.class, "diagStock.jLabel5.text")); // NOI18N

        tfPublicacion.setText(org.openide.util.NbBundle.getMessage(diagStock.class, "diagStock.tfPublicacion.text")); // NOI18N

        btnCancelar.setText(org.openide.util.NbBundle.getMessage(diagStock.class, "diagStock.btnCancelar.text")); // NOI18N

        jButton2.setText(org.openide.util.NbBundle.getMessage(diagStock.class, "diagStock.jButton2.text")); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setText(org.openide.util.NbBundle.getMessage(diagStock.class, "diagStock.jButton1.text")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButtonPublicacionBuscar.setText(org.openide.util.NbBundle.getMessage(diagStock.class, "diagStock.jButtonPublicacionBuscar.text")); // NOI18N
        jButtonPublicacionBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPublicacionBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfCodigo, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                            .addComponent(tfPublicacion)
                            .addComponent(cboFormato, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonPublicacionBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(btnCancelar)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)))
                .addContainerGap(108, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cboFormato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tfPublicacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonPublicacionBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(jButton2))
                .addGap(35, 35, 35))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfCodigoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfCodigoKeyTyped
        // escribir solo numeros
        //char caracter = evt.getKeyChar();
        // Verificar si la tecla pulsada no es un digito
        //if(((caracter < '0') || (caracter > '9')) && (caracter != '\b' /*corresponde a BACK_SPACE*/)) {
        //    evt.consume();  // ignorar el evento de teclado
        //}
        Comunes.soloNumeros(tfCodigo, evt);
    }//GEN-LAST:event_tfCodigoKeyTyped

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        guardar();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        nuevoFormato();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonPublicacionBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPublicacionBuscarActionPerformed
        buscarPublicacion();        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonPublicacionBuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(diagStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(diagStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(diagStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(diagStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                diagStock dialog = new diagStock(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JComboBox cboFormato;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonPublicacionBuscar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField tfCodigo;
    private javax.swing.JTextField tfPublicacion;
    // End of variables declaration//GEN-END:variables
 private void inicializarComponentes() {
        cargarFormatos();
        switch (tipoOperacion) {
            case "Alta":
                if (origen.equals("Editorial")){
                        jButtonPublicacionBuscar.setEnabled(false);
                }
                
                if (editorial != null) {
                    System.out.println("Editorial != null");
                    System.out.println(editorial.toString());
                    tfPublicacion.setText(editorial.toString());

                }
                                tfPublicacion.setEnabled(false);

            case "Modificación":

                try {

                    if (stock.getPublicacion().getTitulo() != null) {
                        tfPublicacion.setText(stock.getPublicacion().getTitulo());

                    }
                } catch (NullPointerException ex) {
                }
                try {
                    if (stock.getCodigo() != null) {
                        tfCodigo.setText(stock.getCodigo());

                    }
                } catch (NullPointerException ex) {
                }
                try {
                    if (stock.getFormato() != null) {
                        cboFormato.setSelectedItem(stock.getFormato());

                    }
                } catch (NullPointerException ex) {
                }
        }

    }

    public void guardar() {
        if (validar()) {
            switch (tipoOperacion) {
                case "Alta":
                    stock = new Stock();
                    asignarDatos();
                    if(editorial != null){
                        altaStock();
                    }
                    this.dispose();
                case "Modificación":
                    asignarDatos();
                    modificarStock();
                    this.dispose();
            }
        }
    }
private void altaStock() {
            try {
                
                StockFacade.getInstance().alta(stock);
                Operacion operacion = new Operacion();
                operacion.setFecha(Comunes.obtenerFechaActualDesdeDB());
                operacion.setOperacion("Alta de stock de publicación científica");
                operacion.setUsuario(usuario);
                OperacionFacade.getInstance().alta(operacion);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Error creando stock de publicación científica\n " + ex);
            }
        }
    
    public Stock getStockCreado() {
        return stock;
    }

    private boolean validar() {
        boolean flag = false;
        if (!tfCodigo.getText().equals("")) {
            if (cboFormato.getSelectedIndex() != -1) {

                flag = true;
            } else {
                JOptionPane.showMessageDialog(null, "Debe ingresar el formato.", "Error", JOptionPane.ERROR_MESSAGE);
                tfCodigo.requestFocus();
            }

        } else {
            JOptionPane.showMessageDialog(null, "Debe ingresar el código.", "Error", JOptionPane.ERROR_MESSAGE);
            cboFormato.requestFocus();
        }

        return flag;
    }

    private void asignarDatos() {
        stock.setCodigo(tfCodigo.getText());
        stock.setFormato((FormatoLibro) cboFormato.getSelectedItem());
        if(editorial == null){
            stock.setPublicacion(null);

        } else{
            stock.setPublicacion(editorial);
        }
    }

    private void modificarStock() {
// try {
//                StockEditorialFacade.getInstance().modificar(stock);
//                Operacion operacion = new Operacion();
//                operacion.setFecha(Comunes.obtenerFechaActualDesdeDB());
//                operacion.setOperacion("Modificación de expediente");
//                operacion.setUsuario(usuario);
//                OperacionFacade.getInstance().alta(operacion);
//
//            } catch (Exception ex) {
//                JOptionPane.showMessageDialog(this, "Error modificando expediente\n " + ex);
//            }   
    }

    private void cargarFormatos() {
        Comunes.cargarJCombo(cboFormato, FormatoFacade.getInstance().listarTodos());

    }

    private void nuevoFormato() {

        diagFormato formato = new diagFormato(null, true, usuario);
        formato.setVisible(true);
        formato.setLocation(Comunes.centrarDialog(formato));
        cargarFormatos();
    }
    private void buscarPublicacion(){
        diagBuscarEditorial diageditorial = new diagBuscarEditorial(null, true);
        diageditorial.setVisible(true);
        diageditorial.setLocation(Comunes.centrarDialog(diageditorial));
        if (diageditorial.getEditorial() != null){
            editorial = diageditorial.getEditorial();
            tfPublicacion.setText(diageditorial.getEditorial().toString());
        }
    }
}
