/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.proyectos.vinculacion.seguimiento;

import entidades.operaciones.Operacion;
import entidades.proyecto.vinculacion.NotaExterna;
import java.awt.Dimension;
import java.awt.Toolkit;
import entidades.usuario.Usuario;
import facade.OperacionFacade;
import includes.Comunes;

import facade.proyecto.vinculacion.NotaExternaFacade;
import javax.swing.JOptionPane;
import org.apache.commons.validator.routines.FloatValidator;
import org.apache.commons.validator.routines.LongValidator;

/**
 *
 * @author Panchi
 */
public class diagNotaExterna extends javax.swing.JDialog {
    private NotaExterna notaExterna;
    private Usuario usuario;
    private String tipoOperacion;
    /**
     * Creates new form diagNotaExterna
     */
    public diagNotaExterna(java.awt.Frame parent, boolean modal,  String tipoOperacion,
                 Usuario usuario) {
        super(parent, modal);
        this.usuario = usuario;
        this.tipoOperacion = tipoOperacion;
        initComponents();
        
        inicializarComponentes();
    }
    public diagNotaExterna(java.awt.Frame parent, boolean modal,  String tipoOperacion,
                 Usuario usuario, NotaExterna notaExterna) {
        super(parent, modal);
        this.usuario = usuario;
        this.notaExterna = notaExterna;
        this.tipoOperacion = tipoOperacion;
        initComponents();
        
        inicializarComponentes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtfNroNota = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtaMotivo = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        dateMesaEntrada = new org.jdesktop.swingx.JXDatePicker();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        dateAprobacion = new org.jdesktop.swingx.JXDatePicker();
        dateDesembolso = new org.jdesktop.swingx.JXDatePicker();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        dateFecha = new org.jdesktop.swingx.JXDatePicker();
        chkFechaDesembolso = new javax.swing.JCheckBox();
        chkFechaAprobacion = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(diagNotaExterna.class, "diagNotaExterna.jPanel1.border.title"))); // NOI18N

        jLabel1.setText(org.openide.util.NbBundle.getMessage(diagNotaExterna.class, "diagNotaExterna.jLabel1.text")); // NOI18N

        jLabel2.setText(org.openide.util.NbBundle.getMessage(diagNotaExterna.class, "diagNotaExterna.jLabel2.text")); // NOI18N

        jLabel3.setText(org.openide.util.NbBundle.getMessage(diagNotaExterna.class, "diagNotaExterna.jLabel3.text")); // NOI18N

        jtfNroNota.setText(org.openide.util.NbBundle.getMessage(diagNotaExterna.class, "diagNotaExterna.jtfNroNota.text")); // NOI18N
        jtfNroNota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfNroNotaActionPerformed(evt);
            }
        });

        jtaMotivo.setColumns(20);
        jtaMotivo.setLineWrap(true);
        jtaMotivo.setRows(5);
        jScrollPane1.setViewportView(jtaMotivo);

        jLabel4.setText(org.openide.util.NbBundle.getMessage(diagNotaExterna.class, "diagNotaExterna.jLabel4.text")); // NOI18N

        dateMesaEntrada.setFormats("dd/MM/yyyy");

        jLabel5.setText(org.openide.util.NbBundle.getMessage(diagNotaExterna.class, "diagNotaExterna.jLabel5.text")); // NOI18N

        jLabel6.setText(org.openide.util.NbBundle.getMessage(diagNotaExterna.class, "diagNotaExterna.jLabel6.text")); // NOI18N

        dateAprobacion.setFormats("dd/MM/yyyy");

        dateDesembolso.setFormats("dd/MM/yyyy");

        jButton1.setText(org.openide.util.NbBundle.getMessage(diagNotaExterna.class, "diagNotaExterna.jButton1.text")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText(org.openide.util.NbBundle.getMessage(diagNotaExterna.class, "diagNotaExterna.jButton2.text")); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        dateFecha.setFormats("dd/MM/yyyy");

        chkFechaDesembolso.setText(org.openide.util.NbBundle.getMessage(diagNotaExterna.class, "diagNotaExterna.chkFechaDesembolso.text")); // NOI18N
        chkFechaDesembolso.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                chkFechaDesembolsoStateChanged(evt);
            }
        });
        chkFechaDesembolso.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chkFechaDesembolsoItemStateChanged(evt);
            }
        });

        chkFechaAprobacion.setText(org.openide.util.NbBundle.getMessage(diagNotaExterna.class, "diagNotaExterna.chkFechaAprobacion.text")); // NOI18N
        chkFechaAprobacion.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                chkFechaAprobacionStateChanged(evt);
            }
        });
        chkFechaAprobacion.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chkFechaAprobacionItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                        .addComponent(dateDesembolso, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jButton1)
                                .addComponent(jLabel4))
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(dateMesaEntrada, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                                    .addComponent(dateAprobacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtfNroNota)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                            .addComponent(dateFecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chkFechaDesembolso)
                    .addComponent(chkFechaAprobacion, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(dateFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtfNroNota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(dateMesaEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(dateAprobacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkFechaAprobacion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(dateDesembolso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkFechaDesembolso))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfNroNotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfNroNotaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfNroNotaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        guardar();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void chkFechaDesembolsoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_chkFechaDesembolsoStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_chkFechaDesembolsoStateChanged

    private void chkFechaDesembolsoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chkFechaDesembolsoItemStateChanged
        modificarEstadoDateFechaDesembolso();        // TODO add your handling code here:
    }//GEN-LAST:event_chkFechaDesembolsoItemStateChanged

    private void chkFechaAprobacionStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_chkFechaAprobacionStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_chkFechaAprobacionStateChanged

    private void chkFechaAprobacionItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chkFechaAprobacionItemStateChanged
        modificarEstadoDateFechaAprobacion();   
    }//GEN-LAST:event_chkFechaAprobacionItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(diagNotaExterna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(diagNotaExterna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(diagNotaExterna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(diagNotaExterna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the dialog
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                diagNotaExterna dialog = new diagNotaExterna(new javax.swing.JFrame(), true, new String(), new Usuario());
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox chkFechaAprobacion;
    private javax.swing.JCheckBox chkFechaDesembolso;
    private org.jdesktop.swingx.JXDatePicker dateAprobacion;
    private org.jdesktop.swingx.JXDatePicker dateDesembolso;
    private org.jdesktop.swingx.JXDatePicker dateFecha;
    private org.jdesktop.swingx.JXDatePicker dateMesaEntrada;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jtaMotivo;
    private javax.swing.JTextField jtfNroNota;
    // End of variables declaration//GEN-END:variables

     private void inicializarComponentes() {
        
        switch (tipoOperacion) {
            case "Alta":
                break;
            case "Modificación":
                try {
                    if (notaExterna.getFecha() != null) {
                        dateFecha.setDate(notaExterna.getFecha());

                    }
                } catch (NullPointerException ex) {
                }
                try {
                    if (notaExterna.getNroNota() != null) {
                        jtfNroNota.setText(notaExterna.getNroNota());

                    }
                } catch (NullPointerException ex) {
                }
                
                try {
                    if (notaExterna.getMotivo() != null) {
                        jtaMotivo.setText(notaExterna.getMotivo());

                    }
                } catch (NullPointerException ex) {
                }
                
                try {
                    if (notaExterna.getFechaDeRecibidoMesaDeEntrada() != null) {
                        dateMesaEntrada.setDate(notaExterna.getFechaDeRecibidoMesaDeEntrada());

                    }
                } catch (NullPointerException ex) {
                }
                
                try {
                    if (notaExterna.getFechaAprobacion() != null) {
                        dateAprobacion.setDate(notaExterna.getFechaAprobacion());

                    } else{
                    
                        dateAprobacion.setEnabled(false);
                        chkFechaAprobacion.setSelected(true);
                }
                } catch (NullPointerException ex) {
                }
                
                try {
                    if (notaExterna.getFechaDesembolso() != null) {
                        dateDesembolso.setDate(notaExterna.getFechaDesembolso());

                    }
                    else{
                        dateDesembolso.setEnabled(false);
                        chkFechaDesembolso.setSelected(true);
                    }
                } catch (NullPointerException ex) {
                }
}
     }

    private void altaNota() {
        try {
            NotaExternaFacade.getInstance().alta(notaExterna);
            Operacion operacion = new Operacion();
            operacion.setFecha(Comunes.obtenerFechaActualDesdeDB());
            operacion.setOperacion("Alta de nota externa");
            operacion.setUsuario(usuario);
            OperacionFacade.getInstance().alta(operacion);

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error creando nota externa\n " + ex);
        }
    }

    private void modificarNota() {
        try {
            NotaExternaFacade.getInstance().modificar(notaExterna);
            Operacion operacion = new Operacion();
            operacion.setFecha(Comunes.obtenerFechaActualDesdeDB());
            operacion.setOperacion("Modificación de nota externa");
            operacion.setUsuario(usuario);
            OperacionFacade.getInstance().alta(operacion);

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error modificando nota externa\n " + ex);
        }
    }

    private void asignarDatos(){
         notaExterna.setFecha(dateFecha.getDate());
                notaExterna.setNroNota(jtfNroNota.getText());
                notaExterna.setMotivo(jtaMotivo.getText());
                notaExterna.setFechaDeRecibidoMesaDeEntrada(dateMesaEntrada.getDate());
                if(dateAprobacion.isEnabled()){
                   notaExterna.setFechaAprobacion(dateAprobacion.getDate());

                }
                else{
                    notaExterna.setFechaAprobacion(null);
                }
                if(dateDesembolso.isEnabled()){
                   notaExterna.setFechaDesembolso(dateDesembolso.getDate());

                }
                else{
                    notaExterna.setFechaDesembolso(null);
                }
    }
    private void guardar() {
        if (validar()) {
            switch (tipoOperacion) {
                case "Alta":
                    notaExterna = new NotaExterna();
                    asignarDatos();
                    altaNota();
                    this.dispose();
                    break;
                case "Modificación":
                    asignarDatos();
                    modificarNota();
                    this.dispose();
                    break;
            }
        }
    }
    private boolean validar() {
            boolean flag = false;
        if (!jtfNroNota.getText().isEmpty() ) {
            if (!jtaMotivo.getText().isEmpty()) {
                if(jtaMotivo.getText().length()<250){
                    flag = true;
                }else{
                    JOptionPane.showMessageDialog(null, "Texto demasiado largo",
                        "Error", JOptionPane.ERROR_MESSAGE);
                }

            } else {
                JOptionPane.showMessageDialog(null, "Motivo incorrecto",
                        "Error", JOptionPane.ERROR_MESSAGE);
            }

        } else {
            JOptionPane.showMessageDialog(null, "Número de nota incorrecto",
                    "Error", JOptionPane.ERROR_MESSAGE);
        }

        return flag;

        
    }
    public NotaExterna getNotaExternaCreada(){
        return notaExterna;
    }

    private void modificarEstadoDateFechaDesembolso() {
    if (chkFechaDesembolso.isSelected()) {
            dateDesembolso.setEnabled(false);
        } else {
            dateDesembolso.setEnabled(true);
        }    
    
    }

    private void modificarEstadoDateFechaAprobacion() {
    if (chkFechaAprobacion.isSelected()) {
            dateAprobacion.setEnabled(false);
        } else {
            dateAprobacion.setEnabled(true);
        }    
    
    }
}
