/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.proyectos.vinculacion.seguimiento;

import entidades.proyecto.vinculacion.NotaInterna;
import javax.swing.JOptionPane;
import org.apache.commons.validator.routines.LongValidator;
import entidades.operaciones.Operacion;
import java.awt.Dimension;
import java.awt.Toolkit;
import entidades.usuario.Usuario;
import facade.OperacionFacade;
import facade.proyecto.vinculacion.NotaInternaFacade;
import includes.Comunes;
/**
 *
 * @author Panchi
 */
public class diagNotaInterna extends javax.swing.JDialog {
    private NotaInterna notaInterna;
   private Usuario usuario;
    private String tipoOperacion;
    /**
     * Creates new form diagNotaInterna
   */
    public diagNotaInterna(java.awt.Frame parent, boolean modal,  String tipoOperacion,
                 Usuario usuario) {
        super(parent, modal);
        this.usuario = usuario;
        this.tipoOperacion = tipoOperacion;
        initComponents();
        
        inicializarComponentes();
    }
    public diagNotaInterna(java.awt.Frame parent, boolean modal,  String tipoOperacion,
                 Usuario usuario, NotaInterna notaInterna) {
        super(parent, modal);
        this.usuario = usuario;
        this.notaInterna = notaInterna;
        this.tipoOperacion = tipoOperacion;
        initComponents();
        
        inicializarComponentes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        dateFecha = new org.jdesktop.swingx.JXDatePicker();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtfNroNota = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtaMotivo = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        dateMesaEntrada = new org.jdesktop.swingx.JXDatePicker();
        jLabel6 = new javax.swing.JLabel();
        dateDesembolso = new org.jdesktop.swingx.JXDatePicker();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        chkFechaDesembolso = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(diagNotaInterna.class, "diagNotaInterna.jPanel1.border.title"))); // NOI18N

        dateFecha.setFormats("dd/MM/yyyy");

        jLabel1.setText(org.openide.util.NbBundle.getMessage(diagNotaInterna.class, "diagNotaInterna.jLabel1.text")); // NOI18N

        jLabel2.setText(org.openide.util.NbBundle.getMessage(diagNotaInterna.class, "diagNotaInterna.jLabel2.text")); // NOI18N

        jLabel3.setText(org.openide.util.NbBundle.getMessage(diagNotaInterna.class, "diagNotaInterna.jLabel3.text")); // NOI18N

        jtfNroNota.setText(org.openide.util.NbBundle.getMessage(diagNotaInterna.class, "diagNotaInterna.jtfNroNota.text")); // NOI18N
        jtfNroNota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfNroNotaActionPerformed(evt);
            }
        });

        jtaMotivo.setColumns(20);
        jtaMotivo.setLineWrap(true);
        jtaMotivo.setRows(5);
        jScrollPane1.setViewportView(jtaMotivo);

        jLabel4.setText(org.openide.util.NbBundle.getMessage(diagNotaInterna.class, "diagNotaInterna.jLabel4.text")); // NOI18N

        dateMesaEntrada.setFormats("dd/MM/yyyy");

        jLabel6.setText(org.openide.util.NbBundle.getMessage(diagNotaInterna.class, "diagNotaInterna.jLabel6.text")); // NOI18N

        dateDesembolso.setFormats("dd/MM/yyyy");

        jButton1.setText(org.openide.util.NbBundle.getMessage(diagNotaInterna.class, "diagNotaInterna.jButton1.text")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText(org.openide.util.NbBundle.getMessage(diagNotaInterna.class, "diagNotaInterna.jButton2.text")); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        chkFechaDesembolso.setText(org.openide.util.NbBundle.getMessage(diagNotaInterna.class, "diagNotaInterna.chkFechaDesembolso.text")); // NOI18N
        chkFechaDesembolso.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chkFechaDesembolsoItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtfNroNota)
                            .addComponent(dateFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jButton1)
                                .addComponent(jLabel4))
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dateDesembolso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(dateMesaEntrada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkFechaDesembolso)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dateFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtfNroNota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(dateMesaEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(dateDesembolso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkFechaDesembolso))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfNroNotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfNroNotaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfNroNotaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        guardar();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void chkFechaDesembolsoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chkFechaDesembolsoItemStateChanged
        modificarEstadoDateFechaDesembolso();            // TODO add your handling code here:
    }//GEN-LAST:event_chkFechaDesembolsoItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(diagNotaInterna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(diagNotaInterna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(diagNotaInterna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(diagNotaInterna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the dialog
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                diagNotaInterna dialog = new diagNotaInterna(new javax.swing.JFrame(), true, new String(), new Usuario());
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox chkFechaDesembolso;
    private org.jdesktop.swingx.JXDatePicker dateDesembolso;
    private org.jdesktop.swingx.JXDatePicker dateFecha;
    private org.jdesktop.swingx.JXDatePicker dateMesaEntrada;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jtaMotivo;
    private javax.swing.JTextField jtfNroNota;
    // End of variables declaration//GEN-END:variables
  private void inicializarComponentes() {
        
        switch (tipoOperacion) {
            case "Alta":
                break;
            case "Modificación":
                try {
                    if (notaInterna.getFecha() != null) {
                        dateFecha.setDate(notaInterna.getFecha());

                    }
                } catch (NullPointerException ex) {
                }
                try {
                    if (notaInterna.getNroNota() != null) {
                        jtfNroNota.setText(notaInterna.getNroNota());

                    }
                } catch (NullPointerException ex) {
                }
                
                try {
                    if (notaInterna.getMotivo() != null) {
                        jtaMotivo.setText(notaInterna.getMotivo());

                    }
                } catch (NullPointerException ex) {
                }
                
                try {
                    if (notaInterna.getFechaDeRecibidoMesaDeEntrada() != null) {
                        dateMesaEntrada.setDate(notaInterna.getFechaDeRecibidoMesaDeEntrada());

                    }
                } catch (NullPointerException ex) {
                }
                
                try {
                    if (notaInterna.getFechaDesembolso() != null) {
                        dateDesembolso.setDate(notaInterna.getFechaDesembolso());

                    }else{
                        dateDesembolso.setEnabled(false);
                        chkFechaDesembolso.setSelected(true);
                    }
                } catch (NullPointerException ex) {
                }
}
     }
  
      private void altaNota() {
        try {
            NotaInternaFacade.getInstance().alta(notaInterna);
            Operacion operacion = new Operacion();
            operacion.setFecha(Comunes.obtenerFechaActualDesdeDB());
            operacion.setOperacion("Alta de nota interna");
            operacion.setUsuario(usuario);
            OperacionFacade.getInstance().alta(operacion);

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error creando nota interna\n " + ex);
        }
    }

    private void modificarNota() {
        try {
            NotaInternaFacade.getInstance().modificar(notaInterna);
            Operacion operacion = new Operacion();
            operacion.setFecha(Comunes.obtenerFechaActualDesdeDB());
            operacion.setOperacion("Modificación de nota interna");
            operacion.setUsuario(usuario);
            OperacionFacade.getInstance().alta(operacion);

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error modificando nota interna\n " + ex);
        }
    }

    private void asignarDatos(){
         notaInterna.setFecha(dateFecha.getDate());
                notaInterna.setNroNota(jtfNroNota.getText());
                notaInterna.setMotivo(jtaMotivo.getText());
                notaInterna.setFechaDeRecibidoMesaDeEntrada(dateMesaEntrada.getDate());
                if(dateDesembolso.isEnabled()){
                notaInterna.setFechaDesembolso(dateDesembolso.getDate());

                }
                else{
                    notaInterna.setFechaDesembolso(null);
                }
    }
    private void guardar() {
        if (validar()) {
            if (tipoOperacion.equals("Alta")) {
                notaInterna = new NotaInterna();
                asignarDatos();
                altaNota();
                this.dispose();
            } else if (tipoOperacion.equals("Modificación")) {

                asignarDatos();
                modificarNota();
                this.dispose();

            }
        }
    }
    private boolean validar() {
         boolean flag = false;
        if (!jtfNroNota.getText().isEmpty() ) {
            if (!jtaMotivo.getText().isEmpty()) {
                if(jtaMotivo.getText().length()<250){

                flag = true;

                }else{
                    JOptionPane.showMessageDialog(null, "Texto demasiado largo",
                        "Error", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(null, "Motivo incorrecto",
                        "Error", JOptionPane.ERROR_MESSAGE);
            }

        } else {
            JOptionPane.showMessageDialog(null, "Número de nota incorrecto",
                    "Error", JOptionPane.ERROR_MESSAGE);
        }

        return flag;
        
    }
    public NotaInterna getNotaInternaCreada(){
        return notaInterna;
    }

    private void modificarEstadoDateFechaDesembolso() {
    if (chkFechaDesembolso.isSelected()) {
            dateDesembolso.setEnabled(false);
        } else {
            dateDesembolso.setEnabled(true);
        }    
    
    }

}
