/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.editorial;

import entidades.operaciones.Operacion;
import entidades.persona.investigador.Investigador;
import entidades.proyecto.Evaluacion;
import entidades.proyecto.Proyecto;
import entidades.proyecto.editorial.EditorialCientifica;
import entidades.proyecto.editorial.EvaluacionEditorial;
import entidades.proyecto.editorial.ExpedienteEditorial;
import entidades.proyecto.editorial.Stock;
import entidades.proyecto.editorial.TipoPublicacion;
import entidades.usuario.Usuario;
import facade.EditorialCientificaFacade;
import facade.EvaluacionEditorialFacade;
import facade.EvaluacionFacade;
import facade.InvestigadorFacade;
import facade.OperacionFacade;
import facade.ProyectoVinculacionFacade;
import facade.editorial.StockFacade;
import facade.editorial.TipoPublicacionFacade;
import includes.Comunes;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Date;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import vista.diagProyectoBusquedaSimple;
import vista.editorial.evaluaciones.diagEvaluacionEditorial;
import vista.editorial.stock.diagStock;
import vista.proyectos.resultado.diagProyectoResultado;
import vistas.evaluaciones.diagEvaluacion;

/**
 *
 * @author francisco
 */
public class diagEditorial extends javax.swing.JDialog {

    private List<EvaluacionEditorial> evaluaciones = new ArrayList<EvaluacionEditorial>();
    private List<Investigador> integrantesDentroLibro = new ArrayList<Investigador>();  
    private String tipoOperacion;
    private Usuario usuario;
    private EditorialCientifica editorialCientifica;
    private Proyecto proyecto;
    private Proyecto proyectoSele;
    private ExpedienteEditorial expedienteEditorial;
    private EvaluacionEditorial evaluacionEditorial;
    private List<Stock> listaUnidades = new ArrayList<Stock>();
    private List<String> palabrasClaves = new ArrayList<String>();
    private List<String> keyWords = new ArrayList<String>();

    /**
     * Creates new form diagEditorial
     */
    public diagEditorial(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public diagEditorial(java.awt.Frame parent, boolean modal, String tipoOperacion, Usuario usuario) {
        super(parent, modal);
        this.tipoOperacion = tipoOperacion;
        this.usuario = usuario;
        //modeloTabla = new DefaultTableModel();
        initComponents();
        inicializarComponentes();

    }

    public diagEditorial(java.awt.Frame parent, boolean modal,
            String tipoOperacion, EditorialCientifica editorialCientifica, Usuario usuario) {
        super(parent, modal);
        this.tipoOperacion = tipoOperacion;
        this.editorialCientifica = editorialCientifica;
        // modeloTabla = new DefaultTableModel();
        this.usuario = usuario;
        listaUnidades = StockFacade.getInstance().getPorPublicacionId(editorialCientifica.getId());
        evaluaciones = editorialCientifica.getEvaluacionesEditorial();
        initComponents();
        inicializarComponentes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtfTitulo = new javax.swing.JTextArea();
        jtfIsbn = new javax.swing.JTextField();
        jcbTipoPublicacion = new javax.swing.JComboBox();
        jtfProyectoRelacionado = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtaMenciones = new javax.swing.JTextArea();
        jxDatePub = new org.jdesktop.swingx.JXDatePicker();
        jButton4 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        btnPublicaciones = new javax.swing.JButton();
        jPanelAsesores = new javax.swing.JPanel();
        jScrollPane10 = new javax.swing.JScrollPane();
        lstIntegrantesDentroLibro = new javax.swing.JList();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jScrollPane11 = new javax.swing.JScrollPane();
        lsIntegrantesFueraLibro = new javax.swing.JList();
        jLabel3 = new javax.swing.JLabel();
        tfBuscarIntregantesLibro = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jListEvaluaciones = new javax.swing.JList();
        jLabel10 = new javax.swing.JLabel();
        btAgregarEvaluacion = new javax.swing.JButton();
        btnEditarEvaluacion = new javax.swing.JButton();
        btnEliminarEvaluacion = new javax.swing.JButton();
        btVerDetallesEvaluacionSeleccionada = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jListUnidades = new javax.swing.JList();
        btAgregarEvaluacion1 = new javax.swing.JButton();
        btnEliminarEvaluacion1 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        taResumen = new javax.swing.JTextArea();
        jScrollPane8 = new javax.swing.JScrollPane();
        taSummary = new javax.swing.JTextArea();
        jLabel12 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButton2.setText(org.openide.util.NbBundle.getMessage(diagEditorial.class, "diagEditorial.jButton2.text")); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(diagEditorial.class, "diagEditorial.jPanel1.border.title"))); // NOI18N

        jLabel1.setText(org.openide.util.NbBundle.getMessage(diagEditorial.class, "diagEditorial.jLabel1.text")); // NOI18N

        jLabel4.setText(org.openide.util.NbBundle.getMessage(diagEditorial.class, "diagEditorial.jLabel4.text")); // NOI18N

        jLabel5.setText(org.openide.util.NbBundle.getMessage(diagEditorial.class, "diagEditorial.jLabel5.text")); // NOI18N

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText(org.openide.util.NbBundle.getMessage(diagEditorial.class, "diagEditorial.jLabel7.text")); // NOI18N
        jLabel7.setToolTipText(org.openide.util.NbBundle.getMessage(diagEditorial.class, "diagEditorial.jLabel7.toolTipText")); // NOI18N
        jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jLabel7.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        jLabel8.setText(org.openide.util.NbBundle.getMessage(diagEditorial.class, "diagEditorial.jLabel8.text")); // NOI18N

        jLabel9.setText(org.openide.util.NbBundle.getMessage(diagEditorial.class, "diagEditorial.jLabel9.text")); // NOI18N

        jtfTitulo.setColumns(20);
        jtfTitulo.setRows(5);
        jScrollPane2.setViewportView(jtfTitulo);

        jtfIsbn.setText(org.openide.util.NbBundle.getMessage(diagEditorial.class, "diagEditorial.jtfIsbn.text")); // NOI18N

        jcbTipoPublicacion.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jtfProyectoRelacionado.setText(org.openide.util.NbBundle.getMessage(diagEditorial.class, "diagEditorial.jtfProyectoRelacionado.text")); // NOI18N
        jtfProyectoRelacionado.setEnabled(false);

        jtaMenciones.setColumns(20);
        jtaMenciones.setRows(5);
        jScrollPane3.setViewportView(jtaMenciones);

        jButton4.setText(org.openide.util.NbBundle.getMessage(diagEditorial.class, "diagEditorial.jButton4.text")); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton1.setText(org.openide.util.NbBundle.getMessage(diagEditorial.class, "diagEditorial.jButton1.text")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnPublicaciones.setText(org.openide.util.NbBundle.getMessage(diagEditorial.class, "diagEditorial.btnPublicaciones.text")); // NOI18N
        btnPublicaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPublicacionesActionPerformed(evt);
            }
        });

        jPanelAsesores.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), org.openide.util.NbBundle.getMessage(diagEditorial.class, "diagEditorial.jPanelAsesores.border.title"))); // NOI18N

        jScrollPane10.setViewportView(lstIntegrantesDentroLibro);

        jButton8.setText(org.openide.util.NbBundle.getMessage(diagEditorial.class, "diagEditorial.jButton8.text")); // NOI18N
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setText(org.openide.util.NbBundle.getMessage(diagEditorial.class, "diagEditorial.jButton9.text")); // NOI18N
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jScrollPane11.setViewportView(lsIntegrantesFueraLibro);

        jLabel3.setText(org.openide.util.NbBundle.getMessage(diagEditorial.class, "diagEditorial.jLabel3.text")); // NOI18N

        tfBuscarIntregantesLibro.setText(org.openide.util.NbBundle.getMessage(diagEditorial.class, "diagEditorial.tfBuscarIntregantesLibro.text")); // NOI18N
        tfBuscarIntregantesLibro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfBuscarIntregantesLibroKeyPressed(evt);
            }
        });

        jLabel2.setText(org.openide.util.NbBundle.getMessage(diagEditorial.class, "diagEditorial.jLabel2.text")); // NOI18N

        jLabel6.setText(org.openide.util.NbBundle.getMessage(diagEditorial.class, "diagEditorial.jLabel6.text")); // NOI18N

        javax.swing.GroupLayout jPanelAsesoresLayout = new javax.swing.GroupLayout(jPanelAsesores);
        jPanelAsesores.setLayout(jPanelAsesoresLayout);
        jPanelAsesoresLayout.setHorizontalGroup(
            jPanelAsesoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAsesoresLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelAsesoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelAsesoresLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(352, 352, 352)
                        .addComponent(jLabel6)
                        .addGap(252, 252, 252))
                    .addGroup(jPanelAsesoresLayout.createSequentialGroup()
                        .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanelAsesoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAsesoresLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAsesoresLayout.createSequentialGroup()
                                .addGroup(jPanelAsesoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(52, 52, 52)))
                        .addGroup(jPanelAsesoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfBuscarIntregantesLibro)
                            .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(55, 55, 55))))
        );
        jPanelAsesoresLayout.setVerticalGroup(
            jPanelAsesoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAsesoresLayout.createSequentialGroup()
                .addGroup(jPanelAsesoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelAsesoresLayout.createSequentialGroup()
                        .addGroup(jPanelAsesoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(tfBuscarIntregantesLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelAsesoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelAsesoresLayout.createSequentialGroup()
                                .addComponent(jButton8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton9))
                            .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelAsesoresLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelAsesoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8))
                        .addGap(42, 42, 42)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jcbTipoPublicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfProyectoRelacionado, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(btnPublicaciones))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel5)
                                .addComponent(jLabel1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jLabel4)))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jxDatePub, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtfIsbn, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanelAsesores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(79, 79, 79)
                                .addComponent(jLabel5))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jtfIsbn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)))
                    .addComponent(jPanelAsesores, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jxDatePub, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton4)
                        .addComponent(jtfProyectoRelacionado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnPublicaciones))
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jcbTipoPublicacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(111, 111, 111))
        );

        jTabbedPane1.addTab(org.openide.util.NbBundle.getMessage(diagEditorial.class, "diagEditorial.jPanel1.TabConstraints.tabTitle"), jPanel1); // NOI18N

        jScrollPane4.setViewportView(jListEvaluaciones);

        jLabel10.setText(org.openide.util.NbBundle.getMessage(diagEditorial.class, "diagEditorial.jLabel10.text")); // NOI18N

        btAgregarEvaluacion.setText(org.openide.util.NbBundle.getMessage(diagEditorial.class, "diagEditorial.btAgregarEvaluacion.text")); // NOI18N
        btAgregarEvaluacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAgregarEvaluacionActionPerformed(evt);
            }
        });

        btnEditarEvaluacion.setText(org.openide.util.NbBundle.getMessage(diagEditorial.class, "diagEditorial.btnEditarEvaluacion.text")); // NOI18N
        btnEditarEvaluacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarEvaluacionActionPerformed(evt);
            }
        });

        btnEliminarEvaluacion.setText(org.openide.util.NbBundle.getMessage(diagEditorial.class, "diagEditorial.btnEliminarEvaluacion.text")); // NOI18N
        btnEliminarEvaluacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarEvaluacionActionPerformed(evt);
            }
        });

        btVerDetallesEvaluacionSeleccionada.setText(org.openide.util.NbBundle.getMessage(diagEditorial.class, "diagEditorial.btVerDetallesEvaluacionSeleccionada.text")); // NOI18N
        btVerDetallesEvaluacionSeleccionada.setEnabled(false);
        btVerDetallesEvaluacionSeleccionada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVerDetallesEvaluacionSeleccionadaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnEditarEvaluacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btAgregarEvaluacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnEliminarEvaluacion, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel10)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(btVerDetallesEvaluacionSeleccionada)))
                .addContainerGap(728, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btAgregarEvaluacion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEditarEvaluacion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEliminarEvaluacion)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btVerDetallesEvaluacionSeleccionada)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab(org.openide.util.NbBundle.getMessage(diagEditorial.class, "diagEditorial.jPanel2.TabConstraints.tabTitle"), jPanel2); // NOI18N

        jScrollPane5.setViewportView(jListUnidades);

        btAgregarEvaluacion1.setText(org.openide.util.NbBundle.getMessage(diagEditorial.class, "diagEditorial.btAgregarEvaluacion1.text")); // NOI18N
        btAgregarEvaluacion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAgregarEvaluacion1ActionPerformed(evt);
            }
        });

        btnEliminarEvaluacion1.setText(org.openide.util.NbBundle.getMessage(diagEditorial.class, "diagEditorial.btnEliminarEvaluacion1.text")); // NOI18N
        btnEliminarEvaluacion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarEvaluacion1ActionPerformed(evt);
            }
        });

        jLabel11.setText(org.openide.util.NbBundle.getMessage(diagEditorial.class, "diagEditorial.jLabel11.text")); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btAgregarEvaluacion1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnEliminarEvaluacion1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel11))
                .addContainerGap(819, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btAgregarEvaluacion1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEliminarEvaluacion1)))
                .addContainerGap(176, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab(org.openide.util.NbBundle.getMessage(diagEditorial.class, "diagEditorial.jPanel3.TabConstraints.tabTitle"), jPanel3); // NOI18N

        taResumen.setColumns(20);
        taResumen.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        taResumen.setLineWrap(true);
        taResumen.setRows(20);
        jScrollPane6.setViewportView(taResumen);

        taSummary.setColumns(20);
        taSummary.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        taSummary.setLineWrap(true);
        taSummary.setRows(20);
        jScrollPane8.setViewportView(taSummary);

        jLabel12.setText(org.openide.util.NbBundle.getMessage(diagEditorial.class, "diagEditorial.jLabel12.text")); // NOI18N

        jLabel25.setText(org.openide.util.NbBundle.getMessage(diagEditorial.class, "diagEditorial.jLabel25.text")); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel25)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 767, Short.MAX_VALUE)
                    .addComponent(jScrollPane8))
                .addContainerGap(322, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel25)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(89, 89, 89))
        );

        jTabbedPane1.addTab(org.openide.util.NbBundle.getMessage(diagEditorial.class, "diagEditorial.jPanel4.TabConstraints.tabTitle"), jPanel4); // NOI18N

        jButton3.setText(org.openide.util.NbBundle.getMessage(diagEditorial.class, "diagEditorial.jButton3.text")); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(459, 459, 459)
                .addComponent(jButton2)
                .addGap(46, 46, 46)
                .addComponent(jButton3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        guardar();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnEliminarEvaluacion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarEvaluacion1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarEvaluacion1ActionPerformed

    private void btAgregarEvaluacion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAgregarEvaluacion1ActionPerformed
        agregarStock();        // TODO add your handling code here:
    }//GEN-LAST:event_btAgregarEvaluacion1ActionPerformed

    private void btVerDetallesEvaluacionSeleccionadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVerDetallesEvaluacionSeleccionadaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btVerDetallesEvaluacionSeleccionadaActionPerformed

    private void btnEliminarEvaluacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarEvaluacionActionPerformed
        eliminarEvaluacion();
    }//GEN-LAST:event_btnEliminarEvaluacionActionPerformed

    private void btnEditarEvaluacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarEvaluacionActionPerformed
        modificarEvaluacion();
    }//GEN-LAST:event_btnEditarEvaluacionActionPerformed

    private void btAgregarEvaluacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAgregarEvaluacionActionPerformed
        agregarNuevaEvaluacion();        // TODO add your handling code here:
    }//GEN-LAST:event_btAgregarEvaluacionActionPerformed

    private void btnPublicacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPublicacionesActionPerformed
        mostrarPublicaciones();
    }//GEN-LAST:event_btnPublicacionesActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        nuevoTipoDePublicacion();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        agregarProyecto();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        agregarIntegrantesLibro();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        quitarIntegrantesLibro();
    }//GEN-LAST:event_jButton9ActionPerformed

    private void tfBuscarIntregantesLibroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfBuscarIntregantesLibroKeyPressed
        buscarIntegrantesLibro();
    }//GEN-LAST:event_tfBuscarIntregantesLibroKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(diagEditorial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(diagEditorial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(diagEditorial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(diagEditorial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                diagEditorial dialog = new diagEditorial(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAgregarEvaluacion;
    private javax.swing.JButton btAgregarEvaluacion1;
    private javax.swing.JButton btVerDetallesEvaluacionSeleccionada;
    private javax.swing.JButton btnEditarEvaluacion;
    private javax.swing.JButton btnEliminarEvaluacion;
    private javax.swing.JButton btnEliminarEvaluacion1;
    private javax.swing.JButton btnPublicaciones;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList jListEvaluaciones;
    private javax.swing.JList jListUnidades;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanelAsesores;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JComboBox jcbTipoPublicacion;
    private javax.swing.JTextArea jtaMenciones;
    private javax.swing.JTextField jtfIsbn;
    private javax.swing.JTextField jtfProyectoRelacionado;
    private javax.swing.JTextArea jtfTitulo;
    private org.jdesktop.swingx.JXDatePicker jxDatePub;
    private javax.swing.JList lsIntegrantesFueraLibro;
    private javax.swing.JList lstIntegrantesDentroLibro;
    private javax.swing.JTextArea taResumen;
    private javax.swing.JTextArea taSummary;
    private javax.swing.JTextField tfBuscarIntregantesLibro;
    // End of variables declaration//GEN-END:variables

    private void inicializarComponentes() {
        cargarTipoPublicacion();
        btnPublicaciones.setEnabled(false);
        
        this.setSize(new Dimension(Toolkit.getDefaultToolkit().getScreenSize()));

        switch (tipoOperacion) {
            case "Alta":
                break;
            case "Modificación":
                try {
                    if (editorialCientifica.getTitulo() != null) {
                        jtfTitulo.setText(editorialCientifica.getTitulo());

                    }
                } catch (NullPointerException ex) {
                }                
                try {
                    if (!listaUnidades.isEmpty()) {
                        cargarListaUnidades();
                    }
                } catch (NullPointerException ex) {
                }                

                /*try {
                    if (editorialCientifica.getResumen() != null) {
                        jtaResumen.setText(editorialCientifica.getResumen());

                    }
                } catch (NullPointerException ex) {
                }*/

                try {
                    if (editorialCientifica.getAnioPublicacion() != null) {
                        jxDatePub.setDate(editorialCientifica.getAnioPublicacion());

                    }
                } catch (NullPointerException ex) {
                }

                try {
                    if (editorialCientifica.getISBN() != null) {
                        jtfIsbn.setText(editorialCientifica.getISBN());

                    }
                } catch (NullPointerException ex) {
                }

                try {
                    if (editorialCientifica.getMenciones() != null) {
                        jtaMenciones.setText(editorialCientifica.getMenciones());

                    }
                } catch (NullPointerException ex) {
                }

                try {
                    if (editorialCientifica.getProyecto() != null) {
                        proyecto = editorialCientifica.getProyecto();
                        jtfProyectoRelacionado.setText(editorialCientifica.getProyecto().toString());

                    }
                } catch (NullPointerException ex) {
                }

                try {
                    if (editorialCientifica.getTipoPublicacion() != null) {

                        jcbTipoPublicacion.setSelectedItem(editorialCientifica.getTipoPublicacion());

                    }
                } catch (NullPointerException ex) {
                }
                try{
                    if (!evaluaciones.isEmpty()){
                        
                    
                        Comunes.cargarJList(jListEvaluaciones, evaluaciones);}
                } catch (NullPointerException ex) {
                }
        }
    }

    

    private void asignarDatos() {
        editorialCientifica.setTitulo(jtfTitulo.getText());
        /*editorialCientifica.setAutor(jtfAutor.getText());
        if (!jtfCoautor.getText().equals("")) {
            editorialCientifica.setCoautor(jtfCoautor.getText());
        } else {
            editorialCientifica.setCoautor(null);
        }*/
        editorialCientifica.setTitulo(jtfTitulo.getText());        
        if (!taResumen.getText().equals("")) {
            editorialCientifica.setResumen(taResumen.getText());
        } else {
            editorialCientifica.setResumen(null);
        }
        if (!taSummary.getText().equals("")) {
            editorialCientifica.setSummary(taSummary.getText());
        } else {
            editorialCientifica.setSummary(null);
        }       
        editorialCientifica.setAnioPublicacion(jxDatePub.getDate());
        editorialCientifica.setISBN(jtfIsbn.getText());

        if (!jtaMenciones.getText().equals("")) {
            editorialCientifica.setMenciones(jtaMenciones.getText());
        } else {
            editorialCientifica.setMenciones(null);
        }
        // editorialCientifica.setProyecto((jtfProyectoRelacionado.getText());

        if (jcbTipoPublicacion.getSelectedIndex() > 0) {
            editorialCientifica.setTipoPublicacion((TipoPublicacion) jcbTipoPublicacion.getSelectedItem());
        } else {
            editorialCientifica.setTipoPublicacion(null);
        }
        if (jtfProyectoRelacionado.getText() != null) {
            editorialCientifica.setProyecto(proyecto);
        } else {
            editorialCientifica.setProyecto(null);
        }
        if (!evaluaciones.isEmpty()){
            editorialCientifica.setEvaluacionesEditorial(evaluaciones);
        } else {
            editorialCientifica.setEvaluacionesEditorial(null);
        }
        
    }

    private void altaEditorial() {
        try {
            EditorialCientificaFacade.getInstance().alta(editorialCientifica);
            Operacion operacion = new Operacion();
            operacion.setFecha(Comunes.obtenerFechaActualDesdeDB());
            operacion.setOperacion("Alta de publicación científica");
            operacion.setUsuario(usuario);
            OperacionFacade.getInstance().alta(operacion);

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error creando publicación científica\n " + ex);
        }
    }

    private void altaStock() {
        for (Stock s : listaUnidades) {
            try {
                s.setPublicacion(editorialCientifica);
                StockFacade.getInstance().alta(s);
                Operacion operacion = new Operacion();
                operacion.setFecha(Comunes.obtenerFechaActualDesdeDB());
                operacion.setOperacion("Alta de stock de publicación científica");
                operacion.setUsuario(usuario);
                OperacionFacade.getInstance().alta(operacion);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Error creando stock de publicación científica\n " + ex);
            }
        }
    }


    private void modificarEditorial() {

        try {
            EditorialCientificaFacade.getInstance().modificar(editorialCientifica);
            Operacion operacion = new Operacion();
            operacion.setFecha(Comunes.obtenerFechaActualDesdeDB());
            operacion.setOperacion("Modificación de publicación científica");
            operacion.setUsuario(usuario);
            OperacionFacade.getInstance().alta(operacion);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error modificando publicación científica\n " + ex);
        }
    }

    private void guardar() {
        if (validar()) {
            if (tipoOperacion.equals("Alta")) {
                editorialCientifica = new EditorialCientifica();
                asignarDatos();
                altaEditorial();
                altaStock();
                diagExpedienteEditorial expedienteEditorial;
                expedienteEditorial = new diagExpedienteEditorial(null, true, editorialCientifica, usuario, "Alta");
                expedienteEditorial.setLocation(Comunes.centrarDialog(expedienteEditorial));
                expedienteEditorial.setVisible(true);
                this.dispose();
            } else if (tipoOperacion.equals("Modificación")) {
                asignarDatos();
                modificarEditorial();
                this.dispose();
            }
        }
    }

    private boolean validar() {
        boolean flag = false;
        if (!jtfTitulo.getText().equals("")) {            
            if (!jtfIsbn.getText().equals("")) {

                flag = true;
            } else {
                JOptionPane.showMessageDialog(null, "Debe ingresar el ISBN de la publicación", "Error", JOptionPane.ERROR_MESSAGE);
            }            
        } else {
            JOptionPane.showMessageDialog(null, "Debe ingresar el título de la publicación", "Error", JOptionPane.ERROR_MESSAGE);
        }
        jtfTitulo.requestFocus();
        return flag;
    }

    private void cargarTipoPublicacion() {
        Comunes.cargarJComboConBlanco(jcbTipoPublicacion, TipoPublicacionFacade.getInstance().listarTodos());
    }

    private void agregarProyecto() {
        diagProyectoBusquedaSimple busquedaSimple = new diagProyectoBusquedaSimple(null, true);
        busquedaSimple.setVisible(true);
        busquedaSimple.setLocation(Comunes.centrarDialog(busquedaSimple));

        if (busquedaSimple.getProyecto() != null) {
            proyectoSele = busquedaSimple.getProyecto();

            jtfProyectoRelacionado.setText(proyectoSele.toString());
            btnPublicaciones.setEnabled(true);
        } else {
            btnPublicaciones.setEnabled(false);
            JOptionPane.showMessageDialog(null, "No seleccionó ningún proyecto");
        }
    }

    private void agregarNuevaEvaluacion() {
        diagEvaluacionEditorial evaluacion = new diagEvaluacionEditorial(null, true, "Alta", usuario);
        evaluacion.setLocation(Comunes.centrarDialog(evaluacion));
        evaluacion.setVisible(true);
        if (evaluacion.getEvaluacionCreada() != null) {
            evaluaciones.add(evaluacion.getEvaluacionCreada());
            cargarEvaluaciones();
        }

    }

    private void agregarStock() {
        diagStock stock;
        if (editorialCientifica != null){
           stock = new diagStock(null, true, usuario, 
                   "Alta", "Editorial", editorialCientifica);

        } else {
            // Estoy creando la publicación por primera vez por lo que no hay
            // un objeto editorialCientifica aun.
           stock = new diagStock(null, true, usuario,
                    "Alta", "Editorial");

        }
        
        stock.setLocation(Comunes.centrarDialog(stock));
        stock.setVisible(true);
        if (stock.getStockCreado() != null) {
            listaUnidades.add(stock.getStockCreado());
            cargarListaUnidades();
        }
    }

    private void cargarListaUnidades() {
        Comunes.cargarJList(jListUnidades, listaUnidades);
    }

    private void modificarEvaluacion() {
        if (jListEvaluaciones.getSelectedIndex() != -1) {
            
            evaluacionEditorial = (EvaluacionEditorial) jListEvaluaciones.getSelectedValue();
            diagEvaluacionEditorial diagevaluacion = new diagEvaluacionEditorial(null, true, "Modificación", evaluacionEditorial, usuario);
            diagevaluacion.setLocation(Comunes.centrarDialog(diagevaluacion));
            diagevaluacion.setVisible(true);
            if (diagevaluacion.getEvaluacionCreada() != null) {
                
                cargarEvaluaciones();
            }

        } else {
            JOptionPane.showMessageDialog(null, "Debe seleccionar una evaluacion");
        }
    }

    private void cargarEvaluaciones() {
        Comunes.cargarJList(jListEvaluaciones, evaluaciones);
    }

    private void eliminarEvaluacion() {
        if (jListEvaluaciones.getSelectedIndex() != -1) {
            int i = JOptionPane.showConfirmDialog(null, "Se eliminaran las dos evaluaciones individuales \n correspondientes. "
                    + "¿Está usted seguro?", "Confirmar", JOptionPane.YES_NO_CANCEL_OPTION);
            if (i == JOptionPane.YES_OPTION) {
                EvaluacionEditorial evaluacionEliminar =  (EvaluacionEditorial) jListEvaluaciones.getSelectedValue();
                evaluaciones.remove(evaluacionEliminar);
                EvaluacionEditorialFacade.getInstance().Eliminar(evaluacionEliminar.getId());
                JOptionPane.showMessageDialog(null, "Evaluacion Eliminada!");
                cargarEvaluaciones();

            }
        } else {
            JOptionPane.showMessageDialog(null, "Debe seleccionar una fila!");
        }
    }

//    private void eliminarStock() {
//        if (jListUnidades.getSelectedIndex() != -1) {
//            int i = JOptionPane.showConfirmDialog(null, "Se eliminaran las tres evaluaciones \n correspondientes. "
//                    + "Esta usted Seguro?", "Confirmar", JOptionPane.YES_NO_CANCEL_OPTION);
//            if (i == JOptionPane.YES_OPTION) {
//                EvaluacionEditorial evaluacionEliminar = EvaluacionEditorialFacade.getInstance().buscar((Long) jListEvaluaciones.getSelectedValue());
//                evaluaciones.remove(evaluacionEliminar);
//                EvaluacionEditorialFacade.getInstance().Eliminar(evaluacionEliminar.getId());
//                JOptionPane.showMessageDialog(null, "Evaluacion Eliminada!");
//                cargarEvaluaciones();
//
//            }
//        } else {
//            JOptionPane.showMessageDialog(null, "Debe seleccionar una fila!");
//        }
//    }

    private void nuevoTipoDePublicacion() {
    diagTipoEditorial tipo = new diagTipoEditorial(null, true,  usuario, "Alta");
        tipo.setLocation(Comunes.centrarDialog(tipo));
        tipo.setVisible(true);
        cargarTipos();
           }
    private void cargarTipos(){
        Comunes.cargarJCombo(jcbTipoPublicacion, TipoPublicacionFacade.getInstance().listarTodos());
    }

    private void mostrarPublicaciones() {
        diagProyectoResultado publicaciones = new diagProyectoResultado(null, true, usuario, proyectoSele);
        publicaciones.setLocation(Comunes.centrarDialog(publicaciones));
        publicaciones.setVisible(true);
        
    }    

    private void agregarIntegrantesLibro() {
        if (lsIntegrantesFueraLibro.getSelectedIndex() != -1) {

            integrantesDentroLibro.add((Investigador) lsIntegrantesFueraLibro.getSelectedValue());
            List<Investigador> integrantesFuera = InvestigadorFacade.getInstance().getTodosInvestigador();
            integrantesFuera.removeAll(integrantesDentroLibro);
            Comunes.cargarJList(lsIntegrantesFueraLibro, integrantesFuera);

            Comunes.cargarJList(lstIntegrantesDentroLibro, integrantesDentroLibro);

        } else {
            JOptionPane.showMessageDialog(rootPane, "Debe escoger un Autor", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void quitarIntegrantesLibro() {
        if (lstIntegrantesDentroLibro.getSelectedIndex() != -1) {

            integrantesDentroLibro.remove((Investigador) lstIntegrantesDentroLibro.getSelectedValue());
            List<Investigador> integrantesFuera = InvestigadorFacade.getInstance().getTodosInvestigador();
            integrantesFuera.removeAll(integrantesDentroLibro);
            Comunes.cargarJList(lsIntegrantesFueraLibro, integrantesFuera);

            Comunes.cargarJList(lstIntegrantesDentroLibro, integrantesDentroLibro);

        }
    }

    private void buscarIntegrantesLibro() {
        if (!tfBuscarIntregantesLibro.getText().equals("")) {
            Comunes.cargarJList(lsIntegrantesFueraLibro, InvestigadorFacade.getInstance().buscarPorApellidoNombre(tfBuscarIntregantesLibro.getText()));
        } else {
            Comunes.cargarJList(lsIntegrantesFueraLibro, InvestigadorFacade.getInstance().getTodosInvestigador());
        }
    }
}
