/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas.mensajes;

import entidades.persona.investigador.AreaSecyt;
import entidades.persona.investigador.Destinatario;
import entidades.persona.investigador.Investigador;
import entidades.persona.investigador.Mensaje;
import entidades.persona.investigador.PlantillaMensaje;
import facade.AreaSecytFacade;
import facade.MensajeFacade;
import includes.Comunes;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JList;
import javax.swing.JOptionPane;
import vista.diagInvestigadorBusquedaMultiple;
import vista.diagInvestigadorBusquedaSimple;

/**
 *
 * @author hugo
 */
public class diagMensajeRespuesta extends javax.swing.JDialog {

    private Mensaje mensaje = new Mensaje();
    private String tipoMensaje;
    private List<Investigador> listaInvestigadores = new ArrayList<>();
    private PlantillaMensaje plantillaMensaje;

    /**
     * Creates new form diagMensajeRespuesta
     */
    public diagMensajeRespuesta(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        inicializarComponentes();
    }

    public diagMensajeRespuesta(java.awt.Frame parent, boolean modal, String tipoMensaje) {
        super(parent, modal);
        initComponents();
        this.tipoMensaje = tipoMensaje;
        inicializarComponentes();
    }
        public diagMensajeRespuesta(java.awt.Frame parent, boolean modal, String tipoMensaje,PlantillaMensaje plantillaMensaje) {
        super(parent, modal);
        initComponents();
        this.tipoMensaje = tipoMensaje;
        this.plantillaMensaje=plantillaMensaje;
        inicializarComponentes();
    }

    public diagMensajeRespuesta(java.awt.Frame parent, boolean modal, Mensaje mensaje, String tipoMensaje) {
        super(parent, modal);
        initComponents();
        this.mensaje = mensaje;
        this.tipoMensaje = tipoMensaje;
        inicializarComponentes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taRespuesta = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cboAreaSecyt = new javax.swing.JComboBox();
        btnBuscarInvestigador = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListInvestigadores = new javax.swing.JList();
        btnRespuesta = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(diagMensajeRespuesta.class, "diagMensajeRespuesta.jPanel1.border.title"))); // NOI18N

        taRespuesta.setColumns(20);
        taRespuesta.setRows(5);
        jScrollPane1.setViewportView(taRespuesta);

        jLabel1.setText(org.openide.util.NbBundle.getMessage(diagMensajeRespuesta.class, "diagMensajeRespuesta.jLabel1.text")); // NOI18N

        jLabel2.setText(org.openide.util.NbBundle.getMessage(diagMensajeRespuesta.class, "diagMensajeRespuesta.jLabel2.text")); // NOI18N

        cboAreaSecyt.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnBuscarInvestigador.setText(org.openide.util.NbBundle.getMessage(diagMensajeRespuesta.class, "diagMensajeRespuesta.btnBuscarInvestigador.text")); // NOI18N
        btnBuscarInvestigador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarInvestigadorActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(jListInvestigadores);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 477, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(cboAreaSecyt, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnBuscarInvestigador, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cboAreaSecyt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(btnBuscarInvestigador))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 13, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        btnRespuesta.setText(org.openide.util.NbBundle.getMessage(diagMensajeRespuesta.class, "diagMensajeRespuesta.btnRespuesta.text")); // NOI18N
        btnRespuesta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRespuestaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(154, 154, 154)
                .addComponent(btnRespuesta, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRespuesta)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRespuestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRespuestaActionPerformed
        enviarMensaje();
    }//GEN-LAST:event_btnRespuestaActionPerformed

    private void btnBuscarInvestigadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarInvestigadorActionPerformed
        buscarInvestigador();
    }//GEN-LAST:event_btnBuscarInvestigadorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(diagMensajeRespuesta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(diagMensajeRespuesta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(diagMensajeRespuesta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(diagMensajeRespuesta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                diagMensajeRespuesta dialog = new diagMensajeRespuesta(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarInvestigador;
    private javax.swing.JButton btnRespuesta;
    private javax.swing.JComboBox cboAreaSecyt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JList jListInvestigadores;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea taRespuesta;
    // End of variables declaration//GEN-END:variables

    private void inicializarComponentes() {
        try {
            Comunes.cargarJCombo(cboAreaSecyt, AreaSecytFacade.getInstance().listar());
        } catch (Exception ex) {
            Logger.getLogger(diagMensajeRespuesta.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (tipoMensaje.equals("Respuesta")) {
            cboAreaSecyt.setSelectedItem(mensaje.getAreaSecyt());
            listaInvestigadores.add(mensaje.getInvestigador());
            Comunes.cargarJList(jListInvestigadores, listaInvestigadores);
            btnBuscarInvestigador.setVisible(false);
            cboAreaSecyt.setEnabled(false);

        }
        if(tipoMensaje.equals("Plantilla")){
            listaInvestigadores=plantillaMensaje.getListaInvestigadores();
            Comunes.cargarJList(jListInvestigadores, listaInvestigadores);
            taRespuesta.setText(plantillaMensaje.getMensaje());
        }

    }

    private void enviarMensaje() {
        int cuentaMensajes=0;
        System.out.println("Lista investigadores: "+listaInvestigadores.size());
        if (validar()) {
            for (Investigador investigador : listaInvestigadores) {
                cuentaMensajes++;
                Mensaje mensajeRespuesta = new Mensaje();
                mensajeRespuesta.setAreaSecyt((AreaSecyt) cboAreaSecyt.getSelectedItem());
                mensajeRespuesta.setDescripcion(taRespuesta.getText());
                mensajeRespuesta.setDestinatario(Destinatario.INVESTIGADOR);
                mensajeRespuesta.setFechaEnvio(Comunes.obtenerFechaActualDesdeDB());
                mensajeRespuesta.setInvestigador(investigador);
                mensajeRespuesta.setLeido(false);
                mensajeRespuesta.setBorrado(false);
                try {
                    MensajeFacade.getInstance().alta(mensajeRespuesta);
                                        
                } catch (Exception ex) {
                    Logger.getLogger(diagMensajeRespuesta.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            System.out.println(cuentaMensajes+" Mensaje/s enviado/s!!");
            JOptionPane.showMessageDialog(null, cuentaMensajes+" Mensaje/s enviado/s!!");
            this.dispose();





        }


    }

    private boolean validar() {
        if (!listaInvestigadores.isEmpty()) {
            if (!taRespuesta.getText().isEmpty()) {
                return true;
            } else {
                JOptionPane.showMessageDialog(null, "Debe escribir un mensaje de respuesta!!");
                return false;

            }
        } else {
            JOptionPane.showMessageDialog(null, "Debe Seleccionar al menos un Investigador!!");
            return false;
        }

    }

    private void buscarInvestigador() {
        diagInvestigadorBusquedaMultiple busqueda = new diagInvestigadorBusquedaMultiple(null, true);
        busqueda.setLocation(Comunes.centrarDialog(busqueda));
        busqueda.setVisible(true);
        if (busqueda.getListaInvestigador() != null) {
            //mensaje.setInvestigador(busqueda.getInvestigador());
            listaInvestigadores = busqueda.getListaInvestigador();
            Comunes.cargarJList(jListInvestigadores, listaInvestigadores);
            //jListInvestigadores.setText(busqueda.getInvestigador().toString());
        }
    }
}
