/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas.mensajes;

import entidades.persona.investigador.AreaSecyt;
import entidades.persona.investigador.Destinatario;
import entidades.persona.investigador.Investigador;
import entidades.persona.investigador.Mensaje;
import entidades.persona.investigador.PlantillaMensaje;
import facade.AreaSecytFacade;
import facade.MensajeFacade;
import facade.PlantillaMensajeFacade;
import includes.Comunes;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JList;
import javax.swing.JOptionPane;
import vista.diagInvestigadorBusquedaMultiple;
import vista.diagInvestigadorBusquedaMultiple2;
import vista.diagInvestigadorBusquedaSimple;

/**
 *
 * @author hugo
 */
public class diagPlantilla extends javax.swing.JDialog {

    private PlantillaMensaje plantillaMensaje;
    private String tipoOperacion;
    private List<Investigador> listaInvestigadores = new ArrayList<>();

    public PlantillaMensaje getPlantillaMensaje() {
        return plantillaMensaje;
    }

    public void setPlantillaMensaje(PlantillaMensaje plantillaMensaje) {
        this.plantillaMensaje = plantillaMensaje;
    }

    public String getTipoOperacion() {
        return tipoOperacion;
    }

     public void setTipoOperacion(String tipoOperacion) {
        this.tipoOperacion = tipoOperacion;
    }

    /**
     * Creates new form diagMensajeRespuesta
     */
    public diagPlantilla(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        inicializarComponentes();
    }

    public diagPlantilla(java.awt.Frame parent, boolean modal, String tipoOperacion) {
        super(parent, modal);
        initComponents();
        this.tipoOperacion = tipoOperacion;
        inicializarComponentes();
    }

    public diagPlantilla(java.awt.Frame parent, boolean modal, PlantillaMensaje plantillaMensaje, String tipoOperacion) {
        super(parent, modal);
        initComponents();
        this.tipoOperacion = tipoOperacion;
        this.plantillaMensaje = plantillaMensaje;
        inicializarComponentes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taRespuesta = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        btnBuscarInvestigador = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListInvestigadores = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();
        tfNombrePlantilla = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnRespuesta = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(diagPlantilla.class, "diagPlantilla.jPanel1.border.title"))); // NOI18N

        taRespuesta.setColumns(20);
        taRespuesta.setRows(5);
        jScrollPane1.setViewportView(taRespuesta);

        jLabel2.setText(org.openide.util.NbBundle.getMessage(diagPlantilla.class, "diagPlantilla.jLabel2.text")); // NOI18N

        btnBuscarInvestigador.setText(org.openide.util.NbBundle.getMessage(diagPlantilla.class, "diagPlantilla.btnBuscarInvestigador.text")); // NOI18N
        btnBuscarInvestigador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarInvestigadorActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(jListInvestigadores);

        jLabel1.setText(org.openide.util.NbBundle.getMessage(diagPlantilla.class, "diagPlantilla.jLabel1.text")); // NOI18N

        tfNombrePlantilla.setText(org.openide.util.NbBundle.getMessage(diagPlantilla.class, "diagPlantilla.tfNombrePlantilla.text")); // NOI18N

        jLabel3.setText(org.openide.util.NbBundle.getMessage(diagPlantilla.class, "diagPlantilla.jLabel3.text")); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(tfNombrePlantilla, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBuscarInvestigador, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfNombrePlantilla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnBuscarInvestigador)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                        .addComponent(jLabel3))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        btnRespuesta.setText(org.openide.util.NbBundle.getMessage(diagPlantilla.class, "diagPlantilla.btnRespuesta.text")); // NOI18N
        btnRespuesta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRespuestaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(167, 167, 167)
                .addComponent(btnRespuesta, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(184, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRespuesta)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRespuestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRespuestaActionPerformed
        guardarPlantilla();
    }//GEN-LAST:event_btnRespuestaActionPerformed

    private void btnBuscarInvestigadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarInvestigadorActionPerformed
        buscarInvestigador();
    }//GEN-LAST:event_btnBuscarInvestigadorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(diagPlantilla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(diagPlantilla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(diagPlantilla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(diagPlantilla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                diagPlantilla dialog = new diagPlantilla(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarInvestigador;
    private javax.swing.JButton btnRespuesta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JList jListInvestigadores;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea taRespuesta;
    private javax.swing.JTextField tfNombrePlantilla;
    // End of variables declaration//GEN-END:variables

    private void inicializarComponentes() {

        if (tipoOperacion.equals("Modificación")) {
            try {
                tfNombrePlantilla.setText(plantillaMensaje.getDescripcion());
            } catch (Exception e) {

            }
            try {
                listaInvestigadores = plantillaMensaje.getListaInvestigadores();
                Comunes.cargarJList(jListInvestigadores, listaInvestigadores);
            } catch (Exception e) {

            }
            try {
                taRespuesta.setText(plantillaMensaje.getMensaje());
            } catch (Exception e) {

            }

        }

    }

    private void guardarPlantilla() {

        if (validar()) {
            if (tipoOperacion.equals("Alta")) {
                plantillaMensaje = new PlantillaMensaje();
                plantillaMensaje.setDescripcion(tfNombrePlantilla.getText());
                plantillaMensaje.setListaInvestigadores(listaInvestigadores);
                plantillaMensaje.setMensaje(taRespuesta.getText());
                plantillaMensaje.setFecha(Comunes.obtenerFechaActualDesdeDB());
                try {
                    PlantillaMensajeFacade.getInstance().alta(plantillaMensaje);

                } catch (Exception ex) {
                    Logger.getLogger(diagPlantilla.class.getName()).log(Level.SEVERE, null, ex);
                }
                JOptionPane.showMessageDialog(null, "Plantilla de mensaje guardada!");

                this.dispose();
            }
            if(tipoOperacion.equals("Modificación")){
                plantillaMensaje.setDescripcion(tfNombrePlantilla.getText());
                plantillaMensaje.setListaInvestigadores(listaInvestigadores);
                plantillaMensaje.setMensaje(taRespuesta.getText());
                try {
                    PlantillaMensajeFacade.getInstance().modificar(plantillaMensaje);

                } catch (Exception ex) {
                    Logger.getLogger(diagPlantilla.class.getName()).log(Level.SEVERE, null, ex);
                }
                JOptionPane.showMessageDialog(null, "Plantilla modificada!");

                this.dispose();
            }

        }

    }

    private boolean validar() {
        if (!listaInvestigadores.isEmpty()) {
            if (!taRespuesta.getText().isEmpty()) {
                return true;
            } else {
                JOptionPane.showMessageDialog(null, "Debe escribir un mensaje!!");
                return false;

            }
        } else {
            JOptionPane.showMessageDialog(null, "Debe Seleccionar al menos un Investigador!");
            return false;
        }

    }

    private void buscarInvestigador() {
        diagInvestigadorBusquedaMultiple2 busqueda = new diagInvestigadorBusquedaMultiple2(null, true);
        busqueda.setLocation(Comunes.centrarDialog(busqueda));
        busqueda.setVisible(true);
        if (busqueda.getListaInvestigador() != null) {
            //mensaje.setInvestigador(busqueda.getInvestigador());
            listaInvestigadores = busqueda.getListaInvestigador();
            Comunes.cargarJList(jListInvestigadores, listaInvestigadores);
            //jListInvestigadores.setText(busqueda.getInvestigador().toString());
        }
    }
}
