/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * diagVerDetalleRendicion.java
 *
 * Created on 17/08/2012, 20:00:37
 */
package vista.economico;

import entidades.Documento;
import entidades.economico.Cobro;
import entidades.economico.Rendicion;
import entidades.economico.RendicionDetalle;
import java.awt.Desktop;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.math.BigDecimal;
import java.text.SimpleDateFormat;
import java.util.Collection;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.Collections;

/**
 *
 * @author wbivanco
 */
public class diagVerDetalleRendicion extends javax.swing.JDialog {
    Rendicion rendicion = new Rendicion();   

    public Rendicion getRendicion() {
        return rendicion;
    }

    public void setRendicion(Rendicion rendicion) {
        this.rendicion = rendicion;
    }    
    
     // Formateo las fechas
    SimpleDateFormat formato = new SimpleDateFormat("dd-MM-yyyy");
    
    // Defino aqui el modelos de las tablas para que lo cree una sola vez
    DefaultTableModel modeloTablaDetalleRendicion = new DefaultTableModel()
    {@Override
        public boolean isCellEditable (int fila, int columna){
            return false;
        }
    };
    

    /** Creates new form diagVerDetalleRendicion */
    public diagVerDetalleRendicion(java.awt.Frame parent, boolean modal, 
            Rendicion rendicionSeleccionada) {
        super(parent, modal);
        initComponents();
        setRendicion(rendicionSeleccionada);        
        inicializarComponentes();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tfMonto = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        dpFechaRendicion = new org.jdesktop.swingx.JXDatePicker();
        jScrollPane1 = new javax.swing.JScrollPane();
        taObservacion = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblDetalleRendicion = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        btnImprimirRendicion = new javax.swing.JButton();
        lblTotalBC = new javax.swing.JLabel();
        lblTotalBNP = new javax.swing.JLabel();
        lblTotalGV = new javax.swing.JLabel();
        lblTotalBU = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tfAnioRendido = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tfLibreDeuda = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(org.openide.util.NbBundle.getMessage(diagVerDetalleRendicion.class, "diagVerDetalleRendicion.title")); // NOI18N

        jLabel1.setText(org.openide.util.NbBundle.getMessage(diagVerDetalleRendicion.class, "diagVerDetalleRendicion.jLabel1.text")); // NOI18N

        tfMonto.setText(org.openide.util.NbBundle.getMessage(diagVerDetalleRendicion.class, "diagVerDetalleRendicion.tfMonto.text")); // NOI18N

        jLabel2.setText(org.openide.util.NbBundle.getMessage(diagVerDetalleRendicion.class, "diagVerDetalleRendicion.jLabel2.text")); // NOI18N

        jLabel3.setText(org.openide.util.NbBundle.getMessage(diagVerDetalleRendicion.class, "diagVerDetalleRendicion.jLabel3.text")); // NOI18N

        dpFechaRendicion.setFormats("dd/MM/yyyy");

        taObservacion.setColumns(20);
        taObservacion.setRows(5);
        jScrollPane1.setViewportView(taObservacion);

        tblDetalleRendicion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tblDetalleRendicion);

        jLabel4.setText(org.openide.util.NbBundle.getMessage(diagVerDetalleRendicion.class, "diagVerDetalleRendicion.jLabel4.text")); // NOI18N

        btnImprimirRendicion.setText(org.openide.util.NbBundle.getMessage(diagVerDetalleRendicion.class, "diagVerDetalleRendicion.btnImprimirRendicion.text")); // NOI18N
        btnImprimirRendicion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirRendicionActionPerformed(evt);
            }
        });

        lblTotalBC.setText(org.openide.util.NbBundle.getMessage(diagVerDetalleRendicion.class, "diagVerDetalleRendicion.lblTotalBC.text")); // NOI18N

        lblTotalBNP.setText(org.openide.util.NbBundle.getMessage(diagVerDetalleRendicion.class, "diagVerDetalleRendicion.lblTotalBNP.text")); // NOI18N

        lblTotalGV.setText(org.openide.util.NbBundle.getMessage(diagVerDetalleRendicion.class, "diagVerDetalleRendicion.lblTotalGV.text")); // NOI18N

        lblTotalBU.setText(org.openide.util.NbBundle.getMessage(diagVerDetalleRendicion.class, "diagVerDetalleRendicion.lblTotalBU.text")); // NOI18N

        jLabel5.setText(org.openide.util.NbBundle.getMessage(diagVerDetalleRendicion.class, "diagVerDetalleRendicion.jLabel5.text")); // NOI18N

        tfAnioRendido.setText(org.openide.util.NbBundle.getMessage(diagVerDetalleRendicion.class, "diagVerDetalleRendicion.tfAnioRendido.text")); // NOI18N

        jLabel6.setText(org.openide.util.NbBundle.getMessage(diagVerDetalleRendicion.class, "diagVerDetalleRendicion.jLabel6.text")); // NOI18N

        tfLibreDeuda.setText(org.openide.util.NbBundle.getMessage(diagVerDetalleRendicion.class, "diagVerDetalleRendicion.tfLibreDeuda.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 607, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(dpFechaRendicion, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(83, 83, 83)
                                    .addComponent(jLabel6)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(tfLibreDeuda))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(tfMonto, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(72, 72, 72)
                                    .addComponent(jLabel5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(tfAnioRendido, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 723, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(201, 201, 201)
                                .addComponent(btnImprimirRendicion, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTotalBC)
                .addGap(80, 80, 80)
                .addComponent(lblTotalBNP)
                .addGap(82, 82, 82)
                .addComponent(lblTotalGV)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTotalBU)
                .addGap(37, 37, 37))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfMonto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(tfAnioRendido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(dpFechaRendicion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(tfLibreDeuda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(32, 32, 32))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnImprimirRendicion)
                        .addGap(11, 11, 11)))
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotalBC)
                    .addComponent(lblTotalBNP)
                    .addComponent(lblTotalGV)
                    .addComponent(lblTotalBU))
                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnImprimirRendicionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirRendicionActionPerformed
        abrirDetalleRendicion();
    }//GEN-LAST:event_btnImprimirRendicionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(diagVerDetalleRendicion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(diagVerDetalleRendicion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(diagVerDetalleRendicion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(diagVerDetalleRendicion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                diagVerDetalleRendicion dialog = new diagVerDetalleRendicion(new javax.swing.JFrame(), true, 
                        new Rendicion());
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnImprimirRendicion;
    private org.jdesktop.swingx.JXDatePicker dpFechaRendicion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblTotalBC;
    private javax.swing.JLabel lblTotalBNP;
    private javax.swing.JLabel lblTotalBU;
    private javax.swing.JLabel lblTotalGV;
    private javax.swing.JTextArea taObservacion;
    private javax.swing.JTable tblDetalleRendicion;
    private javax.swing.JTextField tfAnioRendido;
    private javax.swing.JTextField tfLibreDeuda;
    private javax.swing.JTextField tfMonto;
    // End of variables declaration//GEN-END:variables

    private void inicializarComponentes() {
        this.setLocationRelativeTo(null);
        habilitarComponentes(false);
        cargarComponentes();        
    }

    private void habilitarComponentes(boolean b) {
        tfMonto.setEditable(b);
        //tfDiferencia.setEditable(b);
        //tfCobro.setEditable(b);
        dpFechaRendicion.setEditable(b);
        taObservacion.setEditable(b);        
        btnImprimirRendicion.setVisible(b);
        tfAnioRendido.setEditable(b);
        tfLibreDeuda.setEditable(b);
        lblTotalBC.setVisible(b);
        lblTotalBNP.setVisible(b);
        lblTotalBU.setVisible(b);
        lblTotalGV.setVisible(b);
    }

    private void cargarTablaDetalleRendicion() {
        cargarEncabezadoDetalleRendicion();
        cargarCuerpoDetalleRendicion();
    }

    private void cargarEncabezadoDetalleRendicion() {
        modeloTablaDetalleRendicion.addColumn("Tipo Bien");
        modeloTablaDetalleRendicion.addColumn("Detalle");
        modeloTablaDetalleRendicion.addColumn("N° Acta");        
        modeloTablaDetalleRendicion.addColumn("N° Comprobante");        
        modeloTablaDetalleRendicion.addColumn("Fecha");   
        modeloTablaDetalleRendicion.addColumn("Monto");   
        tblDetalleRendicion.setModel(modeloTablaDetalleRendicion);
    }

    private void cargarCuerpoDetalleRendicion() {
        List<RendicionDetalle> listaDetalle = getRendicion().getRendicionDetalle();
        Collections.sort(listaDetalle);
        if(listaDetalle.size() > 0){
            Object[] fila = new Object[6];             
            for(int i = 0; i < listaDetalle.size() ;i++){
                fila[0] = listaDetalle.get(i).getTipoBien();
                fila[1] = listaDetalle.get(i).getDetalle();
                fila[2] = listaDetalle.get(i).getNumeroActaPatrimonial();
                fila[3] = listaDetalle.get(i).getNumeroComprobante();                
                //fila[4] = formato.format(listaDetalle.get(i).getFechaCompra());
                fila[4] = listaDetalle.get(i).getFechaCompra();
                fila[5] = listaDetalle.get(i).getPrecioUnitario();
                modeloTablaDetalleRendicion.addRow(fila);
            }
            tblDetalleRendicion.setModel(modeloTablaDetalleRendicion);
        }        
    }

    private void cargarComponentes() {
        List<RendicionDetalle> listaDetalle = getRendicion().getRendicionDetalle();
        if(listaDetalle.size() > 0){
            if(getRendicion().getArchivoRendicion() != null){
                btnImprimirRendicion.setVisible(true);
            }
            calcularTotalesRendicion(listaDetalle);
        }
        cargarTablaDetalleRendicion();
        BigDecimal montoRendido = getRendicion().getMontoRendido();       
        //BigDecimal diferencia = montoRendido.subtract(montoCobrado);
        tfMonto.setText(String.valueOf(montoRendido));
        //tfCobro.setText(getCobro().toString());
        //tfDiferencia.setText(String.valueOf(diferencia));
        taObservacion.setText(getRendicion().getObservacion());
        tfAnioRendido.setText(String.valueOf(getRendicion().getAnioRendido()));
        tfLibreDeuda.setText(getRendicion().getLibreDeuda());
        dpFechaRendicion.setDate(getRendicion().getFechaRendicion());
    }

    private void abrirDetalleRendicion() {
        try {
            Documento documento = rendicion.getArchivoRendicion();
            byte[] archivoInterno = documento.getContenidoArchivo();
            File archivo = File.createTempFile("tmp", documento.getNombreArchivo());
            archivo.deleteOnExit();
            try (FileOutputStream fos = new FileOutputStream(archivo)) {
                fos.write(archivoInterno);
            }
            if (Desktop.isDesktopSupported() == true) {
                Desktop desktop = Desktop.getDesktop();
                try {
                    if (archivo.exists() == true) {
                        desktop.open(archivo);
                    } else {
                        JOptionPane.showMessageDialog(null, "No se encontrar el archivo: " + archivo.getAbsolutePath(), "Aviso", JOptionPane.WARNING_MESSAGE);
                    }
                } catch (IOException e) {
                }
            } else {
                JOptionPane.showMessageDialog(null, "No se puede ejecutar el comando de apertura en este sistema operativo", "Aviso", JOptionPane.WARNING_MESSAGE);
            }
        } catch (IOException ex) {
            Logger.getLogger(diagVerDetalleRendicion.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void calcularTotalesRendicion(List<RendicionDetalle> listaRendicion) {
        BigDecimal totalBC = new BigDecimal("0");
        BigDecimal totalBNP = new BigDecimal("0");
        BigDecimal totalGV = new BigDecimal("0");
        BigDecimal totalBU = new BigDecimal("0");
        for(RendicionDetalle rd: listaRendicion){
            if(rd.getTipoBien().equals("Bien de Consumo")){
                totalBC = totalBC.add(rd.getPrecioUnitario());
            }
            if(rd.getTipoBien().equals("Servicio No Personal")){
                totalBNP = totalBNP.add(rd.getPrecioUnitario());
            }
            if(rd.getTipoBien().equals("Gastos de Viaje")){
                totalGV = totalGV.add(rd.getPrecioUnitario());
            }
            if(rd.getTipoBien().equals("Bien de Capital")){
                totalBU = totalBU.add(rd.getPrecioUnitario());
            }            
        }       
        lblTotalBC.setText("Bien Consumo $ " + totalBC);
        lblTotalBNP.setText("Serv. No Pers. $ " + totalBNP);
        lblTotalBU.setText("Bien Capital $ " + totalBU);
        lblTotalGV.setText("Gastos Viaje $ " + totalGV);
        lblTotalBC.setVisible(true);
        lblTotalBNP.setVisible(true);
        lblTotalBU.setVisible(true);
        lblTotalGV.setVisible(true);
    }
}
