/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * diagAltaRendicionDetalle.java
 *
 * Created on 14/08/2012, 19:12:59
 */
package vista.economico;

import entidades.economico.Rendicion;
import entidades.economico.RendicionDetalle;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author wbivanco
 */
public class diagAltaRendicionDetalle extends javax.swing.JDialog {
    List<RendicionDetalle> listaRendicionDetalle = new ArrayList<>();

    public List<RendicionDetalle> getListaRendicionDetalle() {
        return listaRendicionDetalle;
    }

    public void setListaRendicionDetalle(List<RendicionDetalle> listaRendicionDetalle) {
        this.listaRendicionDetalle = listaRendicionDetalle;
    }

    

    /** Creates new form diagAltaRendicionDetalle */
    public diagAltaRendicionDetalle(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        inicializarComponentes();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tfActaPatrimonial = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tfCantidad = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tfPrecio = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tfDetalle = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        dpFecha = new org.jdesktop.swingx.JXDatePicker();
        btnGuardar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taObservacion = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        tfNumeroComprobante = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tfProveedor = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        cmbTipoBien = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(org.openide.util.NbBundle.getMessage(diagAltaRendicionDetalle.class, "diagAltaRendicionDetalle.title")); // NOI18N

        jLabel1.setText(org.openide.util.NbBundle.getMessage(diagAltaRendicionDetalle.class, "diagAltaRendicionDetalle.jLabel1.text")); // NOI18N

        tfActaPatrimonial.setText(org.openide.util.NbBundle.getMessage(diagAltaRendicionDetalle.class, "diagAltaRendicionDetalle.tfActaPatrimonial.text")); // NOI18N

        jLabel2.setText(org.openide.util.NbBundle.getMessage(diagAltaRendicionDetalle.class, "diagAltaRendicionDetalle.jLabel2.text")); // NOI18N

        tfCantidad.setText(org.openide.util.NbBundle.getMessage(diagAltaRendicionDetalle.class, "diagAltaRendicionDetalle.tfCantidad.text")); // NOI18N

        jLabel3.setText(org.openide.util.NbBundle.getMessage(diagAltaRendicionDetalle.class, "diagAltaRendicionDetalle.jLabel3.text")); // NOI18N

        tfPrecio.setText(org.openide.util.NbBundle.getMessage(diagAltaRendicionDetalle.class, "diagAltaRendicionDetalle.tfPrecio.text")); // NOI18N

        jLabel4.setText(org.openide.util.NbBundle.getMessage(diagAltaRendicionDetalle.class, "diagAltaRendicionDetalle.jLabel4.text")); // NOI18N

        tfDetalle.setText(org.openide.util.NbBundle.getMessage(diagAltaRendicionDetalle.class, "diagAltaRendicionDetalle.tfDetalle.text")); // NOI18N

        jLabel5.setText(org.openide.util.NbBundle.getMessage(diagAltaRendicionDetalle.class, "diagAltaRendicionDetalle.jLabel5.text")); // NOI18N

        dpFecha.setFormats("dd/MM/yyyy");

        btnGuardar.setText(org.openide.util.NbBundle.getMessage(diagAltaRendicionDetalle.class, "diagAltaRendicionDetalle.btnGuardar.text")); // NOI18N
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        jLabel6.setText(org.openide.util.NbBundle.getMessage(diagAltaRendicionDetalle.class, "diagAltaRendicionDetalle.jLabel6.text")); // NOI18N

        taObservacion.setColumns(20);
        taObservacion.setRows(5);
        jScrollPane1.setViewportView(taObservacion);

        jLabel7.setText(org.openide.util.NbBundle.getMessage(diagAltaRendicionDetalle.class, "diagAltaRendicionDetalle.jLabel7.text")); // NOI18N

        tfNumeroComprobante.setText(org.openide.util.NbBundle.getMessage(diagAltaRendicionDetalle.class, "diagAltaRendicionDetalle.tfNumeroComprobante.text")); // NOI18N

        jLabel8.setText(org.openide.util.NbBundle.getMessage(diagAltaRendicionDetalle.class, "diagAltaRendicionDetalle.jLabel8.text")); // NOI18N

        tfProveedor.setText(org.openide.util.NbBundle.getMessage(diagAltaRendicionDetalle.class, "diagAltaRendicionDetalle.tfProveedor.text")); // NOI18N

        jLabel9.setText(org.openide.util.NbBundle.getMessage(diagAltaRendicionDetalle.class, "diagAltaRendicionDetalle.jLabel9.text")); // NOI18N

        cmbTipoBien.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Bien de Consumo", "Servicio No Personal", "Gastos de Viaje", "Bien de Capital" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnGuardar)
                .addGap(262, 262, 262))
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel4)
                                            .addGap(45, 45, 45))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(jLabel6)
                                            .addGap(18, 18, 18)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel3))
                                        .addGap(28, 28, 28)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 485, Short.MAX_VALUE)
                                    .addComponent(tfDetalle)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(tfPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(tfNumeroComprobante, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(tfProveedor)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cmbTipoBien, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(dpFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfActaPatrimonial, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(cmbTipoBien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(dpFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfActaPatrimonial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(tfCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel7)
                    .addComponent(tfNumeroComprobante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfDetalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tfProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addComponent(btnGuardar)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        guardarRendicionDetalle();
    }//GEN-LAST:event_btnGuardarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(diagAltaRendicionDetalle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(diagAltaRendicionDetalle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(diagAltaRendicionDetalle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(diagAltaRendicionDetalle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                diagAltaRendicionDetalle dialog = new diagAltaRendicionDetalle(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox cmbTipoBien;
    private org.jdesktop.swingx.JXDatePicker dpFecha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea taObservacion;
    private javax.swing.JTextField tfActaPatrimonial;
    private javax.swing.JTextField tfCantidad;
    private javax.swing.JTextField tfDetalle;
    private javax.swing.JTextField tfNumeroComprobante;
    private javax.swing.JTextField tfPrecio;
    private javax.swing.JTextField tfProveedor;
    // End of variables declaration//GEN-END:variables

    private void inicializarComponentes() {
        this.setLocationRelativeTo(null);
        getRootPane().setDefaultButton(btnGuardar);
        tfActaPatrimonial.requestFocus();
    }

    private void guardarRendicionDetalle() {
        validarCampos();
    }

    private void validarCampos() {
        boolean bandera = true;
        String error = "Error: \n";
        
       /*if(tfActaPatrimonial.getText().isEmpty()){
            bandera = false;
            error += "Debe ingresar un Número de Acta Patrimonial \n";
        }
        
        if(tfCantidad.getText().isEmpty()){
            bandera = false;
            error += "Debe ingresar una Cantidad \n";
        }
        
        if(tfDetalle.getText().isEmpty()){
            bandera = false;
            error += "Debe ingresar el Detalle \n";
        }
        
        if(tfPrecio.getText().isEmpty()){
            bandera = false;
            error += "Debe ingresar el Precio \n";
        }              
        
        if(dpFecha.getDate() == null){
            bandera = false;
            error += "Debe ingresar una Fecha de Compra \n";
        }*/
                
        if(bandera == false){
            JOptionPane.showMessageDialog(null, error);
        }else{
            guardarRegistro();
        }
    }

    private void guardarRegistro() {
        
        RendicionDetalle rendicionDetalle = new RendicionDetalle();
        int cantidad = 0;
        if(!tfCantidad.getText().isEmpty()){
            cantidad = Integer.parseInt(tfCantidad.getText());
        }            
        rendicionDetalle.setCantidadCompra(cantidad);        
        rendicionDetalle.setDetalle(tfDetalle.getText());
        rendicionDetalle.setFechaCompra(dpFecha.getDate());
        rendicionDetalle.setNumeroActaPatrimonial(tfActaPatrimonial.getText());
        rendicionDetalle.setNumeroComprobante(tfNumeroComprobante.getText());
        if(!tfPrecio.getText().equals("")){
            rendicionDetalle.setPrecioUnitario(new BigDecimal(tfPrecio.getText()));
        }else{
            rendicionDetalle.setPrecioUnitario(new BigDecimal("0"));
        }
        rendicionDetalle.setTipoBien(cmbTipoBien.getSelectedItem().toString());
        
        listaRendicionDetalle.add(rendicionDetalle);
        setListaRendicionDetalle(listaRendicionDetalle);
        
        JOptionPane.showMessageDialog(null, "Datos agregados");
        limpiarCampos();
        //setRendicionDetalle(rendicionDetalle);
        this.dispose();
    }

    private void limpiarCampos() {
        tfActaPatrimonial.setText("");
        tfCantidad.setText("");
        tfPrecio.setText("");
        tfDetalle.setText("");
        tfProveedor.setText("");
        tfNumeroComprobante.setText("");
        taObservacion.setText("");
        tfActaPatrimonial.requestFocus();
    }
}
