/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.economico;

import entidades.Documento;
import entidades.economico.ModificacionPresupuesto;
import java.awt.Desktop;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author Walter
 */
public class diagVerDetalleModificacionPrespuesto extends javax.swing.JDialog {
    
    private ModificacionPresupuesto modificacionPresupuesto = new ModificacionPresupuesto();

    public ModificacionPresupuesto getModificacionPresupuesto() {
        return modificacionPresupuesto;
    }

    public void setModificacionPresupuesto(ModificacionPresupuesto modificacionPresupuesto) {
        this.modificacionPresupuesto = modificacionPresupuesto;
    } 

    /**
     * Creates new form diagVerDetalleModificacionPrespuesto
     */
    public diagVerDetalleModificacionPrespuesto(java.awt.Frame parent, boolean modal, ModificacionPresupuesto modificacionPresupuesto) {
//    public diagVerDetalleModificacionPrespuesto(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setModificacionPresupuesto(modificacionPresupuesto);
        inicializarComponentes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tfBienConsumo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tfServicioNoPersonal = new javax.swing.JTextField();
        tfGastoViaje = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tfBienUso = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taObservacion = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        btnMostrarArchivo = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        tfAnioRendido = new javax.swing.JTextField();

        jLabel5.setText(org.openide.util.NbBundle.getMessage(diagVerDetalleModificacionPrespuesto.class, "diagVerDetalleModificacionPrespuesto.jLabel5.text")); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(diagVerDetalleModificacionPrespuesto.class, "diagVerDetalleModificacionPrespuesto.jPanel1.border.title"))); // NOI18N

        jLabel1.setText(org.openide.util.NbBundle.getMessage(diagVerDetalleModificacionPrespuesto.class, "diagVerDetalleModificacionPrespuesto.jLabel1.text")); // NOI18N

        tfBienConsumo.setText(org.openide.util.NbBundle.getMessage(diagVerDetalleModificacionPrespuesto.class, "diagVerDetalleModificacionPrespuesto.tfBienConsumo.text")); // NOI18N

        jLabel2.setText(org.openide.util.NbBundle.getMessage(diagVerDetalleModificacionPrespuesto.class, "diagVerDetalleModificacionPrespuesto.jLabel2.text")); // NOI18N

        jLabel3.setText(org.openide.util.NbBundle.getMessage(diagVerDetalleModificacionPrespuesto.class, "diagVerDetalleModificacionPrespuesto.jLabel3.text")); // NOI18N

        tfServicioNoPersonal.setText(org.openide.util.NbBundle.getMessage(diagVerDetalleModificacionPrespuesto.class, "diagVerDetalleModificacionPrespuesto.tfServicioNoPersonal.text")); // NOI18N

        tfGastoViaje.setText(org.openide.util.NbBundle.getMessage(diagVerDetalleModificacionPrespuesto.class, "diagVerDetalleModificacionPrespuesto.tfGastoViaje.text")); // NOI18N

        jLabel4.setText(org.openide.util.NbBundle.getMessage(diagVerDetalleModificacionPrespuesto.class, "diagVerDetalleModificacionPrespuesto.jLabel4.text")); // NOI18N

        tfBienUso.setText(org.openide.util.NbBundle.getMessage(diagVerDetalleModificacionPrespuesto.class, "diagVerDetalleModificacionPrespuesto.tfBienUso.text")); // NOI18N

        jLabel6.setText(org.openide.util.NbBundle.getMessage(diagVerDetalleModificacionPrespuesto.class, "diagVerDetalleModificacionPrespuesto.jLabel6.text")); // NOI18N

        taObservacion.setColumns(20);
        taObservacion.setRows(5);
        jScrollPane1.setViewportView(taObservacion);

        jLabel7.setText(org.openide.util.NbBundle.getMessage(diagVerDetalleModificacionPrespuesto.class, "diagVerDetalleModificacionPrespuesto.jLabel7.text")); // NOI18N

        btnMostrarArchivo.setText(org.openide.util.NbBundle.getMessage(diagVerDetalleModificacionPrespuesto.class, "diagVerDetalleModificacionPrespuesto.btnMostrarArchivo.text")); // NOI18N
        btnMostrarArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarArchivoActionPerformed(evt);
            }
        });

        jLabel8.setText(org.openide.util.NbBundle.getMessage(diagVerDetalleModificacionPrespuesto.class, "diagVerDetalleModificacionPrespuesto.jLabel8.text")); // NOI18N

        tfAnioRendido.setText(org.openide.util.NbBundle.getMessage(diagVerDetalleModificacionPrespuesto.class, "diagVerDetalleModificacionPrespuesto.tfAnioRendido.text")); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(233, 233, 233))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnMostrarArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfBienConsumo, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(tfGastoViaje, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                                .addComponent(tfServicioNoPersonal, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(tfBienUso, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfAnioRendido, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tfAnioRendido, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfBienConsumo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfServicioNoPersonal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfGastoViaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfBienUso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMostrarArchivo)
                    .addComponent(jLabel7))
                .addGap(35, 35, 35))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMostrarArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarArchivoActionPerformed
        verArchivo();
    }//GEN-LAST:event_btnMostrarArchivoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(diagVerDetalleModificacionPrespuesto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(diagVerDetalleModificacionPrespuesto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(diagVerDetalleModificacionPrespuesto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(diagVerDetalleModificacionPrespuesto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                diagVerDetalleModificacionPrespuesto dialog = new diagVerDetalleModificacionPrespuesto(new javax.swing.JFrame(), true, new ModificacionPresupuesto());
                //diagVerDetalleModificacionPrespuesto dialog = new diagVerDetalleModificacionPrespuesto(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMostrarArchivo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea taObservacion;
    private javax.swing.JTextField tfAnioRendido;
    private javax.swing.JTextField tfBienConsumo;
    private javax.swing.JTextField tfBienUso;
    private javax.swing.JTextField tfGastoViaje;
    private javax.swing.JTextField tfServicioNoPersonal;
    // End of variables declaration//GEN-END:variables

    private void inicializarComponentes() {
         this.setLocationRelativeTo(null);
         habilitarComponentes(false);
         cargarComponentes();
    }
    
    private void habilitarComponentes(boolean valor){
        tfAnioRendido.setEnabled(valor);
        tfBienConsumo.setEnabled(valor);
        tfBienUso.setEnabled(valor);
        tfGastoViaje.setEnabled(valor);
        tfServicioNoPersonal.setEnabled(valor);
        taObservacion.setEnabled(valor);
        if(getModificacionPresupuesto().getArchivoModificacion()!= null){
            btnMostrarArchivo.setEnabled(true);
        }else{
            btnMostrarArchivo.setEnabled(false);
        }
    }

    private void cargarComponentes() {
        tfAnioRendido.setText(String.valueOf(getModificacionPresupuesto().getAnioModificado()));
        tfBienConsumo.setText(String.valueOf(getModificacionPresupuesto().getMontoBC()));
        tfBienUso.setText(String.valueOf(getModificacionPresupuesto().getMontoBU()));
        tfGastoViaje.setText(String.valueOf(getModificacionPresupuesto().getMontoGV()));
        tfServicioNoPersonal.setText(String.valueOf(getModificacionPresupuesto().getMontoBNP()));
        taObservacion.setText(getModificacionPresupuesto().getObservacion());
    }

    private void verArchivo() {
        abrirArchivoResolucion(getModificacionPresupuesto().getArchivoModificacion());
    }

    private void abrirArchivoResolucion(Documento docuSeleccionado) {
        try {
            Documento documento = docuSeleccionado;
            byte[] archivoInterno = documento.getContenidoArchivo();
            File archivo = File.createTempFile("tmp", documento.getNombreArchivo());
            archivo.deleteOnExit();
            try (FileOutputStream fos = new FileOutputStream(archivo)) {
                fos.write(archivoInterno);
            }
            if (Desktop.isDesktopSupported() == true) {
                Desktop desktop = Desktop.getDesktop();
                try {
                    if (archivo.exists() == true) {
                        desktop.open(archivo);
                    } else {
                        JOptionPane.showMessageDialog(null, "No se encontrar el archivo: " + archivo.getAbsolutePath(), "Aviso", JOptionPane.WARNING_MESSAGE);
                    }
                } catch (IOException e) {
                }
            } else {
                JOptionPane.showMessageDialog(null, "No se puede ejecutar el comando de apertura en este sistema operativo", "Aviso", JOptionPane.WARNING_MESSAGE);
            }
        } catch (IOException ex) {
            Logger.getLogger(diagVerDetallePago.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    
}
