/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * diagInvestigadorBusquedaSimple.java
 *
 * Created on 05/06/2011, 17:55:57
 */
package vistas.personas;

import entidades.persona.DocumentoIdentidad;
import entidades.persona.Evaluador;
import entidades.persona.TipoDocumento;
import vista.*;
import entidades.persona.investigador.Investigador;
import entidades.proyecto.Proyecto;
import entidades.usuario.Usuario;
import facade.EvaluadorFacade;
import facade.InvestigadorFacade;
import facade.ProyectoFacade;
import facade.TipoDocumentoFacade;
import importador.diagInvestigador1;
import includes.Comunes;
import java.util.List;
import javax.swing.JOptionPane;
import org.apache.commons.validator.routines.LongValidator;
import vistas.evaluaciones.diagEvaluador;
import vistas.investigadores.diagInvestigador;

/**
 *
 * @author Carlos
 */
public class diagPersonaBusqueda extends javax.swing.JDialog {

    private String tipoPersona;
    private Investigador investigador;
    private Evaluador evaluador;
    private Usuario usuario;

    /** Creates new form diagInvestigadorBusquedaSimple */
    public diagPersonaBusqueda(java.awt.Frame parent, boolean modal, String tipoPersona, Usuario usuario) {
        super(parent, modal);
        this.tipoPersona = tipoPersona;
        this.usuario = usuario;
        initComponents();
        inicializarComponentes();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tfBusqueda = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(org.openide.util.NbBundle.getMessage(diagPersonaBusqueda.class, "diagProyectoBusquedaSimple.title")); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(diagPersonaBusqueda.class, "diagPersonaBusqueda.jPanel1.border.title"))); // NOI18N

        jLabel1.setText(org.openide.util.NbBundle.getMessage(diagPersonaBusqueda.class, "diagPersonaBusqueda.jLabel1.text")); // NOI18N

        tfBusqueda.setText(org.openide.util.NbBundle.getMessage(diagPersonaBusqueda.class, "diagPersonaBusqueda.tfBusqueda.text")); // NOI18N

        jButton1.setText(org.openide.util.NbBundle.getMessage(diagPersonaBusqueda.class, "diagPersonaBusqueda.jButton1.text")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setText(org.openide.util.NbBundle.getMessage(diagPersonaBusqueda.class, "diagPersonaBusqueda.jLabel3.text")); // NOI18N

        jLabel4.setText(org.openide.util.NbBundle.getMessage(diagPersonaBusqueda.class, "diagPersonaBusqueda.jLabel4.text")); // NOI18N

        jTextField1.setText(org.openide.util.NbBundle.getMessage(diagPersonaBusqueda.class, "diagPersonaBusqueda.jTextField1.text")); // NOI18N

        jButton4.setText(org.openide.util.NbBundle.getMessage(diagPersonaBusqueda.class, "diagPersonaBusqueda.jButton4.text")); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jButton4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setText(org.openide.util.NbBundle.getMessage(diagPersonaBusqueda.class, "diagPersonaBusqueda.jLabel2.text")); // NOI18N

        jScrollPane1.setViewportView(jList1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton2.setText(org.openide.util.NbBundle.getMessage(diagPersonaBusqueda.class, "diagPersonaBusqueda.jButton2.text")); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText(org.openide.util.NbBundle.getMessage(diagPersonaBusqueda.class, "diagPersonaBusqueda.jButton3.text")); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton5.setText(org.openide.util.NbBundle.getMessage(diagPersonaBusqueda.class, "diagPersonaBusqueda.jButton5.text")); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(70, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(61, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(144, 144, 144))
            .addGroup(layout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(244, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        buscarPorApellido();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        seleccionarPersona();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        buscarPorDocumentoIdentidad();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        agregarNuevaPersona();
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                diagPersonaBusqueda dialog = new diagPersonaBusqueda(new javax.swing.JFrame(), true, new String(), new Usuario());
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JList jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField tfBusqueda;
    // End of variables declaration//GEN-END:variables

    private void inicializarComponentes() {
        buscarPorApellido();
        cargarTiposDocumentos();
    }

    private void buscarInvestigadoresPorApellido() {
        Comunes.cargarJList(jList1, InvestigadorFacade.getInstance().buscarPorApellidoNombre(tfBusqueda.getText()));
    }

    private void buscarInvestigadoresPorDocumentoIdentidad() {
        Comunes.cargarJList(jList1, (List) InvestigadorFacade.getInstance().buscarPorDocumentoIdentidad(
                (TipoDocumento) jComboBox1.getSelectedItem(),
                Long.parseLong(jTextField1.getText())));
    }

    private void cargarTiposDocumentos() {
        Comunes.cargarJComboConBlanco(jComboBox1, TipoDocumentoFacade.getInstance().listarTodosTipoDocumento());
    }

    private void seleccionarPersona() {
        if (jList1.getSelectedIndex() != -1) {
            if (tipoPersona.equals("Investigador")) {
                investigador = (Investigador) jList1.getSelectedValue();
                this.dispose();
            } else if (tipoPersona.equals("Evaluador")) {
                evaluador = (Evaluador) jList1.getSelectedValue();
                this.dispose();
            }
        } else {
            JOptionPane.showMessageDialog(null, "Debe seleccionar una persona de la lista", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    public Investigador getInvestigador() {
        return investigador;
    }

    public Evaluador getEvaluador() {
        return evaluador;
    }

    private void agregarNuevaPersona() {
        if (tipoPersona.equals("Investigador")) {
            diagInvestigador investigadorAlta = new diagInvestigador(null, true, "Alta", usuario);
            investigadorAlta.setLocation(Comunes.centrarDialog(investigadorAlta));
            investigadorAlta.setVisible(true);
            if (investigadorAlta.getInvestigador() != null) {
                investigador = investigadorAlta.getInvestigador();
                this.dispose();
            }
        } else if (tipoPersona.equals("Evaluador")) {
            diagEvaluador evaluadorAlta = new diagEvaluador(null, true, "Alta");
            evaluadorAlta.setLocation(Comunes.centrarDialog(evaluadorAlta));
            evaluadorAlta.setVisible(true);
            if (evaluadorAlta.getEvaluador() != null) {
                evaluador = evaluadorAlta.getEvaluador();
                this.dispose();
            }
        }
    }

    private void buscarEvaluadoresPorApellido() {
        Comunes.cargarJList(jList1, EvaluadorFacade.getInstance().buscarPorApellidoNombre(tfBusqueda.getText()));
    }

    private void buscarPorApellido() {
        if (tipoPersona.equals("Investigador")) {
            buscarInvestigadoresPorApellido();
        } else if (tipoPersona.equals("Evaluador")) {
            buscarEvaluadoresPorApellido();
        }
    }

    private void buscarPorDocumentoIdentidad() {
        if (jComboBox1.getSelectedIndex() != -1
                && jComboBox1.getSelectedIndex() != 0) {
            if (LongValidator.getInstance().isValid(jTextField1.getText())) {
                if (tipoPersona.equals("Investigador")) {
                    buscarInvestigadoresPorDocumentoIdentidad();
                } else if (tipoPersona.equals("Evaluador")) {
                    buscarEvaluadoresPorDocumentoIdentidad();
                }
            } else {
                JOptionPane.showMessageDialog(null, "Numero de documento de identidad incorrecto", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Debe escoger un tipo de documento", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void buscarEvaluadoresPorDocumentoIdentidad() {
        Comunes.cargarJList(jList1, (List) EvaluadorFacade.getInstance().buscarPorDocumentoIdentidad(
                (TipoDocumento) jComboBox1.getSelectedItem(),
                Long.parseLong(jTextField1.getText())));
    }
}
