/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * diagDecretoAlta.java
 *
 * Created on 23/06/2011, 11:06:28
 */
package vista.proyectos.vinculacion.financiacion.pfip;

import vista.resoluciones.*;
import controladores.DocumentoJpaController;
import entidades.Documento;
import entidades.Resolucion;
import entidades.proyecto.vinculacion.financiacion.pfip.Etapa;
import facade.ConexionFacade;
import facade.DocumentoFacade;
import facade.EtapaFacade;
import facade.ResolucionFacade;
import includes.Comunes;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.nio.channels.FileChannel;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import org.apache.commons.validator.routines.IntegerValidator;

/**
 *
 * @author carlos
 */
public class diagSubirArchivo extends javax.swing.JDialog {

    private Resolucion resolucion;
    private String tipoOperacion;
    private Etapa etapa;
    private Documento documento;
    /**
     * Creates new form diagDecretoAlta
     */
    public diagSubirArchivo(java.awt.Frame parent, boolean modal, String tipoOperacion) {
        super(parent, modal);
        this.tipoOperacion = tipoOperacion;
        initComponents();
        inicializarComponentes();
    }
        public diagSubirArchivo(java.awt.Frame parent, boolean modal, String tipoOperacion, Etapa etapa) {
        super(parent, modal);
        this.tipoOperacion = tipoOperacion;
        this.etapa = etapa;
                System.out.println(tipoOperacion);

        initComponents();
        inicializarComponentes();
    }

//    public diagSubirArchivo(java.awt.Frame parent, boolean modal, String tipoOperacion, Resolucion resolucion) {
//        super(parent, modal);
//        this.tipoOperacion = tipoOperacion;
//        this.resolucion = resolucion;
//        initComponents();
//        inicializarComponentes();
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pnCargar = new javax.swing.JPanel();
        tfRutaCargaResolucion = new javax.swing.JTextField();
        btnEscogerArchivo = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taDescripcion = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Alta de Resolución");

        pnCargar.setBorder(javax.swing.BorderFactory.createTitledBorder("Cargar Archivo"));

        tfRutaCargaResolucion.setEditable(false);

        btnEscogerArchivo.setText("Cargar");
        btnEscogerArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEscogerArchivoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnCargarLayout = new javax.swing.GroupLayout(pnCargar);
        pnCargar.setLayout(pnCargarLayout);
        pnCargarLayout.setHorizontalGroup(
            pnCargarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnCargarLayout.createSequentialGroup()
                .addComponent(tfRutaCargaResolucion, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEscogerArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );
        pnCargarLayout.setVerticalGroup(
            pnCargarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnCargarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(tfRutaCargaResolucion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(btnEscogerArchivo))
        );

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        jLabel3.setText("Descripción");

        taDescripcion.setColumns(20);
        taDescripcion.setRows(5);
        jScrollPane1.setViewportView(taDescripcion);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pnCargar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(243, 243, 243)
                        .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1)))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnCargar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEscogerArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEscogerArchivoActionPerformed
        cargarResolucion();
}//GEN-LAST:event_btnEscogerArchivoActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        guardarArchivo();
}//GEN-LAST:event_btnGuardarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                diagSubirArchivo dialog = new diagSubirArchivo(new javax.swing.JFrame(), true, new String());
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEscogerArchivo;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnCargar;
    private javax.swing.JTextArea taDescripcion;
    private javax.swing.JTextField tfRutaCargaResolucion;
    // End of variables declaration//GEN-END:variables

    public Resolucion getResolucion() {
        return resolucion;
    }
    public Documento documento(){
        return documento;
    }
    private void inicializarComponentes() {
        switch (tipoOperacion) {
            case "Alta":
                establecerAnoActual();
                break;
            case "Modificación":
                taDescripcion.setText(resolucion.getDescripcion());
                break;
            case "Consulta":
                taDescripcion.setText(resolucion.getDescripcion());
                taDescripcion.setEditable(false);
                tfRutaCargaResolucion.setEditable(false);
                btnEscogerArchivo.setVisible(false);
                break;
        }
    }

    private void establecerAnoActual() {
        Date fechaActual = Comunes.obtenerFechaActualDesdeDB();
        Calendar calendario = Calendar.getInstance();
        calendario.setTime(fechaActual);
    }

    private void cargarResolucion() {
        JFileChooser fileChooser = new JFileChooser();
        int seleccion = fileChooser.showOpenDialog(null);
        if (seleccion == JFileChooser.APPROVE_OPTION) {
            File fichero = fileChooser.getSelectedFile();
            tfRutaCargaResolucion.setText(fichero.getAbsolutePath());
        }
    }

    private void guardarArchivo() {
        System.out.println("-guardar");

        if (validarDatos()) {
                    System.out.println("validarDatos");

            switch (tipoOperacion) {
                case "Alta": {
                    System.out.println("case alta");
                    File archivoEntrada = new File(tfRutaCargaResolucion.getText());
                    
                    System.out.println("File");
                    System.out.println(archivoEntrada);
                    if (longitudArchivoValida(archivoEntrada)) {
                        System.out.println("longitud valida");

                        InputStream is = null;
                        try {
                            Documento d = new Documento();
                            
                            d.setNombreArchivo(archivoEntrada.getName());
                            is = new FileInputStream(archivoEntrada);
                            byte[] buffer = new byte[(int) archivoEntrada.length()]; //creamos el buffer
                            is.read(buffer); //leemos el archivo al buffer
                            d.setContenidoArchivo(buffer);
                            //new DocumentoJpaController(Persistence.createEntityManagerFactory("ProyectoUnoPU", ConexionFacade.PROPIEDADES)).create(d);
                            new DocumentoFacade().alta(d);
                            documento = d;
                            System.out.println("doc creado");
                            List<Documento> docs = etapa.getDocumentos();
                            docs.add(d);
                            new EtapaFacade().modificar(etapa);
                                JOptionPane.showMessageDialog(null, "Su archivo  "
                                        + "se ha subido correctamente");

                            this.dispose();
                        } catch (FileNotFoundException ex) {
                            Logger.getLogger(diagSubirArchivo.class.getName()).log(Level.SEVERE, null, ex);
                        } catch (IOException ex) {
                            Logger.getLogger(diagSubirArchivo.class.getName()).log(Level.SEVERE, null, ex);
                        } finally {
                            try {
                                if (is != null) {
                                    is.close();
                                }
                            } catch (IOException ex) {
                                Logger.getLogger(diagSubirArchivo.class.getName()).log(Level.SEVERE, null, ex);
                            }
                        }
                    } else {
                        JOptionPane.showMessageDialog(null, "Archivo demasiado grande, debe ser menor a 5 MegaBytes");
                    }
                    break;
                }
                case "Modificación": {
//                    InputStream is = null;
//                    try {
////                        File archivoEntrada = new File(tfRutaCargaResolucion.getText());
////                        Documento d = new Documento();
////                        d.setNombreArchivo(archivoEntrada.getName());
////                        is = new FileInputStream(archivoEntrada);
////                        byte[] buffer = new byte[(int) archivoEntrada.length()]; //creamos el buffer
////                        is.read(buffer); //leemos el archivo al buffer
////                        d.setContenidoArchivo(buffer);
////                        new DocumentoJpaController(Persistence.createEntityManagerFactory("ProyectoUnoPU", ConexionFacade.PROPIEDADES)).create(d);
////                        resolucion.setAno((Integer) spnAnio.getValue());
////                        resolucion.setDescripcion(taDescripcion.getText());
////                        resolucion.setNumero(Long.parseLong(tfNumeroResolucion.getText()));
////                        resolucion.setDocumento(d);
////                        new ResolucionFacade().modificar(resolucion);
////                        JOptionPane.showMessageDialog(null, "La modificación de la Resolución "
////                                + "se ha realizado correctamente");
//                        this.dispose();
//                        break;
//                    } catch (FileNotFoundException ex) {
//                        Logger.getLogger(diagSubirArchivo.class.getName()).log(Level.SEVERE, null, ex);
//                    } catch (IOException ex) {
//                        Logger.getLogger(diagSubirArchivo.class.getName()).log(Level.SEVERE, null, ex);
//                    } finally {
//                        try {
//                            if (is != null) {
//                                is.close();
//                            }
//                        } catch (IOException ex) {
//                            Logger.getLogger(diagSubirArchivo.class.getName()).log(Level.SEVERE, null, ex);
//                        }
//                    }
                }
                case "Consulta":
                    this.dispose();
                    break;
            }

        }
        else{
             JOptionPane.showMessageDialog(null, "Datos no válidos");

        }
    }

    private boolean validarDatos() {
        boolean flag = false;
        if (!taDescripcion.getText().isEmpty()) {
            if (!tfRutaCargaResolucion.getText().equals("")) {
                flag = true;
            } else {
                JOptionPane.showMessageDialog(null, "Debe escoger un archivo de entrada",
                        "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Debe ingresar una descripción",
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
        return flag;
    }

    private boolean longitudArchivoValida(File archivoEntrada) {
        // Get length of file in bytes
        long fileSizeInBytes = archivoEntrada.length();
        // Convert the bytes to Kilobytes (1 KB = 1024 Bytes)
        long fileSizeInKB = fileSizeInBytes / 1024;
        // Convert the KB to MegaBytes (1 MB = 1024 KBytes)
        long fileSizeInMB = fileSizeInKB / 1024;
        return fileSizeInMB < 5;

    }
}
