/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.proyectos.vinculacion.financiacion.pfip;

import entidades.proyecto.vinculacion.financiacion.pfip.Etapa;
import includes.Comunes;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import org.apache.commons.validator.routines.FloatValidator;
import org.apache.commons.validator.routines.IntegerValidator;

/**
 *
 * @author Panchi
 */
public class diagEtapa extends javax.swing.JDialog {

    private Etapa etapaCreada;
    private List<Etapa> etapas = new ArrayList<Etapa>();
    private String operacion;

    /**
     * Creates new form diagEtapa
     */
    public diagEtapa(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public diagEtapa(java.awt.Frame parent, boolean modal, List<Etapa> etapas, String operacion) {
        super(parent, modal);
        this.operacion = operacion;
        initComponents();
        this.etapas = etapas;
        cargarNroEtapa();
        inicializarComponentes();
    }

    public diagEtapa(java.awt.Frame parent, boolean modal, Etapa etapa, String operacion) {
        super(parent, modal);
        initComponents();
        this.operacion = operacion;
        this.etapaCreada = etapa;
        inicializarComponentes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtfNroEtapa = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        taObservaciones = new javax.swing.JTextArea();
        jLabel16 = new javax.swing.JLabel();
        jxFechaInicio = new org.jdesktop.swingx.JXDatePicker();
        jxFechaFin = new org.jdesktop.swingx.JXDatePicker();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jtfbcfc = new javax.swing.JTextField();
        jtfrechfc = new javax.swing.JTextField();
        jtfconsulfc = new javax.swing.JTextField();
        jtfmatfc = new javax.swing.JTextField();
        jtfotrofc = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jtftotalfc = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jtfbiendecapfm = new javax.swing.JTextField();
        jtfrechfm = new javax.swing.JTextField();
        jtfconsulfm = new javax.swing.JTextField();
        jtfmatfm = new javax.swing.JTextField();
        jtfotrosfm = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jtftotalfm = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(diagEtapa.class, "diagEtapa.jPanel1.border.title"))); // NOI18N

        jLabel1.setText(org.openide.util.NbBundle.getMessage(diagEtapa.class, "diagEtapa.jLabel1.text")); // NOI18N

        jLabel2.setText(org.openide.util.NbBundle.getMessage(diagEtapa.class, "diagEtapa.jLabel2.text")); // NOI18N

        jLabel3.setText(org.openide.util.NbBundle.getMessage(diagEtapa.class, "diagEtapa.jLabel3.text")); // NOI18N

        jtfNroEtapa.setText(org.openide.util.NbBundle.getMessage(diagEtapa.class, "diagEtapa.jtfNroEtapa.text")); // NOI18N

        taObservaciones.setColumns(20);
        taObservaciones.setRows(5);
        jScrollPane1.setViewportView(taObservaciones);

        jLabel16.setText(org.openide.util.NbBundle.getMessage(diagEtapa.class, "diagEtapa.jLabel16.text")); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane1)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3))
                            .addGap(22, 22, 22)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jtfNroEtapa, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                                .addComponent(jxFechaInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jxFechaFin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addComponent(jLabel16))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtfNroEtapa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jxFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jxFechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(diagEtapa.class, "diagEtapa.jPanel2.border.title"))); // NOI18N

        jLabel4.setText(org.openide.util.NbBundle.getMessage(diagEtapa.class, "diagEtapa.jLabel4.text")); // NOI18N

        jLabel5.setText(org.openide.util.NbBundle.getMessage(diagEtapa.class, "diagEtapa.jLabel5.text")); // NOI18N

        jLabel6.setText(org.openide.util.NbBundle.getMessage(diagEtapa.class, "diagEtapa.jLabel6.text")); // NOI18N

        jLabel7.setText(org.openide.util.NbBundle.getMessage(diagEtapa.class, "diagEtapa.jLabel7.text")); // NOI18N

        jLabel8.setText(org.openide.util.NbBundle.getMessage(diagEtapa.class, "diagEtapa.jLabel8.text")); // NOI18N

        jtfbcfc.setText(org.openide.util.NbBundle.getMessage(diagEtapa.class, "diagEtapa.jtfbcfc.text")); // NOI18N
        jtfbcfc.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtfbcfcFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfbcfcFocusLost(evt);
            }
        });

        jtfrechfc.setText(org.openide.util.NbBundle.getMessage(diagEtapa.class, "diagEtapa.jtfrechfc.text")); // NOI18N
        jtfrechfc.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtfrechfcFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfrechfcFocusLost(evt);
            }
        });

        jtfconsulfc.setText(org.openide.util.NbBundle.getMessage(diagEtapa.class, "diagEtapa.jtfconsulfc.text")); // NOI18N
        jtfconsulfc.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtfconsulfcFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfconsulfcFocusLost(evt);
            }
        });

        jtfmatfc.setText(org.openide.util.NbBundle.getMessage(diagEtapa.class, "diagEtapa.jtfmatfc.text")); // NOI18N
        jtfmatfc.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtfmatfcFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfmatfcFocusLost(evt);
            }
        });

        jtfotrofc.setText(org.openide.util.NbBundle.getMessage(diagEtapa.class, "diagEtapa.jtfotrofc.text")); // NOI18N
        jtfotrofc.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtfotrofcFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfotrofcFocusLost(evt);
            }
        });

        jLabel9.setText(org.openide.util.NbBundle.getMessage(diagEtapa.class, "diagEtapa.jLabel9.text")); // NOI18N

        jtftotalfc.setText(org.openide.util.NbBundle.getMessage(diagEtapa.class, "diagEtapa.jtftotalfc.text")); // NOI18N
        jtftotalfc.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtftotalfcFocusGained(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtftotalfc, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfotrofc, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfconsulfc, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfrechfc, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfbcfc, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfmatfc, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtfbcfc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfrechfc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfconsulfc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfmatfc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(13, 13, 13)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfotrofc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9)
                    .addComponent(jtftotalfc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jButton1.setText(org.openide.util.NbBundle.getMessage(diagEtapa.class, "diagEtapa.jButton1.text")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText(org.openide.util.NbBundle.getMessage(diagEtapa.class, "diagEtapa.jButton2.text")); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(diagEtapa.class, "diagEtapa.jPanel4.border.title"))); // NOI18N

        jLabel10.setText(org.openide.util.NbBundle.getMessage(diagEtapa.class, "diagEtapa.jLabel10.text")); // NOI18N

        jLabel11.setText(org.openide.util.NbBundle.getMessage(diagEtapa.class, "diagEtapa.jLabel11.text")); // NOI18N

        jLabel12.setText(org.openide.util.NbBundle.getMessage(diagEtapa.class, "diagEtapa.jLabel12.text")); // NOI18N

        jLabel13.setText(org.openide.util.NbBundle.getMessage(diagEtapa.class, "diagEtapa.jLabel13.text")); // NOI18N

        jLabel14.setText(org.openide.util.NbBundle.getMessage(diagEtapa.class, "diagEtapa.jLabel14.text")); // NOI18N

        jtfbiendecapfm.setText(org.openide.util.NbBundle.getMessage(diagEtapa.class, "diagEtapa.jtfbiendecapfm.text")); // NOI18N
        jtfbiendecapfm.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtfbiendecapfmFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfbiendecapfmFocusLost(evt);
            }
        });

        jtfrechfm.setText(org.openide.util.NbBundle.getMessage(diagEtapa.class, "diagEtapa.jtfrechfm.text")); // NOI18N
        jtfrechfm.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtfrechfmFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfrechfmFocusLost(evt);
            }
        });

        jtfconsulfm.setText(org.openide.util.NbBundle.getMessage(diagEtapa.class, "diagEtapa.jtfconsulfm.text")); // NOI18N
        jtfconsulfm.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtfconsulfmFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfconsulfmFocusLost(evt);
            }
        });

        jtfmatfm.setText(org.openide.util.NbBundle.getMessage(diagEtapa.class, "diagEtapa.jtfmatfm.text")); // NOI18N
        jtfmatfm.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtfmatfmFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfmatfmFocusLost(evt);
            }
        });

        jtfotrosfm.setText(org.openide.util.NbBundle.getMessage(diagEtapa.class, "diagEtapa.jtfotrosfm.text")); // NOI18N
        jtfotrosfm.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtfotrosfmFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfotrosfmFocusLost(evt);
            }
        });

        jLabel15.setText(org.openide.util.NbBundle.getMessage(diagEtapa.class, "diagEtapa.jLabel15.text")); // NOI18N

        jtftotalfm.setText(org.openide.util.NbBundle.getMessage(diagEtapa.class, "diagEtapa.jtftotalfm.text")); // NOI18N
        jtftotalfm.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtftotalfmFocusGained(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtftotalfm, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfotrosfm, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfconsulfm, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfrechfm, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfbiendecapfm, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfmatfm, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jtfbiendecapfm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfrechfm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfconsulfm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfmatfm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(8, 8, 8)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfotrosfm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel15)
                    .addComponent(jtftotalfm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton2))
                        .addGap(40, 40, 40))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(79, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        aceptar();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jtfbcfcFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfbcfcFocusLost
        cambiarTotalContraparte();        // TODO add your handling code here:
    }//GEN-LAST:event_jtfbcfcFocusLost

    private void jtfrechfcFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfrechfcFocusLost
        cambiarTotalContraparte();        // TODO add your handling code here:
    }//GEN-LAST:event_jtfrechfcFocusLost

    private void jtfconsulfcFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfconsulfcFocusLost
        cambiarTotalContraparte();        // TODO add your handling code here:
    }//GEN-LAST:event_jtfconsulfcFocusLost

    private void jtfmatfcFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfmatfcFocusLost
        cambiarTotalContraparte();        // TODO add your handling code here:
    }//GEN-LAST:event_jtfmatfcFocusLost

    private void jtfotrofcFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfotrofcFocusLost
        cambiarTotalContraparte();        // TODO add your handling code here:
    }//GEN-LAST:event_jtfotrofcFocusLost

    private void jtftotalfcFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtftotalfcFocusGained
        cambiarTotalContraparte();        // TODO add your handling code here:
    }//GEN-LAST:event_jtftotalfcFocusGained

    private void jtfbiendecapfmFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfbiendecapfmFocusLost
        cambiarTotalMincyt();        // TODO add your handling code here:
    }//GEN-LAST:event_jtfbiendecapfmFocusLost

    private void jtfrechfmFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfrechfmFocusLost
        cambiarTotalMincyt();        // TODO add your handling code here:
    }//GEN-LAST:event_jtfrechfmFocusLost

    private void jtfconsulfmFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfconsulfmFocusLost
        cambiarTotalMincyt();        // TODO add your handling code here:
    }//GEN-LAST:event_jtfconsulfmFocusLost

    private void jtfmatfmFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfmatfmFocusLost
        cambiarTotalMincyt();        // TODO add your handling code here:
    }//GEN-LAST:event_jtfmatfmFocusLost

    private void jtfotrosfmFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfotrosfmFocusLost
        cambiarTotalMincyt();        // TODO add your handling code here:
    }//GEN-LAST:event_jtfotrosfmFocusLost

    private void jtftotalfmFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtftotalfmFocusGained
        cambiarTotalMincyt();        // TODO add your handling code here:
    }//GEN-LAST:event_jtftotalfmFocusGained

    private void jtfbcfcFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfbcfcFocusGained
        seleccionarTextoTextField(jtfbcfc);        // TODO add your handling code here:
    }//GEN-LAST:event_jtfbcfcFocusGained

    private void jtfrechfcFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfrechfcFocusGained
        seleccionarTextoTextField(jtfrechfc);        // TODO add your handling code here:
    }//GEN-LAST:event_jtfrechfcFocusGained

    private void jtfconsulfcFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfconsulfcFocusGained
        seleccionarTextoTextField(jtfconsulfc);// TODO add your handling code here:
    }//GEN-LAST:event_jtfconsulfcFocusGained

    private void jtfmatfcFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfmatfcFocusGained
        seleccionarTextoTextField(jtfmatfc);
    }//GEN-LAST:event_jtfmatfcFocusGained

    private void jtfotrofcFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfotrofcFocusGained
        seleccionarTextoTextField(jtfotrofc);        // TODO add your handling code here:
    }//GEN-LAST:event_jtfotrofcFocusGained

    private void jtfbiendecapfmFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfbiendecapfmFocusGained
        seleccionarTextoTextField(jtfbiendecapfm);        // TODO add your handling code here:
    }//GEN-LAST:event_jtfbiendecapfmFocusGained

    private void jtfrechfmFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfrechfmFocusGained
        seleccionarTextoTextField(jtfrechfm);        // TODO add your handling code here:
    }//GEN-LAST:event_jtfrechfmFocusGained

    private void jtfconsulfmFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfconsulfmFocusGained
        seleccionarTextoTextField(jtfconsulfm);        // TODO add your handling code here:
    }//GEN-LAST:event_jtfconsulfmFocusGained

    private void jtfmatfmFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfmatfmFocusGained
        seleccionarTextoTextField(jtfmatfm);        // TODO add your handling code here:
    }//GEN-LAST:event_jtfmatfmFocusGained

    private void jtfotrosfmFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfotrosfmFocusGained
        seleccionarTextoTextField(jtfotrosfm);        // TODO add your handling code here:
    }//GEN-LAST:event_jtfotrosfmFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(diagEtapa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(diagEtapa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(diagEtapa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(diagEtapa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the dialog
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                diagEtapa dialog = new diagEtapa(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jtfNroEtapa;
    private javax.swing.JTextField jtfbcfc;
    private javax.swing.JTextField jtfbiendecapfm;
    private javax.swing.JTextField jtfconsulfc;
    private javax.swing.JTextField jtfconsulfm;
    private javax.swing.JTextField jtfmatfc;
    private javax.swing.JTextField jtfmatfm;
    private javax.swing.JTextField jtfotrofc;
    private javax.swing.JTextField jtfotrosfm;
    private javax.swing.JTextField jtfrechfc;
    private javax.swing.JTextField jtfrechfm;
    private javax.swing.JTextField jtftotalfc;
    private javax.swing.JTextField jtftotalfm;
    private org.jdesktop.swingx.JXDatePicker jxFechaFin;
    private org.jdesktop.swingx.JXDatePicker jxFechaInicio;
    private javax.swing.JTextArea taObservaciones;
    // End of variables declaration//GEN-END:variables

    public Etapa getCampoEtapa() {
        return etapaCreada;
    }

    private void cargarNroEtapa() {
        if (etapas.isEmpty()) {
            jtfNroEtapa.setText("1");
        } else {
            jtfNroEtapa.setText(Integer.toString(etapas.size() + 1));

        }

    }
//
//    private Integer calcularNroEtapa() {
//       Integer proxEtapa = null;
//        for(Etapa e: etapas){
//           proxEtapa = e.getNroEtapa();
//       }
//      return  proxEtapa++;
//    }

    private void aceptar() {
        if (validar()) {
            switch (operacion) {
                case "Alta":

                    etapaCreada = new Etapa();
                    cargarDatos();


                    this.dispose();
                    break;
                case "Modificacion":
                    cargarDatos();
                    this.dispose();
                    break;
            }
        }
    }

    public boolean validar() {
        boolean flag = false;

        //panel de etapas
        if (!jtfNroEtapa.getText().isEmpty()
                && IntegerValidator.getInstance().isValid(jtfNroEtapa.getText())) {
        if (jxFechaInicio.getDate() != null) {
             if (jxFechaFin.getDate() != null) {


                    //panel de financiamiento contraparte
                    if (!jtfbcfc.getText().isEmpty()) {
                        //&& FloatValidator.getInstance().isValid(jtfbcfc.getText())) {
                        if (!jtfrechfc.getText().isEmpty()) {
                            //  && FloatValidator.getInstance().isValid(jtfrechfc.getText())) {
                            if (!jtfconsulfc.getText().isEmpty()) {
                                //    && FloatValidator.getInstance().isValid(jtfconsulfc.getText())) {

                                if (!jtfmatfc.getText().isEmpty()) {
                                    //      && FloatValidator.getInstance().isValid(jtfmatfc.getText())) {
                                    if (!jtfotrofc.getText().isEmpty()) {
                                        //        && FloatValidator.getInstance().isValid(jtfotrofc.getText())) {


                                        //panel de financiamiento por mincyt
                                        if (!jtfbiendecapfm.getText().isEmpty()) {
                                            //          && FloatValidator.getInstance().isValid(jtfbiendecapfm.getText())) {
                                            if (!jtfrechfm.getText().isEmpty()) {
//                                                    && FloatValidator.getInstance().isValid(jtfrechfm.getText())) {
                                                if (!jtfconsulfm.getText().isEmpty()) {
                                                    //                                                      && FloatValidator.getInstance().isValid(jtfconsulfm.getText())) {

                                                    if (!jtfmatfm.getText().isEmpty()) {
//                                                            && FloatValidator.getInstance().isValid(jtfmatfm.getText())) {
                                                        if (!jtfotrosfm.getText().isEmpty()) {
                                                            //                                                              && FloatValidator.getInstance().isValid(jtfotrosfm.getText())) {

                                                            flag = true;

                                                        } else {
                                                            JOptionPane.showMessageDialog(null, "Valor de otros recursos a financiar por Mincyt incorrecto",
                                                                    "Error", JOptionPane.ERROR_MESSAGE);
                                                        }
                                                    } else {
                                                        JOptionPane.showMessageDialog(null, "Valor de materiales a financiar por Mincyt incorrecto",
                                                                "Error", JOptionPane.ERROR_MESSAGE);
                                                    }
                                                } else {
                                                    JOptionPane.showMessageDialog(null, "Valor de consultorías a financiar por Mincyt incorrecto",
                                                            "Error", JOptionPane.ERROR_MESSAGE);
                                                }
                                            } else {
                                                JOptionPane.showMessageDialog(null, "Valor de recursos humanos a financiar por Mincyt incorrecto",
                                                        "Error", JOptionPane.ERROR_MESSAGE);
                                            }

                                        } else {
                                            JOptionPane.showMessageDialog(null, "Valor de bienes de capital a financiar por Mincyt incorrecto",
                                                    "Error", JOptionPane.ERROR_MESSAGE);
                                        }
                                    } else {
                                        JOptionPane.showMessageDialog(null, "Valor de otros recursos a financiar por contraparte incorrecto",
                                                "Error", JOptionPane.ERROR_MESSAGE);
                                    }
                                } else {
                                    JOptionPane.showMessageDialog(null, "Valor de materiales a financiar por contraparte incorrecto",
                                            "Error", JOptionPane.ERROR_MESSAGE);
                                }
                            } else {
                                JOptionPane.showMessageDialog(null, "Valor de consultorías a financiar por contraparte incorrecto",
                                        "Error", JOptionPane.ERROR_MESSAGE);
                            }
                        } else {
                            JOptionPane.showMessageDialog(null, "Valor de recursos humanos a financiar por contraparte incorrecto",
                                    "Error", JOptionPane.ERROR_MESSAGE);
                        }

                    } else {
                        JOptionPane.showMessageDialog(null, "Valor de bienes de capital a financiar por contraparte incorrecto",
                                "Error", JOptionPane.ERROR_MESSAGE);
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Valor de mes de fin incorrecto",
                            "Error", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(null, "Valor de mes de inicio incorrecto",
                        "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Número de etapa incorrecto",
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
        return flag;





    }

    private void inicializarComponentes() {
        jxFechaInicio.setFormats(new SimpleDateFormat("dd/MM/yyyy"));
        jxFechaFin.setFormats(new SimpleDateFormat("dd/MM/yyyy"));
        switch (operacion) {
            case "Alta":
                setearTextField();


                break;
            case "Modificacion":
                jxFechaInicio.setDate(etapaCreada.getFechaInicio());
               jxFechaFin.setDate(etapaCreada.getFechaFin());
                jtfNroEtapa.setText(etapaCreada.getNroEtapa().toString());
                taObservaciones.setText(etapaCreada.getObservaciones());
                
                if (etapaCreada.getBienCapitalFC() != null) {
                    jtfbcfc.setText(etapaCreada.getBienCapitalFC().toString());
                } else {
                    jtfbcfc.setText("0.0");
                }
                if (etapaCreada.getBienCapitalFM() != null) {
                    jtfbiendecapfm.setText(etapaCreada.getBienCapitalFM().toString());
                } else {
                    jtfbiendecapfm.setText("0.0");
                }
                if (etapaCreada.getConsultoriasFC() != null) {
                    jtfconsulfc.setText(etapaCreada.getConsultoriasFC().toString());
                } else {
                    jtfconsulfc.setText("0.0");
                }

                if (etapaCreada.getConsultoriasFM() != null) {
                    jtfconsulfm.setText(etapaCreada.getConsultoriasFM().toString());
                } else {
                    jtfconsulfm.setText("0.0");
                }

                if (etapaCreada.getMaterialesFC() != null) {
                    jtfmatfc.setText(etapaCreada.getMaterialesFC().toString());
                } else {
                    jtfmatfc.setText("0.0");
                }

                if (etapaCreada.getMaterialesFM() != null) {
                    jtfmatfm.setText(etapaCreada.getMaterialesFM().toString());
                } else {
                    jtfmatfm.setText("0.0");
                }

                if (etapaCreada.getOtrosRecursosFC() != null) {
                    jtfotrofc.setText(etapaCreada.getOtrosRecursosFC().toString());
                } else {
                    jtfotrofc.setText("0.0");
                }

                if (etapaCreada.getOtrosRecursosFM() != null) {
                    jtfotrosfm.setText(etapaCreada.getOtrosRecursosFM().toString());
                } else {
                    jtfotrosfm.setText("0.0");
                }

                if (etapaCreada.getRecHumFC() != null) {
                    jtfrechfc.setText(etapaCreada.getRecHumFC().toString());
                } else {
                    jtfrechfc.setText("0.0");
                }

                if (etapaCreada.getRecHumFM() != null) {
                    jtfrechfm.setText(etapaCreada.getRecHumFM().toString());
                } else {
                    jtfrechfm.setText("0.0");
                }
                cambiarTotalContraparte();
                cambiarTotalMincyt();
                break;
        }
    }

    private void setearTextField() {
        jtfbcfc.setText("0.0");
        jtfconsulfc.setText("0.0");
        jtfmatfc.setText("0.0");
        jtfotrofc.setText("0.0");
        jtfrechfc.setText("0.0");
        jtftotalfc.setText("0.0");
        jtfbiendecapfm.setText("0.0");
        jtfconsulfm.setText("0.0");
        jtfmatfm.setText("0.0");
        jtfotrosfm.setText("0.0");
        jtfrechfm.setText("0.0");
        jtftotalfm.setText("0.0");

    }

    private void cargarDatos() {
        etapaCreada.setNroEtapa(Integer.parseInt(jtfNroEtapa.getText()));
        etapaCreada.setFechaInicio(jxFechaInicio.getDate());
        etapaCreada.setFechaFin(jxFechaFin.getDate());
        etapaCreada.setObservaciones(taObservaciones.getText());
        try {
            etapaCreada.setBienCapitalFM(Float.valueOf(jtfbiendecapfm.getText()));
            etapaCreada.setConsultoriasFM(Float.valueOf(jtfconsulfm.getText()));
            etapaCreada.setMaterialesFM(Float.valueOf(jtfmatfm.getText()));
            etapaCreada.setOtrosRecursosFM(Float.valueOf(jtfotrosfm.getText()));
            etapaCreada.setRecHumFM(Float.valueOf(jtfrechfm.getText()));
            etapaCreada.setBienCapitalFC(Float.valueOf(jtfbcfc.getText()));
            etapaCreada.setConsultoriasFC(Float.valueOf(jtfconsulfc.getText()));
            etapaCreada.setMaterialesFC(Float.valueOf(jtfmatfc.getText()));
            etapaCreada.setOtrosRecursosFC(Float.valueOf(jtfotrofc.getText()));
            etapaCreada.setRecHumFC(Float.valueOf(jtfrechfc.getText()));
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Numeros mal formados", "Error", JOptionPane.ERROR_MESSAGE);

        }
    }

    private void cambiarTotalContraparte() {
        jtftotalfc.setText(calcularTotalContraparte().toString());
    }

    private Float calcularTotalContraparte() {
        float total = 0;
        float total2 = 0;
//        try {
            total = Float.valueOf(jtfbcfc.getText())
                    + Float.valueOf(jtfconsulfc.getText())
                    + Float.valueOf(jtfmatfc.getText())
                    + Float.valueOf(jtfotrofc.getText())
                    + Float.valueOf(jtfrechfc.getText());
     
//        } catch (NumberFormatException e) {
//            JOptionPane.showMessageDialog(null, "Numeros mal formados", "Error", JOptionPane.ERROR_MESSAGE);
//
//        }

        return total;
    }

    private void cambiarTotalMincyt() {
        jtftotalfm.setText(calcularTotalMincyt().toString());
    }

    private Float calcularTotalMincyt() {
        float total = 0;
//        try {
            total = Float.valueOf(jtfbiendecapfm.getText())
                    + Float.valueOf(jtfconsulfm.getText())
                    + Float.valueOf(jtfmatfm.getText())
                    + Float.valueOf(jtfotrosfm.getText())
                    + Float.valueOf(jtfrechfm.getText());
//        } catch (NumberFormatException e) {
//            JOptionPane.showMessageDialog(null, "Numeros mal formados", "Error", JOptionPane.ERROR_MESSAGE);
//
//        }

        return total;
    }

    private void seleccionarTextoTextField(JTextField jtf) {
        jtf.setSelectionStart(0);
        jtf.setSelectionEnd(jtf.getText().length());
    }
}
