/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * diagInvestigadorBusqueda.java
 *
 * Created on 16/11/2011, 10:24:07
 */
package vista.categorizacion;

import entidades.categorizacion.Categorizacion;
import entidades.operaciones.Operacion;
import entidades.persona.investigador.Investigador;
import entidades.usuario.Usuario;
import facade.InvestigadorFacade;
import facade.OperacionFacade;
import includes.Comunes;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import org.apache.commons.validator.routines.LongValidator;
import vistas.investigadores.diagInvestigador;

/**
 *
 * @author wbivanco
 */
public class diagInvestigadorBusqueda extends javax.swing.JDialog {

    public static Investigador investigadorSeleccionado;
    public static Categorizacion categoriaSeleccionada;
    private Usuario usuario;

    public Investigador getInvestigadorSeleccionado() {
        return investigadorSeleccionado;
    }

    public void setInvestigadorSeleccionado(Investigador investigadorSeleccionado) {
        this.investigadorSeleccionado = investigadorSeleccionado;
    }

    public static Categorizacion getCategoriaSeleccionada() {
        return categoriaSeleccionada;
    }

    public static void setCategoriaSeleccionada(Categorizacion categoriaSeleccionada) {
        diagInvestigadorBusqueda.categoriaSeleccionada = categoriaSeleccionada;
    }

    /**
     * Creates new form diagInvestigadorBusqueda
     */
    public diagInvestigadorBusqueda(java.awt.Frame parent, boolean modal, Usuario usuario) {
        super(parent, modal);
        initComponents();
        this.usuario = usuario;
        inicializarComponentes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cmbTipo = new javax.swing.JComboBox();
        tfTValor = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        btnAgregarInvestigador = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstDatos = new javax.swing.JList();
        btnCategorizacion = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstCategorizaciones = new javax.swing.JList();
        btnEliminarCategorizacion = new javax.swing.JButton();
        btnModifiicacionCategorizacion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(org.openide.util.NbBundle.getMessage(diagInvestigadorBusqueda.class, "diagInvestigadorBusqueda.title")); // NOI18N
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(diagInvestigadorBusqueda.class, "diagInvestigadorBusqueda.jPanel1.border.title"))); // NOI18N

        cmbTipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Apellido", "DNI" }));
        cmbTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTipoActionPerformed(evt);
            }
        });

        tfTValor.setText(org.openide.util.NbBundle.getMessage(diagInvestigadorBusqueda.class, "diagInvestigadorBusqueda.tfTValor.text")); // NOI18N
        tfTValor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tfTValorMouseClicked(evt);
            }
        });

        btnBuscar.setText(org.openide.util.NbBundle.getMessage(diagInvestigadorBusqueda.class, "diagInvestigadorBusqueda.btnBuscar.text")); // NOI18N
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnAgregarInvestigador.setText(org.openide.util.NbBundle.getMessage(diagInvestigadorBusqueda.class, "diagInvestigadorBusqueda.btnAgregarInvestigador.text")); // NOI18N
        btnAgregarInvestigador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarInvestigadorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cmbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfTValor, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBuscar)
                .addGap(66, 66, 66)
                .addComponent(btnAgregarInvestigador, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfTValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar)
                    .addComponent(btnAgregarInvestigador))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(diagInvestigadorBusqueda.class, "diagInvestigadorBusqueda.jPanel2.border.title"))); // NOI18N

        lstDatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstDatosMouseClicked(evt);
            }
        });
        lstDatos.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstDatosValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lstDatos);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnCategorizacion.setText(org.openide.util.NbBundle.getMessage(diagInvestigadorBusqueda.class, "diagInvestigadorBusqueda.btnCategorizacion.text")); // NOI18N
        btnCategorizacion.setEnabled(false);
        btnCategorizacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCategorizacionActionPerformed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(diagInvestigadorBusqueda.class, "diagInvestigadorBusqueda.jPanel3.border.title"))); // NOI18N

        lstCategorizaciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstCategorizacionesMouseClicked(evt);
            }
        });
        lstCategorizaciones.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                lstCategorizacionesFocusLost(evt);
            }
        });
        jScrollPane2.setViewportView(lstCategorizaciones);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnEliminarCategorizacion.setText(org.openide.util.NbBundle.getMessage(diagInvestigadorBusqueda.class, "diagInvestigadorBusqueda.btnEliminarCategorizacion.text")); // NOI18N
        btnEliminarCategorizacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarCategorizacionActionPerformed(evt);
            }
        });

        btnModifiicacionCategorizacion.setText(org.openide.util.NbBundle.getMessage(diagInvestigadorBusqueda.class, "diagInvestigadorBusqueda.btnModifiicacionCategorizacion.text")); // NOI18N
        btnModifiicacionCategorizacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifiicacionCategorizacionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnEliminarCategorizacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCategorizacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnModifiicacionCategorizacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCategorizacion)
                        .addGap(11, 11, 11)
                        .addComponent(btnModifiicacionCategorizacion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEliminarCategorizacion)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbTipoActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        buscarInvestigador();
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void lstDatosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstDatosMouseClicked
        Investigador investigador = (Investigador) lstDatos.getSelectedValue();
        setInvestigadorSeleccionado(investigador);
        cargarCategorizaciones();
        btnCategorizacion.setEnabled(true);
        deshabilitarBotones();
    }//GEN-LAST:event_lstDatosMouseClicked

    private void btnCategorizacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCategorizacionActionPerformed
        diagCategorizacionAlta diagCategoriazion = new diagCategorizacionAlta(null, true,usuario);
        diagCategoriazion.setVisible(true);
        //cargarCategorizaciones();
    }//GEN-LAST:event_btnCategorizacionActionPerformed

private void lstCategorizacionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstCategorizacionesMouseClicked
    Categorizacion categoria = (Categorizacion) lstCategorizaciones.getSelectedValue();
    setCategoriaSeleccionada(categoria);
    btnModifiicacionCategorizacion.setEnabled(true);
    btnEliminarCategorizacion.setEnabled(true);
}//GEN-LAST:event_lstCategorizacionesMouseClicked

private void lstDatosValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstDatosValueChanged
    //cargarCategorizaciones();
}//GEN-LAST:event_lstDatosValueChanged

private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained
}//GEN-LAST:event_formFocusGained

    private void btnEliminarCategorizacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarCategorizacionActionPerformed
        eliminarCategorizacion();
        deshabilitarBotones();
    }//GEN-LAST:event_btnEliminarCategorizacionActionPerformed

    private void btnAgregarInvestigadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarInvestigadorActionPerformed
        agregarInvestigador();
        deshabilitarBotones();
    }//GEN-LAST:event_btnAgregarInvestigadorActionPerformed

    private void lstCategorizacionesFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lstCategorizacionesFocusLost
        //btnEliminarCategorizacion.setEnabled(false);
        //btnModifiicacionCategorizacion.setEnabled(false);
    }//GEN-LAST:event_lstCategorizacionesFocusLost

    private void btnModifiicacionCategorizacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifiicacionCategorizacionActionPerformed
        modificarCategorizacion();
        deshabilitarBotones();
    }//GEN-LAST:event_btnModifiicacionCategorizacionActionPerformed

    private void tfTValorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfTValorMouseClicked
        deshabilitarBotones();
    }//GEN-LAST:event_tfTValorMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(diagInvestigadorBusqueda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(diagInvestigadorBusqueda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(diagInvestigadorBusqueda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(diagInvestigadorBusqueda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the dialog
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                diagInvestigadorBusqueda dialog = new diagInvestigadorBusqueda(new javax.swing.JFrame(), true, new Usuario());
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarInvestigador;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCategorizacion;
    private javax.swing.JButton btnEliminarCategorizacion;
    private javax.swing.JButton btnModifiicacionCategorizacion;
    private javax.swing.JComboBox cmbTipo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList lstCategorizaciones;
    private javax.swing.JList lstDatos;
    private javax.swing.JTextField tfTValor;
    // End of variables declaration//GEN-END:variables

    //MANEJO DE COMPONENTES
    private void inicializarComponentes() {
        this.setLocationRelativeTo(null);
        getRootPane().setDefaultButton(btnBuscar);
        btnModifiicacionCategorizacion.setEnabled(false);
        btnEliminarCategorizacion.setEnabled(false);
        tfTValor.requestFocus();
    }

    //MANEJO DE DATOS
    private void buscarInvestigador() {
        limpiarListaCategorizaciones();
        limpiarListaInvestigadores();
        List<Investigador> listaInvestigadores = new ArrayList<Investigador>();
        if (cmbTipo.getSelectedItem().equals("Apellido")) {
            listaInvestigadores = InvestigadorFacade.getInstance().buscarDniApellido(tfTValor.getText());
            if(listaInvestigadores.isEmpty()){
                JOptionPane.showMessageDialog(null, "No se encontraron resultados para: " + tfTValor.getText());
            }else{
                Comunes.cargarJList(lstDatos, listaInvestigadores);
            }
        } else if (cmbTipo.getSelectedItem().equals("DNI")) {
            if (LongValidator.getInstance().isValid(tfTValor.getText())) {
                listaInvestigadores = InvestigadorFacade.getInstance().buscarPorNumeroDocumentoIdentidad(Long.parseLong(tfTValor.getText()));
                if(listaInvestigadores.isEmpty()){
                    JOptionPane.showMessageDialog(null, "No se encontraron resultados para: " + tfTValor.getText());
                }else{
                    Comunes.cargarJList(lstDatos, listaInvestigadores);
                }
            } else {
                JOptionPane.showMessageDialog(null, "Número de Documento de Identidad incorrecto", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
        deshabilitarBotones();
    }

    private void cargarCategorizaciones() {              
        Comunes.cargarJList(lstCategorizaciones, ((Investigador) lstDatos.getSelectedValue()).getCategorizaciones());
    }
    
    private void limpiarListaCategorizaciones(){
        DefaultListModel model = new DefaultListModel();
        lstCategorizaciones.setModel(model);        
    }
    
    private void limpiarListaInvestigadores(){
        DefaultListModel model = new DefaultListModel();
        lstDatos.setModel(model);        
    }                

    private void eliminarCategorizacion() {
        int eleccion = JOptionPane.showConfirmDialog(rootPane, "Esta seguro "
                + "que desea eliminar La Categorización "
                + lstCategorizaciones.getSelectedValue() + " ?",
                "Confirma Eliminacion?", JOptionPane.YES_NO_OPTION);
        if (eleccion == 0) {
            Categorizacion categorizacion = (Categorizacion) lstCategorizaciones.getSelectedValue();
            facade.CategorizacionFacade.getInstance().baja(categorizacion);              
                      
            // Selecciono el investigador al cual le voy a quitar una categoria y se la quito
            Investigador inve = diagInvestigadorBusqueda.investigadorSeleccionado;
            List<Categorizacion> listaCategorias = inve.getCategorizaciones();
            listaCategorias.remove(categorizacion);
            inve.setCategorizaciones(listaCategorias);
            InvestigadorFacade.getInstance().modificar(inve);
            
            Operacion operacion = new Operacion();
            operacion.setFecha(Comunes.obtenerFechaActualDesdeDB());
            operacion.setOperacion("Baja de Categorización");
            operacion.setUsuario(usuario);
            OperacionFacade.getInstance().alta(operacion);
            buscarInvestigador();
            JOptionPane.showMessageDialog(rootPane, "La Categoría fue eliminada");                   
        }
    }

    private void agregarInvestigador() {
        vistas.investigadores.diagInvestigador investigador = new diagInvestigador(null, true, "Alta", usuario);
        investigador.setVisible(true);
    }

    private void modificarCategorizacion() {
        diagCategorizacionModificacion categorizacionModificacion = new diagCategorizacionModificacion(null, true, usuario);
        categorizacionModificacion.setVisible(true);
    }

    private void deshabilitarBotones() {
        btnEliminarCategorizacion.setEnabled(false);
        btnModifiicacionCategorizacion.setEnabled(false);
    }
}
