/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.proyectoWeb;

import controladores.DocumentoJpaController;
import entidades.Documento;
import entidades.Resolucion;
import entidades.economico.Presupuesto;
import entidades.proyecto.Participacion;
import entidades.proyecto.Proyecto;
import entidades.proyecto.ProyectoDatosComplementarios;
import entidades.proyectoWeb.ArchivoWeb;
import entidades.proyectoWeb.ParticipacionWeb;
import entidades.proyectoWeb.ProyectoWeb;
import facade.ConexionFacade;
import facade.ParticipacionFacade;
import facade.PresupuestoFacade;
import facade.ProyectoDatosComplementariosFacade;
import facade.ProyectoFacade;
import facade.ProyectoWebFacade;
import facade.ResolucionFacade;
import includes.Comunes;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.Persistence;
import javax.swing.JOptionPane;

/**
 *
 * @author hugo
 */
public class diagVistaProyectoWeb extends javax.swing.JDialog {

    private ProyectoWeb proyectoWeb;
    private ParticipacionFacade participacionFacade = new ParticipacionFacade();

    /**
     * Creates new form diagVistaProyectoWeb
     */
    public diagVistaProyectoWeb(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        inicializarComponentes();
    }

    public diagVistaProyectoWeb(java.awt.Frame parent, boolean modal, ProyectoWeb proyectoWeb) {
        super(parent, modal);
        initComponents();
        this.proyectoWeb = proyectoWeb;
        inicializarComponentes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAprobar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tfCodigoProyecto = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jxdpFechaInicio = new org.jdesktop.swingx.JXDatePicker();
        jLabel9 = new javax.swing.JLabel();
        jxdpFechaFinalizacion = new org.jdesktop.swingx.JXDatePicker();
        jScrollPane7 = new javax.swing.JScrollPane();
        JlstParticipaciones = new javax.swing.JList();
        jLabel10 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        taObservaciones = new javax.swing.JTextArea();
        tfUnidadAcademica = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        tfConvocatoria = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        tfUnidadEjecutora = new javax.swing.JTextField();
        jScrollPane9 = new javax.swing.JScrollPane();
        taTituloProyecto1 = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        jlistocalizaciones = new javax.swing.JList();
        tfLineaInvestigacion = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstSubdisciplinasCientificas = new javax.swing.JList();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jlstArchivos = new javax.swing.JList();
        bntNoAprobar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnAprobar.setText(org.openide.util.NbBundle.getMessage(diagVistaProyectoWeb.class, "diagVistaProyectoWeb.btnAprobar.text")); // NOI18N
        btnAprobar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAprobarActionPerformed(evt);
            }
        });

        btnCancelar.setText(org.openide.util.NbBundle.getMessage(diagVistaProyectoWeb.class, "diagVistaProyectoWeb.btnCancelar.text")); // NOI18N
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(diagVistaProyectoWeb.class, "diagVistaProyectoWeb.jPanel1.border.title"))); // NOI18N
        jPanel1.setAutoscrolls(true);

        jLabel1.setText(org.openide.util.NbBundle.getMessage(diagVistaProyectoWeb.class, "diagVistaProyectoWeb.jLabel1.text")); // NOI18N

        tfCodigoProyecto.setText(org.openide.util.NbBundle.getMessage(diagVistaProyectoWeb.class, "diagVistaProyectoWeb.tfCodigoProyecto.text")); // NOI18N

        jLabel2.setText(org.openide.util.NbBundle.getMessage(diagVistaProyectoWeb.class, "diagVistaProyectoWeb.jLabel2.text")); // NOI18N

        jLabel3.setText(org.openide.util.NbBundle.getMessage(diagVistaProyectoWeb.class, "diagVistaProyectoWeb.jLabel3.text")); // NOI18N

        jLabel4.setText(org.openide.util.NbBundle.getMessage(diagVistaProyectoWeb.class, "diagVistaProyectoWeb.jLabel4.text")); // NOI18N

        jLabel7.setText(org.openide.util.NbBundle.getMessage(diagVistaProyectoWeb.class, "diagVistaProyectoWeb.jLabel7.text")); // NOI18N

        jLabel5.setText(org.openide.util.NbBundle.getMessage(diagVistaProyectoWeb.class, "diagVistaProyectoWeb.jLabel5.text")); // NOI18N

        jLabel8.setText(org.openide.util.NbBundle.getMessage(diagVistaProyectoWeb.class, "diagVistaProyectoWeb.jLabel8.text")); // NOI18N

        jLabel9.setText(org.openide.util.NbBundle.getMessage(diagVistaProyectoWeb.class, "diagVistaProyectoWeb.jLabel9.text")); // NOI18N

        jScrollPane7.setViewportView(JlstParticipaciones);

        jLabel10.setText(org.openide.util.NbBundle.getMessage(diagVistaProyectoWeb.class, "diagVistaProyectoWeb.jLabel10.text")); // NOI18N

        jLabel6.setText(org.openide.util.NbBundle.getMessage(diagVistaProyectoWeb.class, "diagVistaProyectoWeb.jLabel6.text")); // NOI18N

        taObservaciones.setColumns(20);
        taObservaciones.setRows(5);
        jScrollPane8.setViewportView(taObservaciones);

        tfUnidadAcademica.setText(org.openide.util.NbBundle.getMessage(diagVistaProyectoWeb.class, "diagVistaProyectoWeb.tfUnidadAcademica.text")); // NOI18N

        jLabel11.setText(org.openide.util.NbBundle.getMessage(diagVistaProyectoWeb.class, "diagVistaProyectoWeb.jLabel11.text")); // NOI18N

        tfConvocatoria.setText(org.openide.util.NbBundle.getMessage(diagVistaProyectoWeb.class, "diagVistaProyectoWeb.tfConvocatoria.text")); // NOI18N

        jLabel12.setText(org.openide.util.NbBundle.getMessage(diagVistaProyectoWeb.class, "diagVistaProyectoWeb.jLabel12.text")); // NOI18N

        tfUnidadEjecutora.setText(org.openide.util.NbBundle.getMessage(diagVistaProyectoWeb.class, "diagVistaProyectoWeb.tfUnidadEjecutora.text")); // NOI18N

        taTituloProyecto1.setColumns(20);
        taTituloProyecto1.setRows(5);
        jScrollPane9.setViewportView(taTituloProyecto1);

        jlistocalizaciones.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane5.setViewportView(jlistocalizaciones);

        tfLineaInvestigacion.setText(org.openide.util.NbBundle.getMessage(diagVistaProyectoWeb.class, "diagVistaProyectoWeb.tfLineaInvestigacion.text")); // NOI18N

        lstSubdisciplinasCientificas.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(lstSubdisciplinasCientificas);

        jLabel13.setText(org.openide.util.NbBundle.getMessage(diagVistaProyectoWeb.class, "diagVistaProyectoWeb.jLabel13.text")); // NOI18N

        jlstArchivos.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jlstArchivos);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane8, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jxdpFechaInicio, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                                    .addComponent(jxdpFechaFinalizacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(jLabel5)
                            .addComponent(jLabel10)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jScrollPane7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 455, Short.MAX_VALUE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel1)
                                        .addComponent(jLabel11))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(tfCodigoProyecto)
                                        .addComponent(tfConvocatoria))))))
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jLabel2)
                    .addComponent(jLabel12)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfUnidadAcademica, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE)
                            .addComponent(tfUnidadEjecutora)))
                    .addComponent(jLabel4)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tfLineaInvestigacion, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfConvocatoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)
                            .addComponent(tfUnidadAcademica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(tfCodigoProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(tfUnidadEjecutora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel12)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(tfLineaInvestigacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jxdpFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jxdpFechaFinalizacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39))
        );

        jScrollPane4.setViewportView(jPanel1);

        bntNoAprobar.setText(org.openide.util.NbBundle.getMessage(diagVistaProyectoWeb.class, "diagVistaProyectoWeb.bntNoAprobar.text")); // NOI18N
        bntNoAprobar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntNoAprobarActionPerformed(evt);
            }
        });

        jButton1.setText(org.openide.util.NbBundle.getMessage(diagVistaProyectoWeb.class, "diagVistaProyectoWeb.jButton1.text")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(114, 114, 114)
                        .addComponent(btnAprobar, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bntNoAprobar, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(110, 110, 110)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 366, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAprobar)
                    .addComponent(btnCancelar)
                    .addComponent(bntNoAprobar)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAprobarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAprobarActionPerformed
        aprobarProyecto();
    }//GEN-LAST:event_btnAprobarActionPerformed

    private void bntNoAprobarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntNoAprobarActionPerformed
        noAprobar();
    }//GEN-LAST:event_bntNoAprobarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        cerrarDialog();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ProyectoWeb proyecto = proyectoWeb;
//        proyecto.setCronogramaTrabajo(filterHTMLTags(proyecto.getCronogramaTrabajo()));
//        proyecto.setCapacitacionFormacionRH(filterHTMLTags(proyecto.getCapacitacionFormacionRH()));
        new reportes.Reporte().reporteProyectoConvocatoria(proyecto);

    }//GEN-LAST:event_jButton1ActionPerformed

//    public static String filterHTMLTags(String html) {
//
//         String striped = html.toString().replaceAll("\\<.*?>","");
//
//        // save valid tags:
////        String striped = html.replaceAll("(?i)\\<(\\s*/?(h\\d|b|i|em|strong|p|br|li|ul|ol).*?/?)\\>", "{{$1}}");
////        // remove all tags:
////        striped = striped.replaceAll("\\<(/?[^\\>]+)\\>", " ");
////        // restore valid tags:
////        striped = striped.replaceAll("\\{\\{(.+?)\\}\\}", "<$1>");
////
//        return striped;
//    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(diagVistaProyectoWeb.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(diagVistaProyectoWeb.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(diagVistaProyectoWeb.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(diagVistaProyectoWeb.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                diagVistaProyectoWeb dialog = new diagVistaProyectoWeb(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList JlstParticipaciones;
    private javax.swing.JButton bntNoAprobar;
    private javax.swing.JButton btnAprobar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JList jlistocalizaciones;
    private javax.swing.JList jlstArchivos;
    private org.jdesktop.swingx.JXDatePicker jxdpFechaFinalizacion;
    private org.jdesktop.swingx.JXDatePicker jxdpFechaInicio;
    private javax.swing.JList lstSubdisciplinasCientificas;
    private javax.swing.JTextArea taObservaciones;
    private javax.swing.JTextArea taTituloProyecto1;
    private javax.swing.JTextField tfCodigoProyecto;
    private javax.swing.JTextField tfConvocatoria;
    private javax.swing.JTextField tfLineaInvestigacion;
    private javax.swing.JTextField tfUnidadAcademica;
    private javax.swing.JTextField tfUnidadEjecutora;
    // End of variables declaration//GEN-END:variables

    private void inicializarComponentes() {
        this.setTitle("Proyecto Web");
        Comunes.autoAjusteTextArea(taObservaciones);
        Comunes.autoAjusteTextArea(taTituloProyecto1);
        disableComponents();

        try {
            tfConvocatoria.setText(proyectoWeb.getConvocatoria().getDescripcion());
        } catch (Exception e) {
            tfConvocatoria.setText("");
        }
        try {
            tfCodigoProyecto.setText(proyectoWeb.getCodigo());
        } catch (Exception e) {
            tfCodigoProyecto.setText("");
        }
        try {
            taTituloProyecto1.setText(proyectoWeb.getTitulo());
        } catch (Exception e) {
            taTituloProyecto1.setText("");
        }
        try {
            jxdpFechaInicio.setDate(proyectoWeb.getFechaInicio());
        } catch (Exception e) {
            jxdpFechaInicio.setDate(new Date());
        }
        try {
            jxdpFechaFinalizacion.setDate(proyectoWeb.getFechaFinalizacion());
        } catch (Exception e) {
            jxdpFechaFinalizacion.setDate(new Date());
        }
        try {
            Comunes.cargarJList(JlstParticipaciones, proyectoWeb.getParticipacionesWeb());
        } catch (Exception e) {
        }
        try {
            taObservaciones.setText(proyectoWeb.getObservaciones());
        } catch (Exception e) {
            taObservaciones.setText("");
        }
        try {
            tfUnidadAcademica.setText(proyectoWeb.getUnidadAcademica().toString());
        } catch (Exception e) {
            tfUnidadAcademica.setText("");
        }
        try {
            tfUnidadEjecutora.setText(proyectoWeb.getUnidadEjecutora().toString());
        } catch (Exception e) {
            tfUnidadEjecutora.setText("");
        }
        try {
            Comunes.cargarJList(jlistocalizaciones, proyectoWeb.getLocalizaciones());
        } catch (Exception e) {
        }
        try {
            tfLineaInvestigacion.setText(proyectoWeb.getLineaPrioritaria().getDescripcion());
        } catch (Exception e) {
            tfLineaInvestigacion.setText("");
        }
        try {
            Comunes.cargarJList(lstSubdisciplinasCientificas, proyectoWeb.getSubDisciplinasCientificas());
        } catch (Exception e) {
        }
        try {
            Comunes.cargarJList(jlstArchivos, proyectoWeb.getLstArchivoWeb());
        } catch (Exception e) {
        }
    }

    private void aprobarProyecto() {

//        try {
        darAltaProyectoWebComoProyecto();
        editarProyectoWeb();
//        } catch (Exception e) {
//            JOptionPane.showMessageDialog(rootPane, "Error al realizar la operacion");
//        }

    }

    private void editarProyectoWeb() {
        try {
            proyectoWeb.setObservaciones(taObservaciones.getText());
        } catch (Exception e) {
            proyectoWeb.setObservaciones(null);
        }
        proyectoWeb.setAprobado(true);
        try {
            ProyectoWebFacade.getInstance().editar(proyectoWeb);
        } catch (Exception ex) {
            Logger.getLogger(diagVistaProyectoWeb.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void darAltaProyectoWebComoProyecto() {
        //DIVIENDO PROYECTOWEB EN "PROYECTO Y DATOSCOMPLEMENTARIOS"
        //DATOS COMPLEMENTARIOS
        ProyectoDatosComplementarios datosComplementarios = new ProyectoDatosComplementarios();
        try {
            datosComplementarios.setAntecedentes(proyectoWeb.getProyectoWebFGP().getAntecedentes());
        } catch (Exception e) {
            datosComplementarios.setAntecedentes(null);
        }
        try {
            datosComplementarios.setCapacitacionFormacionRH(proyectoWeb.getProyectoWebFGP().getCapacitacionFormacionRH());
        } catch (Exception e) {
            datosComplementarios.setCapacitacionFormacionRH(null);
        }
        try {
            datosComplementarios.setConvocatoria(proyectoWeb.getConvocatoria());
        } catch (Exception e) {
            datosComplementarios.setConvocatoria(null);
        }
        try {
            datosComplementarios.setCronogramaTrabajo(proyectoWeb.getProyectoWebFGP().getCronogramaTrabajo());
        } catch (Exception e) {
            datosComplementarios.setCronogramaTrabajo(null);
        }
        datosComplementarios.setFinalizado(true);
        try {
            datosComplementarios.setLocalizacionOtra(proyectoWeb.getLocalizacionOtra());
        } catch (Exception e) {
            datosComplementarios.setLocalizacionOtra(null);
        }
        try {
            datosComplementarios.setMetodologia(proyectoWeb.getProyectoWebFGP().getMetodologia());
        } catch (Exception e) {
            datosComplementarios.setMetodologia(null);
        }
        try {
            datosComplementarios.setObjetivoEspecificoHipotesis(proyectoWeb.getProyectoWebFGP().getObjetivoEspecificoHipotesis());
        } catch (Exception e) {
            datosComplementarios.setObjetivoEspecificoHipotesis(null);
        }
        try {
            datosComplementarios.setObjetivoGral(proyectoWeb.getProyectoWebFGP().getObjetivoGral());
        } catch (Exception e) {
            datosComplementarios.setObjetivoGral(null);
        }
        try {
            datosComplementarios.setProyectoIniciacion(proyectoWeb.getProyectoIniciacion());
        } catch (Exception e) {
            datosComplementarios.setProyectoIniciacion(null);
        }
        try {
            datosComplementarios.setProyectoOrientado(proyectoWeb.getProyectoOrientado());
        } catch (Exception e) {
            datosComplementarios.setProyectoOrientado(null);
        }
        try {
            datosComplementarios.setRelevanciaProblema(proyectoWeb.getProyectoWebFGP().getRelevanciaProblema());
        } catch (Exception e) {
            datosComplementarios.setRelevanciaProblema(null);
        }
        try {
            datosComplementarios.setSubDisciplinaCientificaOtra(proyectoWeb.getSubDisciplinaCientificaOtra());
        } catch (Exception e) {
            datosComplementarios.setSubDisciplinaCientificaOtra(null);
        }
        try {
            datosComplementarios.setUnidadEjecutoraOtra(proyectoWeb.getUnidadEjecutoraOtra());
        } catch (Exception e) {
            datosComplementarios.setUnidadEjecutoraOtra(null);
        }
        try {
            datosComplementarios.setLatitud(proyectoWeb.getLatitud());
        } catch (Exception e) {
            datosComplementarios.setLatitud(-28.459478);
        }
        try {
            datosComplementarios.setLongitud(proyectoWeb.getLongitud());
        } catch (Exception e) {
            datosComplementarios.setLongitud(-65.782818);
        }
        try {
            datosComplementarios.setSectorPrioritario(proyectoWeb.getSectorPrioritario());
        } catch (Exception e) {
            datosComplementarios.setSectorPrioritario(null);
        }
        try {
            datosComplementarios.setSectorPrioritarioOtro(proyectoWeb.getSectorPrioritarioOtro());
        } catch (Exception e) {
            datosComplementarios.setSectorPrioritarioOtro(null);
        }
        //DATOS DE PROYECTO
        Proyecto proyecto = new Proyecto();
        try {
            proyecto.setCamposAplicacion(proyectoWeb.getCamposAplicacion());
        } catch (Exception e) {
            proyecto.setCamposAplicacion(null);
        }
        try {
            proyecto.setCodigo(proyectoWeb.getCodigo());
        } catch (Exception e) {
            proyecto.setCodigo(null);
        }
        try {
            proyecto.setCodigoIncentivos(proyectoWeb.getCodigo());
        } catch (Exception e) {
            proyecto.setCodigoIncentivos(null);
        }
        try {
            proyecto.setFechaFinalizacion(proyectoWeb.getFechaFinalizacion());
        } catch (Exception e) {
            proyecto.setFechaFinalizacion(new Date());
        }
        try {
            proyecto.setFechaInicio(proyectoWeb.getFechaInicio());
        } catch (Exception e) {
            proyecto.setFechaInicio(new Date());
        }
        try {
            proyecto.setKeywords(proyectoWeb.getKeywords());
        } catch (Exception e) {
            proyecto.setKeywords(new ArrayList<String>());
        }
        try {
            proyecto.setLineaInvestigacion(proyectoWeb.getLineaInvestigacion());
        } catch (Exception e) {
            proyecto.setLineaInvestigacion(null);
        }
        try {
            proyecto.setObjetivoSocioeconomico(proyectoWeb.getObjetivoSocioeconomico());
        } catch (Exception e) {
            proyecto.setObjetivoSocioeconomico(null);
        }
        try {
            proyecto.setPalabrasClaves(proyectoWeb.getPalabrasClaves());
        } catch (Exception e) {
            proyecto.setPalabrasClaves(new ArrayList<String>());
        }
        //resoluciones(Archivos)
//        try {
        if (!proyectoWeb.getLstArchivoWeb().isEmpty()) {
            List<Resolucion> resoluciones = new ArrayList<>();
            System.out.println("Lista Archivos Web" + proyectoWeb.getLstArchivoWeb());
            for (ArchivoWeb archivoWeb : proyectoWeb.getLstArchivoWeb()) {
                System.out.println("entro");
                Documento documento = new Documento();
                documento.setContenidoArchivo(archivoWeb.getContenidoArchivo());
                documento.setNombreArchivo(archivoWeb.getNombre());
                new DocumentoJpaController(Persistence.createEntityManagerFactory("ProyectoUnoPU", ConexionFacade.PROPIEDADES)).create(documento);
                Resolucion resolucion = new Resolucion();
                resolucion.setDocumento(documento);
                resolucion.setDescripcion(documento.getNombreArchivo());
                new ResolucionFacade().alta(resolucion);
                resoluciones.add(resolucion);
                System.out.println("resolucion creada" + resolucion);
            }
            proyecto.setResoluciones(resoluciones);
        }
//        } catch (Exception e) {
//            System.out.println("entro catchh");
//            proyecto.setResoluciones(null);
//        }

        //PRESUPUESTOWEB A PRESUPUESTO
        if (proyectoWeb.getPresupuestoWeb() != null) {
            Presupuesto presupuesto = new Presupuesto();
            presupuesto.setBienConsumo(proyectoWeb.getPresupuestoWeb().getBienConsumo());
            presupuesto.setBienNoPersonal(proyectoWeb.getPresupuestoWeb().getBienNoPersonal());
            presupuesto.setBienUso(proyectoWeb.getPresupuestoWeb().getBienUso());
            presupuesto.setGastosViaje(proyectoWeb.getPresupuestoWeb().getGastosViaje());
            //presupuesto.setProyecto(proyecto);
            PresupuestoFacade.getInstance().altaPresupuesto(presupuesto);
            proyecto.setPresupuesto(presupuesto);
        } else {
            proyecto.setPresupuesto(null);
        }

        try {
            proyecto.setResumen(proyectoWeb.getResumen());
        } catch (Exception e) {
            proyecto.setResumen(null);
        }
        try {
            proyecto.setSubDisciplinasCientificas(proyectoWeb.getSubDisciplinasCientificas());
        } catch (Exception e) {
            proyecto.setSubDisciplinasCientificas(null);
        }
        try {
            proyecto.setSummary(proyectoWeb.getSummary());
        } catch (Exception e) {
            proyecto.setSummary(null);
        }
        try {
            proyecto.setTipoProyecto(proyectoWeb.getTipoProyecto());
        } catch (Exception e) {
            proyecto.setTipoProyecto(null);
        }
        try {
            proyecto.setTitle(proyectoWeb.getTitle());
        } catch (Exception e) {
            proyecto.setTitle(null);
        }
        try {
            proyecto.setTitulo(proyectoWeb.getTitulo());
        } catch (Exception e) {
            proyecto.setTitulo(null);
        }
        try {
            proyecto.setUnidadAcademica(proyectoWeb.getUnidadAcademica());
        } catch (Exception e) {
            proyecto.setUnidadAcademica(null);
        }
        try {
            proyecto.setUnidadEjecutora(proyectoWeb.getUnidadEjecutora());
        } catch (Exception e) {
            proyecto.setUnidadEjecutora(null);
        }

        ProyectoFacade.getInstance().alta(proyecto);
        //PARTICIPACIONESWEB A PARTICIPACIONES

        if (!proyectoWeb.getParticipacionesWeb().isEmpty()) {
            List<Participacion> participaciones = new ArrayList<>();
            Participacion participacion = new Participacion();
            for (ParticipacionWeb pw : proyectoWeb.getParticipacionesWeb()) {
                participacion.setDedicacionSemanal(pw.getDedicacionSemanal());
                participacion.setFechaDesde(pw.getFechaDesde());
                participacion.setFechaHasta(pw.getFechaHasta());
                participacion.setInvestigador(pw.getInvestigador());
                participacion.setProyecto(proyecto);
                participacion.setRol(pw.getRol());
                participacionFacade.alta(participacion);
                participaciones.add(participacion);

            }
            proyecto.setParticipaciones(participaciones);
            ProyectoFacade.getInstance().modificar(proyecto);

        }

        datosComplementarios.setProyecto(proyecto);
        ProyectoDatosComplementariosFacade.getInstance().alta(datosComplementarios);

        JOptionPane.showMessageDialog(null, "Proyecto Agregado!");
        this.dispose();

    }

    private void cerrarDialog() {
        this.dispose();
    }

    private void noAprobar() {
        if (taObservaciones.getText().isEmpty()) {

            int respuesta = JOptionPane.showConfirmDialog(null, "Se sugiere enviar una observacion, desea enviarla?", "Sugerencia", JOptionPane.YES_NO_OPTION);
            if (respuesta == 0) {
                taObservaciones.requestFocus();
            } else {
                editarCerrar();

            }
        } else {
            editarCerrar();
        }

    }

    private void editarCerrar() {
        try {
            proyectoWeb.setObservaciones(taObservaciones.getText());
        } catch (Exception e) {
            proyectoWeb.setObservaciones(null);
        }
        JOptionPane.showMessageDialog(null, "finalizado =" + proyectoWeb.getFinalizado());
        proyectoWeb.setFinalizado(false);

        try {
            ProyectoWebFacade.getInstance().editar(proyectoWeb);
            this.dispose();
        } catch (Exception ex) {
            Logger.getLogger(diagVistaProyectoWeb.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void disableComponents() {
        tfConvocatoria.setEditable(false);
        tfCodigoProyecto.setEditable(false);
        tfLineaInvestigacion.setEditable(false);
        tfUnidadAcademica.setEditable(false);
        tfUnidadEjecutora.setEditable(false);
        taTituloProyecto1.setEditable(false);
        jxdpFechaFinalizacion.setEditable(false);
        jxdpFechaInicio.setEditable(false);
    }
}
