/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * diagDatosInvestigador.java
 *
 * Created on 14/06/2011, 12:19:48
 */
package importador;


import entidades.operaciones.Operacion;
import entidades.persona.investigador.Investigador;
import entidades.proyecto.Proyecto;
import entidades.proyecto.Rol;
import entidades.usuario.Usuario;
import facade.OperacionFacade;
import facade.ParticipacionFacade;
import facade.ProyectoFacade;
import facade.RolFacade;
import includes.Comunes;
import java.util.Date;
import javax.swing.JOptionPane;
import org.apache.commons.validator.routines.IntegerValidator;

/**
 *
 * @author carlos
 */
public class diagDatosNuevosInvestigador extends javax.swing.JDialog {

    private Investigador investigador;
    private Proyecto proyecto;
    private ParticipacionFacade participacionFacade = new ParticipacionFacade();
    private ProyectoFacade proyectoFacade = ProyectoFacade.getInstance();
    private RolFacade rolFacade = new RolFacade();
    private boolean guardado = false;
    private Usuario usuario;

    /** Creates new form diagDatosInvestigador */
    public diagDatosNuevosInvestigador(java.awt.Frame parent, boolean modal, Investigador investigador, Proyecto proyecto, Usuario usuario) {
        super(parent, modal);
        initComponents();
        this.investigador = investigador;
        this.proyecto = proyecto;
        this.usuario = usuario;
        inicializarComponentes();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jXDateFechaDesde = new org.jdesktop.swingx.JXDatePicker();
        jXDateFechaHasta = new org.jdesktop.swingx.JXDatePicker();
        cboRol = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTfResolucionAlta = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTfResolucionBaja = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Fecha Desde");

        jLabel2.setText("Fecha Hasta");

        jLabel3.setText("Rol");

        jXDateFechaDesde.setFormats("dd/MM/yyyy");

        jXDateFechaHasta.setFormats("dd/MM/yyyy");

        jButton1.setText("Guardar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jCheckBox1.setText("Sigue Participando Actualmente");
        jCheckBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBox1ItemStateChanged(evt);
            }
        });

        jLabel4.setText("jLabel4");

        jLabel5.setText("Ded. Semanal (hs)");

        jLabel6.setText("Numero Resolucion Alta");

        jLabel7.setText("Numero Resolucion Baja");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(179, 179, 179)
                        .addComponent(jButton1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jXDateFechaHasta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jXDateFechaDesde, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cboRol, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTfResolucionBaja, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                                    .addComponent(jTfResolucionAlta))))
                        .addGap(6, 6, 6)
                        .addComponent(jCheckBox1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jXDateFechaDesde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jXDateFechaHasta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jCheckBox1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cboRol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTfResolucionAlta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTfResolucionBaja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        guardar();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jCheckBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBox1ItemStateChanged
        cambiarEstadoFechaHasta();
    }//GEN-LAST:event_jCheckBox1ItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                diagDatosNuevosInvestigador dialog = new diagDatosNuevosInvestigador(new javax.swing.JFrame(), true, new Investigador(), new Proyecto(), new Usuario());
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cboRol;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTfResolucionAlta;
    private javax.swing.JTextField jTfResolucionBaja;
    private org.jdesktop.swingx.JXDatePicker jXDateFechaDesde;
    private org.jdesktop.swingx.JXDatePicker jXDateFechaHasta;
    // End of variables declaration//GEN-END:variables

    public Investigador getInvestigador() {
        return investigador;
    }

    public Proyecto getProyecto() {
        return proyecto;
    }

    private void inicializarComponentes() {
        Comunes.cargarJCombo(cboRol, rolFacade.getTodos());
        jLabel4.setText("Participación de " + investigador.getPersona().getApellido() + " "
                + investigador.getPersona().getNombre() + " en el Proyecto "
                + proyecto.getTitulo());
    }

    private void guardar() {
//        Participacion participacion = new Participacion();
//        participacion.setFechaDesde(jXDatePicker1.getDate());
//        if(jXDatePicker2.isEnabled()) {
//            participacion.setFechaHasta(jXDatePicker2.getDate());
//        }
//        participacion.setInvestigador(investigador);
//        participacion.setProyecto(proyecto);
//        participacion.setRol((Rol) jComboBox2.getSelectedItem());
//        new ParticipacionJpaController().create(participacion);
        if (jXDateFechaHasta.getDate().after(jXDateFechaDesde.getDate())) {
            if (IntegerValidator.getInstance().isValid(jTextField1.getText())) {
                Date fechaHasta;
                if(!jCheckBox1.isSelected()) {
                    fechaHasta = jXDateFechaHasta.getDate();
                } else {
                    fechaHasta = null;
                }
                String resolucionAlta;
                        String resolucionBaja;
                        if(jTfResolucionAlta.getText()!=null){
                            resolucionAlta=jTfResolucionAlta.getText();
                        }else{
                            resolucionAlta=null;
                        }
                        if(jTfResolucionBaja.getText()!=null){
                            resolucionBaja=jTfResolucionBaja.getText();
                        }else{
                            resolucionBaja=null;
                        }
                proyectoFacade.agregarParticipacion(investigador, proyecto,
                        jXDateFechaDesde.getDate(), fechaHasta,
                        (Rol) cboRol.getSelectedItem(), Integer.parseInt(jTextField1.getText()),
                        resolucionAlta,resolucionBaja);
                guardado = true;
                Operacion operacion = new Operacion();
                operacion.setFecha(Comunes.obtenerFechaActualDesdeDB());
                operacion.setOperacion("Agregación de Integrante en Proyecto");
                operacion.setUsuario(usuario);
                OperacionFacade.getInstance().alta(operacion);
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(null, "Dedicación semanal incorrecta",
                        "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Fechas incorrectas. La fecha "
                    + "desde debe ser anterior a la fecha hasta",
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    public boolean isGuardado() {
        return guardado;
    }

    private void cambiarEstadoFechaHasta() {
        if (jCheckBox1.isSelected()) {
            jXDateFechaHasta.setEnabled(false);
        } else {
            jXDateFechaHasta.setEnabled(true);
        }
    }
}
