/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * diagPresupuesto.java
 *
 * Created on 17/08/2012, 12:07:06
 */
package vista.proyectos.vinculacion.financiacion.picto;

import entidades.proyecto.vinculacion.financiacion.FinanciacionPICTO;
import entidades.proyecto.vinculacion.financiacion.picto.Item;
import entidades.proyecto.vinculacion.financiacion.picto.Rubro;
import facade.proyecto.vinculacion.PictoFacade;
import includes.Comunes;
import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author ruben
 */
public class diagPresupuesto extends javax.swing.JDialog {

    private int duracion;
    private List años;
    private Item item;
    

    /**
     * Creates new form diagPresupuesto
     */
    public diagPresupuesto(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
      
        initComponents();
        inicializarComponentes();
    }

    private diagPresupuesto(JFrame jFrame, boolean b) {
        super(jFrame, b);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jCboxrubro = new javax.swing.JComboBox();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTfdescripcion = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTfmontosubsidio = new javax.swing.JFormattedTextField();
        jTfmontocontraparte = new javax.swing.JFormattedTextField();
        jSpinner1 = new javax.swing.JSpinner();
        jBtnaceptar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setText(org.openide.util.NbBundle.getMessage(diagPresupuesto.class, "diagPresupuesto.jLabel1.text")); // NOI18N

        jLabel2.setText(org.openide.util.NbBundle.getMessage(diagPresupuesto.class, "diagPresupuesto.jLabel2.text")); // NOI18N

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), org.openide.util.NbBundle.getMessage(diagPresupuesto.class, "diagPresupuesto.jPanel2.border.title"))); // NOI18N

        jLabel3.setText(org.openide.util.NbBundle.getMessage(diagPresupuesto.class, "diagPresupuesto.jLabel3.text")); // NOI18N

        jTfdescripcion.setText(org.openide.util.NbBundle.getMessage(diagPresupuesto.class, "diagPresupuesto.jTfdescripcion.text")); // NOI18N

        jLabel4.setText(org.openide.util.NbBundle.getMessage(diagPresupuesto.class, "diagPresupuesto.jLabel4.text")); // NOI18N

        jLabel5.setText(org.openide.util.NbBundle.getMessage(diagPresupuesto.class, "diagPresupuesto.jLabel5.text")); // NOI18N

        jTfmontosubsidio.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.###",new java.text.DecimalFormatSymbols(java.util.Locale.ENGLISH)))));
        jTfmontosubsidio.setText(org.openide.util.NbBundle.getMessage(diagPresupuesto.class, "diagPresupuesto.jTfmontosubsidio.text")); // NOI18N

        jTfmontocontraparte.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.###",new java.text.DecimalFormatSymbols(java.util.Locale.ENGLISH)))));
        jTfmontocontraparte.setText(org.openide.util.NbBundle.getMessage(diagPresupuesto.class, "diagPresupuesto.jTfmontocontraparte.text")); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTfmontocontraparte))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTfdescripcion, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
                            .addComponent(jTfmontosubsidio))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTfdescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTfmontosubsidio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTfmontocontraparte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jCboxrubro, 0, 151, Short.MAX_VALUE)
                            .addComponent(jSpinner1))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jCboxrubro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jBtnaceptar.setText(org.openide.util.NbBundle.getMessage(diagPresupuesto.class, "diagPresupuesto.jBtnaceptar.text")); // NOI18N
        jBtnaceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnaceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jBtnaceptar)
                        .addGap(159, 159, 159))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBtnaceptar)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnaceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnaceptarActionPerformed
        aceptar();
        this.dispose();
    }//GEN-LAST:event_jBtnaceptarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                diagPresupuesto dialog = new diagPresupuesto(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnaceptar;
    private javax.swing.JComboBox jCboxrubro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTextField jTfdescripcion;
    private javax.swing.JFormattedTextField jTfmontocontraparte;
    private javax.swing.JFormattedTextField jTfmontosubsidio;
    // End of variables declaration//GEN-END:variables

    private void cantidadAños() {
        años = new ArrayList();
        for (int i = 0; i < duracion; i++) {
            años.add(i + 1);
        }
    }

    private void inicializarComponentes() {
        cantidadAños();
        jSpinner1.setValue(1);
        Comunes.cargarJComboConBlanco(jCboxrubro, PictoFacade.getInstance().getTodosRubros());
    }

    private void aceptar() {
        
        item = new Item();
        if ( jCboxrubro.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(rootPane, "Debe elegir el Año y el Rubro", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            item.setAño((int)jSpinner1.getValue());
            item.setRubro((Rubro) jCboxrubro.getSelectedItem());
            if(!jTfdescripcion.getText().equals("")){
                item.setDescripcion(jTfdescripcion.getText());
            }else{
                item.setDescripcion("Sin Descripcion");
            }
            
            try {
                if(!jTfmontosubsidio.getText().equals(""))
                {
                item.setMontosubsidio(Float.valueOf(quitarcomas(jTfmontosubsidio.getText())));
                }else{
                    item.setMontosubsidio(0F);
                }
                if(!jTfmontocontraparte.getText().equals(""))
                {
                item.setMontocontraparte(Float.valueOf(quitarcomas(jTfmontocontraparte.getText())));
                }else{
                    item.setMontocontraparte(0F);
                }
            }  catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(rootPane, "Debe ingresar números en los campos de monto", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }

    public Item getItem() {
        return item;
    }
    
    public String quitarcomas(String numero){
        return numero.replace(",", "").trim();
    }

    public float formatodecimal(String texto) throws ParseException {

        float valor = 0;

        DecimalFormatSymbols simbolos = new DecimalFormatSymbols();
        simbolos.setDecimalSeparator(',');
        DecimalFormat formateador = new DecimalFormat("###,###.###", simbolos);

        // parse() lanza una ParseException en caso de fallo que hay
        // que capturar.
        Number numero = formateador.parse(texto);
        valor = numero.floatValue();
        System.out.println(valor);
        // Estas dos líneas se puede abreviar con
        // double valor = formateador.parse(texto).doubleValue();

        return valor;

    }
}
