/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

 /*
 * diagInformes.java
 *
 * Created on 26-dic-2011, 14:23:10
 */
package vistas.becas;

import entidades.becas.PostulacionBeca;
import facade.EvaluacionesFacade;
import facade.NotaPagoFacade;
import facade.PagoFacade;
import facade.PostulacionBecaFacade;
import includes.Comunes;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.persistence.NoResultException;
import javax.swing.table.DefaultTableModel;
import reportes.becas.ReportesBecas;

/**
 *
 * @author Usuario
 */
public class diagInformes extends javax.swing.JDialog {

    private DefaultTableModel modelo;

    /**
     * Creates new form diagInformes
     */
    public diagInformes(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelHistorico = new javax.swing.JPanel();
        btHistorial = new javax.swing.JButton();
        jPanelVigentes = new javax.swing.JPanel();
        btVigentes = new javax.swing.JButton();
        jPanelPostulaciones = new javax.swing.JPanel();
        btPostulacionesVigentes = new javax.swing.JButton();
        btPostulacionesTodos = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        tfBuscar = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        cboExportarAExcel = new javax.swing.JComboBox();
        btnExportar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanelHistorico.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(diagInformes.class, "diagInformes.jPanelHistorico.border.title"))); // NOI18N

        btHistorial.setText(org.openide.util.NbBundle.getMessage(diagInformes.class, "diagInformes.btHistorial.text")); // NOI18N
        btHistorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btHistorialActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelHistoricoLayout = new javax.swing.GroupLayout(jPanelHistorico);
        jPanelHistorico.setLayout(jPanelHistoricoLayout);
        jPanelHistoricoLayout.setHorizontalGroup(
            jPanelHistoricoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHistoricoLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(btHistorial, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );
        jPanelHistoricoLayout.setVerticalGroup(
            jPanelHistoricoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHistoricoLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(btHistorial)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelVigentes.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(diagInformes.class, "diagInformes.jPanelVigentes.border.title"))); // NOI18N

        btVigentes.setText(org.openide.util.NbBundle.getMessage(diagInformes.class, "diagInformes.btVigentes.text")); // NOI18N
        btVigentes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVigentesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelVigentesLayout = new javax.swing.GroupLayout(jPanelVigentes);
        jPanelVigentes.setLayout(jPanelVigentesLayout);
        jPanelVigentesLayout.setHorizontalGroup(
            jPanelVigentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelVigentesLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(btVigentes, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );
        jPanelVigentesLayout.setVerticalGroup(
            jPanelVigentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelVigentesLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(btVigentes)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelPostulaciones.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(diagInformes.class, "diagInformes.jPanelPostulaciones.border.title"))); // NOI18N

        btPostulacionesVigentes.setText(org.openide.util.NbBundle.getMessage(diagInformes.class, "diagInformes.btPostulacionesVigentes.text")); // NOI18N
        btPostulacionesVigentes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPostulacionesVigentesActionPerformed(evt);
            }
        });

        btPostulacionesTodos.setText(org.openide.util.NbBundle.getMessage(diagInformes.class, "diagInformes.btPostulacionesTodos.text")); // NOI18N
        btPostulacionesTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPostulacionesTodosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelPostulacionesLayout = new javax.swing.GroupLayout(jPanelPostulaciones);
        jPanelPostulaciones.setLayout(jPanelPostulacionesLayout);
        jPanelPostulacionesLayout.setHorizontalGroup(
            jPanelPostulacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPostulacionesLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(btPostulacionesTodos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                .addComponent(btPostulacionesVigentes)
                .addGap(35, 35, 35))
        );
        jPanelPostulacionesLayout.setVerticalGroup(
            jPanelPostulacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPostulacionesLayout.createSequentialGroup()
                .addGroup(jPanelPostulacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btPostulacionesVigentes)
                    .addComponent(btPostulacionesTodos))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(diagInformes.class, "diagInformes.jPanel1.border.title"))); // NOI18N

        tfBuscar.setText(org.openide.util.NbBundle.getMessage(diagInformes.class, "diagInformes.tfBuscar.text")); // NOI18N
        tfBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfBuscarActionPerformed(evt);
            }
        });

        jLabel1.setText(org.openide.util.NbBundle.getMessage(diagInformes.class, "diagInformes.jLabel1.text")); // NOI18N

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Beca", "Proyecto", "Plan de Trabajo", "Postulante", "Situacion", "Fecha"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(tfBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 697, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(diagInformes.class, "diagInformes.jPanel2.border.title"))); // NOI18N

        cboExportarAExcel.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Postulantes", "Evaluaciones", "Pagos", "Situacion", "Todo" }));

        btnExportar.setText(org.openide.util.NbBundle.getMessage(diagInformes.class, "diagInformes.btnExportar.text")); // NOI18N
        btnExportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(cboExportarAExcel, 0, 175, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnExportar, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnExportar)
                    .addComponent(cboExportarAExcel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanelPostulaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanelHistorico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanelVigentes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanelVigentes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanelHistorico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanelPostulaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btVigentesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVigentesActionPerformed
        reporteBecasVigentes();
    }//GEN-LAST:event_btVigentesActionPerformed

    private void btPostulacionesVigentesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPostulacionesVigentesActionPerformed
        imprimirReportepostulantesVigentes();
    }//GEN-LAST:event_btPostulacionesVigentesActionPerformed

    private void btPostulacionesTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPostulacionesTodosActionPerformed
        imprimirReportesPostulantesTodos();
    }//GEN-LAST:event_btPostulacionesTodosActionPerformed

    private void tfBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfBuscarActionPerformed
        cargarTabla(tfBuscar.getText());
    }//GEN-LAST:event_tfBuscarActionPerformed

    private void btHistorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btHistorialActionPerformed
        imprimirReporteHistorioBecas();
    }//GEN-LAST:event_btHistorialActionPerformed

    private void btnExportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportarActionPerformed
        exportarSegunSeleccionCbo();
    }//GEN-LAST:event_btnExportarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(diagInformes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(diagInformes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(diagInformes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(diagInformes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                diagInformes dialog = new diagInformes(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btHistorial;
    private javax.swing.JButton btPostulacionesTodos;
    private javax.swing.JButton btPostulacionesVigentes;
    private javax.swing.JButton btVigentes;
    private javax.swing.JButton btnExportar;
    private javax.swing.JComboBox cboExportarAExcel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelHistorico;
    private javax.swing.JPanel jPanelPostulaciones;
    private javax.swing.JPanel jPanelVigentes;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField tfBuscar;
    // End of variables declaration//GEN-END:variables

    private void cargarTabla(String buscar) {

        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        Object[] fila = new Object[6];
        modelo = new DefaultTableModel();
        modelo.addColumn("Beca");
        modelo.addColumn("Proyecto");
        modelo.addColumn("Plan de Trabajo");
        modelo.addColumn("Postulante");
        modelo.addColumn("Situacion");
        modelo.addColumn("Fecha");

        for (PostulacionBeca postulaciones : PostulacionBecaFacade.getInstance().getPostulante(buscar)) {

            try {
                fila[0] = postulaciones.getBeca().getDescripcion();
            } catch (Exception ex) {
            }
            try {
                fila[1] = postulaciones.getProyecto().toString();
            } catch (Exception ex) {
            }
            try {
                fila[2] = postulaciones.getPlandetrabajo();
            } catch (Exception ex) {
            }
            try {
                fila[3] = postulaciones.getPostulante().toString();
            } catch (Exception ex) {
            }
            try {
                fila[4] = postulaciones.getPostulanteestado();
            } catch (Exception ex) {
            }
            try {
                fila[5] = sdf.format(postulaciones.getFechaalta());
            } catch (Exception ex) {
            }
            modelo.addRow(fila);

        }
        jTable1.setModel(modelo);

        //Comunes.setOcultarColumnasJTable(jTable1, oculta);
    }

    private void imprimirReporteHistorioBecas() {
        new ReportesBecas().reporteHistoricoBecas();
    }

    private void reporteBecasVigentes() {
        new ReportesBecas().reporteVigentesBecas();
    }

    private void imprimirReportesPostulantesTodos() {
        new ReportesBecas().reportePostulantesTodos();
    }

    private void imprimirReportepostulantesVigentes() {
        new ReportesBecas().reportePostulantesVigentes();
    }

    private void exportarSegunSeleccionCbo() {
        switch (cboExportarAExcel.getSelectedIndex()) {
            case 0:
                PostulacionBecaFacade.getInstance().exportarAExcelPostulantes();
                break;
            case 1:
                EvaluacionesFacade.getInstance().exportarAExcelEvaluaciones();
                break;
            case 2:
                NotaPagoFacade.getInstance().exportarAExcelPagos();
                break;
            case 3:
                PostulacionBecaFacade.getInstance().exportarAExcelSituacionPostulantes();
                break;
            case 4:
                PostulacionBecaFacade.getInstance().exportarAExcelTodoBecas();
                break;
        }

    }
}
