/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas.becas;

import entidades.Institucion;
import entidades.Resolucion;
import entidades.becas.*;
import entidades.operaciones.Operacion;
import entidades.persona.investigador.Investigador;
import entidades.usuario.Usuario;
import facade.*;
import includes.Comunes;
import javax.swing.JOptionPane;
import vista.panelControl.diagInstitucion;
import vista.resoluciones.diagResolucionEleccion;

/**
 *
 * @author hugo
 */
public class diagPagos extends javax.swing.JDialog {

    private String tipoOperacion;
    private Usuario usuario;
    private PostulacionBeca postulacion;
    private Pago pago;
    private Resolucion resolucion;

    /**
     * Creates new form diagEvaluaciones
     */
    public diagPagos(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        inicializarComponentes();
    }

    public diagPagos(java.awt.Frame parent, boolean modal, String TipoOperacion, PostulacionBeca postulacion, Usuario usuario) {
        super(parent, modal);
        this.postulacion = postulacion;
        this.tipoOperacion = TipoOperacion;
        this.usuario = usuario;
        initComponents();
        inicializarComponentes();
    }

    public diagPagos(java.awt.Frame parent, boolean modal, String TipoOperacion, PostulacionBeca postulacion, Pago pago, Usuario usuario) {
        super(parent, modal);
        this.postulacion = postulacion;
        this.pago = pago;
        this.tipoOperacion = TipoOperacion;
        this.usuario = usuario;
        initComponents();
        inicializarComponentes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        btnBuscarResolucion = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        taResolucion = new javax.swing.JTextArea();
        jLabel14 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane11 = new javax.swing.JScrollPane();
        taObservaciones = new javax.swing.JTextArea();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jxdpFecha = new org.jdesktop.swingx.JXDatePicker();
        tfexpediente = new javax.swing.JTextField();
        tfMonto = new javax.swing.JTextField();
        tfNroCheque = new javax.swing.JTextField();
        cboNroPago = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        btnNuevoPago = new javax.swing.JButton();
        btnAceptar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(diagPagos.class, "diagPagos.jPanel1.border.title"))); // NOI18N

        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(diagPagos.class, "diagPagos.jPanel11.border.title"))); // NOI18N

        btnBuscarResolucion.setText(org.openide.util.NbBundle.getMessage(diagPagos.class, "diagPagos.btnBuscarResolucion.text")); // NOI18N
        btnBuscarResolucion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarResolucionActionPerformed(evt);
            }
        });

        taResolucion.setColumns(20);
        taResolucion.setRows(5);
        jScrollPane2.setViewportView(taResolucion);

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnBuscarResolucion, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnBuscarResolucion)
                .addGap(0, 24, Short.MAX_VALUE))
        );

        jLabel14.setText(org.openide.util.NbBundle.getMessage(diagPagos.class, "diagPagos.jLabel14.text")); // NOI18N

        jLabel17.setText(org.openide.util.NbBundle.getMessage(diagPagos.class, "diagPagos.jLabel17.text")); // NOI18N

        jLabel18.setText(org.openide.util.NbBundle.getMessage(diagPagos.class, "diagPagos.jLabel18.text")); // NOI18N

        taObservaciones.setColumns(20);
        taObservaciones.setRows(5);
        jScrollPane11.setViewportView(taObservaciones);

        jLabel12.setText(org.openide.util.NbBundle.getMessage(diagPagos.class, "diagPagos.jLabel12.text")); // NOI18N

        jLabel13.setText(org.openide.util.NbBundle.getMessage(diagPagos.class, "diagPagos.jLabel13.text")); // NOI18N

        jxdpFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jxdpFechaActionPerformed(evt);
            }
        });

        tfexpediente.setText(org.openide.util.NbBundle.getMessage(diagPagos.class, "diagPagos.tfexpediente.text")); // NOI18N

        tfMonto.setText(org.openide.util.NbBundle.getMessage(diagPagos.class, "diagPagos.tfMonto.text")); // NOI18N

        tfNroCheque.setText(org.openide.util.NbBundle.getMessage(diagPagos.class, "diagPagos.tfNroCheque.text")); // NOI18N

        jLabel1.setText(org.openide.util.NbBundle.getMessage(diagPagos.class, "diagPagos.jLabel1.text")); // NOI18N

        btnNuevoPago.setText(org.openide.util.NbBundle.getMessage(diagPagos.class, "diagPagos.btnNuevoPago.text")); // NOI18N
        btnNuevoPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoPagoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel12))
                                .addGap(18, 18, 18))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel17))
                                .addGap(18, 18, 18)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfexpediente)
                            .addComponent(tfMonto)
                            .addComponent(tfNroCheque)
                            .addComponent(cboNroPago, 0, 213, Short.MAX_VALUE))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jLabel13))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnNuevoPago, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jxdpFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(114, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(jxdpFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(tfexpediente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfMonto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfNroCheque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cboNroPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(btnNuevoPago))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jScrollPane1.setViewportView(jPanel1);

        btnAceptar.setText(org.openide.util.NbBundle.getMessage(diagPagos.class, "diagPagos.btnAceptar.text")); // NOI18N
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 316, Short.MAX_VALUE)
                        .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(331, 331, 331))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(btnAceptar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarResolucionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarResolucionActionPerformed
        agregarResolucion();
    }//GEN-LAST:event_btnBuscarResolucionActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        aceptar();
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void btnNuevoPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoPagoActionPerformed
        agregarNumPago();
    }//GEN-LAST:event_btnNuevoPagoActionPerformed

    private void jxdpFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jxdpFechaActionPerformed
        Comunes.validarjxdatepicker(jxdpFecha);
    }//GEN-LAST:event_jxdpFechaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(diagPagos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(diagPagos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(diagPagos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(diagPagos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the dialog
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                diagPagos dialog = new diagPagos(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnBuscarResolucion;
    private javax.swing.JButton btnNuevoPago;
    private javax.swing.JComboBox cboNroPago;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane2;
    private org.jdesktop.swingx.JXDatePicker jxdpFecha;
    private javax.swing.JTextArea taObservaciones;
    private javax.swing.JTextArea taResolucion;
    private javax.swing.JTextField tfMonto;
    private javax.swing.JTextField tfNroCheque;
    private javax.swing.JTextField tfexpediente;
    // End of variables declaration//GEN-END:variables

    private void inicializarComponentes() {
        Comunes.formatearJXdatePicker(jxdpFecha);
        Comunes.autoAjusteTextArea(taResolucion);
        Comunes.autoAjusteTextArea(taObservaciones);
        if (!NumPagoFacade.getInstance().getTodas().isEmpty()) {
            Comunes.cargarJComboConBlanco(cboNroPago, NumPagoFacade.getInstance().getTodas());
        }


        if (tipoOperacion.equals("Modificación")) {
            try {
                if (pago.getExpediente() != null) {
                    tfexpediente.setText(pago.getExpediente());
                }
            } catch (Exception ex) {
            }
            try {
                if (pago.getResolucion() != null) {
                    taResolucion.setText(pago.getResolucion().toString());
                }
            } catch (Exception ex) {
            }
            try {
                if (pago.getMonto() != -1) {
                    tfMonto.setText(String.valueOf(pago.getMonto()));
                }
            } catch (Exception ex) {
            }
            try {
                if (!pago.getNroCheque().isEmpty()) {
                    tfNroCheque.setText(pago.getNroCheque());
                }
            } catch (Exception ex) {
            }
            try {
                if (pago.getNumPago() != null) {
                    cboNroPago.setSelectedItem(pago.getNumPago());
                }
            } catch (Exception ex) {
            }
            try {
                if (!pago.getObservaciones().isEmpty()) {
                    taObservaciones.setText(pago.getObservaciones());
                }
            } catch (Exception ex) {
            }
            try {
                
                    jxdpFecha.setDate(pago.getFecha());
                
            } catch (Exception ex) {
                jxdpFecha.setDate(null);
            }
        }

    }

    private void agregarResolucion() {
        diagResolucionEleccion resolucionEleccion = new diagResolucionEleccion(null, true);
        resolucionEleccion.setLocation(Comunes.centrarDialog(resolucionEleccion));
        resolucionEleccion.setVisible(true);
        if (resolucionEleccion.getResolucion() != null) {
            resolucion = new Resolucion();
            resolucion = resolucionEleccion.getResolucion();
            taResolucion.setText(resolucion.toString());

        }

    }

    private void aceptar() {
        if (validar()) {
            if (tipoOperacion.equals("Alta")) {
                pago = new Pago();

                if (!tfexpediente.getText().isEmpty()) {
                    pago.setExpediente(tfexpediente.getText());
                } else {
                    pago.setExpediente(null);
                }
                if (!tfMonto.getText().isEmpty()) {
                    pago.setMonto(Float.parseFloat(tfMonto.getText()));
                } else {
                    pago.setMonto(0);
                }
                if (!tfNroCheque.getText().isEmpty()) {
                    pago.setNroCheque(tfNroCheque.getText());
                } else {
                    pago.setNroCheque(null);
                }
                pago.setNumPago((NumPago) cboNroPago.getSelectedItem());
                pago.setFecha(jxdpFecha.getDate());

                if (!taObservaciones.getText().isEmpty()) {
                    pago.setObservaciones(taObservaciones.getText());
                } else {
                    pago.setObservaciones(null);
                }
                if (!taResolucion.getText().isEmpty()) {
                    pago.setResolucion(resolucion);
                } else {
                    pago.setResolucion(null);
                }
                pago.setPostulacionbeca(postulacion);


                PagoFacade.getInstance().alta(pago);
                Operacion operacion = new Operacion();
                operacion.setFecha(Comunes.obtenerFechaActualDesdeDB());
                operacion.setOperacion("Alta de Pago de Beca");
                operacion.setUsuario(usuario);
                OperacionFacade.getInstance().alta(operacion);
                JOptionPane.showMessageDialog(null, "Pago Registrado");
                this.dispose();

            }
            if (tipoOperacion.equals("Modificación")) {


                if (!tfexpediente.getText().isEmpty()) {
                    pago.setExpediente(tfexpediente.getText());
                } else {
                    pago.setExpediente(null);
                }
                if (!tfMonto.getText().isEmpty()) {
                    pago.setMonto(Float.parseFloat(tfMonto.getText()));
                } else {
                    pago.setMonto(0);
                }
                if (!tfNroCheque.getText().isEmpty()) {
                    pago.setNroCheque(tfNroCheque.getText());
                } else {
                    pago.setNroCheque(null);
                }
                pago.setNumPago((NumPago) cboNroPago.getSelectedItem());
                pago.setFecha(jxdpFecha.getDate());

                if (!taObservaciones.getText().isEmpty()) {
                    pago.setObservaciones(taObservaciones.getText());
                } else {
                    pago.setObservaciones(null);
                }
                if (!taResolucion.getText().isEmpty()) {
                    pago.setResolucion(resolucion);
                } else {
                    pago.setResolucion(null);
                }
                pago.setPostulacionbeca(postulacion);

                PagoFacade.getInstance().modificar(pago);
                Operacion operacion = new Operacion();
                operacion.setFecha(Comunes.obtenerFechaActualDesdeDB());
                operacion.setOperacion("Modificación de Pago de Beca");
                operacion.setUsuario(usuario);
                OperacionFacade.getInstance().alta(operacion);
                JOptionPane.showMessageDialog(null, "Modificacion Registrada");
                this.dispose();
            }
        }

    }

    private boolean validar() {
        boolean flag = false;

        if (cboNroPago.getSelectedIndex() > 0) {
            if (tfMonto.getText().isEmpty() || Comunes.validarBigDecimal(tfMonto.getText())) {
                flag = true;
            } else {
                JOptionPane.showMessageDialog(null, "Formato numerico invalido");
                tfMonto.requestFocus();
            }
        } else {
            JOptionPane.showMessageDialog(null, "Debe seleccionar nro de pago");
            cboNroPago.requestFocus();
        }


        return flag;
    }

    public Pago getPago() {
        return pago;
    }

    private void agregarNumPago() {
        diagNumPago nuevoNumPago = new diagNumPago(null, true);
        nuevoNumPago.setLocation(Comunes.centrarDialog(nuevoNumPago));
        nuevoNumPago.setVisible(true);
        if (nuevoNumPago.getNumPago() != null) {
            Comunes.cargarJCombo(cboNroPago, NumPagoFacade.getInstance().getTodas());
        }
    }
}
