/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.resoluciones;

import entidades.Resolucion;
import vistas.mensajes.*;
import entidades.persona.investigador.AreaSecyt;
import entidades.persona.investigador.Destinatario;
import entidades.persona.investigador.Investigador;
import entidades.persona.investigador.Mensaje;
import facade.AreaSecytFacade;
import facade.InvestigadorFacade;
import facade.MensajeFacade;
import includes.Comunes;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JList;
import javax.swing.JOptionPane;
import vista.diagInvestigadorBusquedaMultiple;
import vista.diagInvestigadorBusquedaMultiple2;
import vista.diagInvestigadorBusquedaSimple;

/**
 *
 * @author hugo
 */
public class diagAsignacionResolucionInvestigadores extends javax.swing.JDialog {

    private List<Investigador> listaInvestigadores = new ArrayList<>();
    private Resolucion resolucion;

    /**
     * Creates new form diagMensajeRespuesta
     */
    public diagAsignacionResolucionInvestigadores(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        inicializarComponentes();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnBuscarInvestigador = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListInvestigadores = new javax.swing.JList();
        pnCargar = new javax.swing.JPanel();
        btnEscogerResolucion = new javax.swing.JButton();
        tfResolucion = new javax.swing.JTextField();
        btnRespuesta = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(diagAsignacionResolucionInvestigadores.class, "diagAsignacionResolucionInvestigadores.jPanel1.border.title"))); // NOI18N

        jLabel2.setText(org.openide.util.NbBundle.getMessage(diagAsignacionResolucionInvestigadores.class, "diagAsignacionResolucionInvestigadores.jLabel2.text")); // NOI18N

        btnBuscarInvestigador.setText(org.openide.util.NbBundle.getMessage(diagAsignacionResolucionInvestigadores.class, "diagAsignacionResolucionInvestigadores.btnBuscarInvestigador.text")); // NOI18N
        btnBuscarInvestigador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarInvestigadorActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(jListInvestigadores);

        pnCargar.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(diagAsignacionResolucionInvestigadores.class, "diagAsignacionResolucionInvestigadores.pnCargar.border.title"))); // NOI18N

        btnEscogerResolucion.setText(org.openide.util.NbBundle.getMessage(diagAsignacionResolucionInvestigadores.class, "diagAsignacionResolucionInvestigadores.btnEscogerResolucion.text")); // NOI18N
        btnEscogerResolucion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEscogerResolucionActionPerformed(evt);
            }
        });

        tfResolucion.setEditable(false);
        tfResolucion.setText(org.openide.util.NbBundle.getMessage(diagAsignacionResolucionInvestigadores.class, "diagAsignacionResolucionInvestigadores.tfResolucion.text")); // NOI18N

        javax.swing.GroupLayout pnCargarLayout = new javax.swing.GroupLayout(pnCargar);
        pnCargar.setLayout(pnCargarLayout);
        pnCargarLayout.setHorizontalGroup(
            pnCargarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnCargarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tfResolucion, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(btnEscogerResolucion, javax.swing.GroupLayout.PREFERRED_SIZE, 139, Short.MAX_VALUE))
        );
        pnCargarLayout.setVerticalGroup(
            pnCargarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnCargarLayout.createSequentialGroup()
                .addGroup(pnCargarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEscogerResolucion)
                    .addComponent(tfResolucion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBuscarInvestigador, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(pnCargar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(btnBuscarInvestigador))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(pnCargar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        btnRespuesta.setText(org.openide.util.NbBundle.getMessage(diagAsignacionResolucionInvestigadores.class, "diagAsignacionResolucionInvestigadores.btnRespuesta.text")); // NOI18N
        btnRespuesta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRespuestaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(237, 237, 237)
                .addComponent(btnRespuesta, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRespuesta)
                .addGap(53, 53, 53))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRespuestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRespuestaActionPerformed
        enviarArchivo();
    }//GEN-LAST:event_btnRespuestaActionPerformed

    private void btnBuscarInvestigadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarInvestigadorActionPerformed
        buscarInvestigador();
    }//GEN-LAST:event_btnBuscarInvestigadorActionPerformed

    private void btnEscogerResolucionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEscogerResolucionActionPerformed
        cargarResolucion();
    }//GEN-LAST:event_btnEscogerResolucionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(diagMensajeRespuesta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(diagMensajeRespuesta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(diagMensajeRespuesta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(diagMensajeRespuesta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                diagMensajeRespuesta dialog = new diagMensajeRespuesta(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarInvestigador;
    private javax.swing.JButton btnEscogerResolucion;
    private javax.swing.JButton btnRespuesta;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JList jListInvestigadores;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel pnCargar;
    private javax.swing.JTextField tfResolucion;
    // End of variables declaration//GEN-END:variables

    private void inicializarComponentes() {   

    }

    private void enviarArchivo() {
        int cuentaMensajes = 0;
        InvestigadorFacade instance = InvestigadorFacade.getInstance();
        System.out.println("Lista investigadores: " + listaInvestigadores.size());
        if (validar()) {
            for (Investigador investigador : listaInvestigadores) {
                cuentaMensajes++;
                investigador.getResoluciones().add(resolucion);
                instance.modificar(investigador);
            }
            JOptionPane.showMessageDialog(null, cuentaMensajes + " Archivos Adjuntados!!");
            this.dispose();
        }


    }

    private boolean validar() {
        if (!listaInvestigadores.isEmpty()) {
            if (resolucion != null) {
                return true;
            } else {
                JOptionPane.showMessageDialog(null, "Debe escribir un mensaje de respuesta!!");
                return false;
            }
        } else {
            JOptionPane.showMessageDialog(null, "Debe Seleccionar al menos un Investigador!!");
            return false;
        }

    }

    private void buscarInvestigador() {
        diagInvestigadorBusquedaMultiple2 busqueda = new diagInvestigadorBusquedaMultiple2(null, true);
        busqueda.setLocation(Comunes.centrarDialog(busqueda));
        busqueda.setVisible(true);
        if (busqueda.getListaInvestigador() != null) {
            //mensaje.setInvestigador(busqueda.getInvestigador());
            listaInvestigadores = busqueda.getListaInvestigador();
            Comunes.cargarJList(jListInvestigadores, listaInvestigadores);
            //jListInvestigadores.setText(busqueda.getInvestigador().toString());
        }
    }

    private void cargarResolucion() {
        diagResolucionEleccion diEleccion = new diagResolucionEleccion(null, true);
        diEleccion.setVisible(true);
        if (diEleccion.getResolucion() != null) {
            resolucion = diEleccion.getResolucion();
            tfResolucion.setText(resolucion.toString());

        }
    }
}
