/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * diagAsignacionResolucion.java
 *
 * Created on 30/05/2011, 14:03:58
 */
package vista.resoluciones;

import controladores.ResolucionJpaController;
import controladores.exceptions.NonexistentEntityException;
import entidades.Resolucion;
import entidades.persona.Evaluador;
import entidades.persona.investigador.Investigador;
import entidades.proyecto.Proyecto;
import entidades.usuario.Usuario;
import facade.ConexionFacade;
import facade.ResolucionFacade;
import includes.Comunes;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.nio.channels.FileChannel;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import org.apache.commons.validator.routines.IntegerValidator;
import vista.diagEvaluadorBusqueda;
import vista.diagInvestigadorBusquedaSimple;
import vista.diagProyectoBusquedaSimple;

/**
 *
 * @author Administrador
 */
public class diagAsignacionResolucion extends javax.swing.JDialog {

    List<Proyecto> proyectos;
    List<Investigador> investigadores;
    List<Evaluador> evaluadores;
    private Resolucion resolucion;

    /** Creates new form diagDecretoAlta */
    public diagAsignacionResolucion(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        inicializarComponentes();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pnCargar = new javax.swing.JPanel();
        btnEscogerResolucion = new javax.swing.JButton();
        tfResolucion = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListProyectos = new javax.swing.JList();
        jLabel4 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jListInvestigadores = new javax.swing.JList();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jListEvaluadores = new javax.swing.JList();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setResizable(true);
        setTitle(org.openide.util.NbBundle.getMessage(diagAsignacionResolucion.class, "diagAsignacionResolucion.title")); // NOI18N

        pnCargar.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(diagAsignacionResolucion.class, "diagAsignacionResolucion.pnCargar.border.title"))); // NOI18N

        btnEscogerResolucion.setText(org.openide.util.NbBundle.getMessage(diagAsignacionResolucion.class, "diagAsignacionResolucion.btnEscogerResolucion.text")); // NOI18N
        btnEscogerResolucion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEscogerResolucionActionPerformed(evt);
            }
        });

        tfResolucion.setEditable(false);
        tfResolucion.setText(org.openide.util.NbBundle.getMessage(diagAsignacionResolucion.class, "diagAsignacionResolucion.tfResolucion.text")); // NOI18N

        javax.swing.GroupLayout pnCargarLayout = new javax.swing.GroupLayout(pnCargar);
        pnCargar.setLayout(pnCargarLayout);
        pnCargarLayout.setHorizontalGroup(
            pnCargarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnCargarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tfResolucion, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(btnEscogerResolucion, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE))
        );
        pnCargarLayout.setVerticalGroup(
            pnCargarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnCargarLayout.createSequentialGroup()
                .addGroup(pnCargarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEscogerResolucion)
                    .addComponent(tfResolucion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnGuardar.setText(org.openide.util.NbBundle.getMessage(diagAsignacionResolucion.class, "diagAsignacionResolucion.btnGuardar.text")); // NOI18N
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(diagAsignacionResolucion.class, "diagAsignacionResolucion.jPanel2.border.title"))); // NOI18N

        jScrollPane2.setViewportView(jListProyectos);

        jLabel4.setText(org.openide.util.NbBundle.getMessage(diagAsignacionResolucion.class, "diagAsignacionResolucion.jLabel4.text")); // NOI18N

        jButton4.setText(org.openide.util.NbBundle.getMessage(diagAsignacionResolucion.class, "diagAsignacionResolucion.jButton4.text")); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText(org.openide.util.NbBundle.getMessage(diagAsignacionResolucion.class, "diagAsignacionResolucion.jButton5.text")); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jScrollPane3.setViewportView(jListInvestigadores);

        jButton6.setText(org.openide.util.NbBundle.getMessage(diagAsignacionResolucion.class, "diagAsignacionResolucion.jButton6.text")); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText(org.openide.util.NbBundle.getMessage(diagAsignacionResolucion.class, "diagAsignacionResolucion.jButton7.text")); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jLabel5.setText(org.openide.util.NbBundle.getMessage(diagAsignacionResolucion.class, "diagAsignacionResolucion.jLabel5.text")); // NOI18N

        jScrollPane4.setViewportView(jListEvaluadores);

        jButton8.setText(org.openide.util.NbBundle.getMessage(diagAsignacionResolucion.class, "diagAsignacionResolucion.jButton8.text")); // NOI18N
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setText(org.openide.util.NbBundle.getMessage(diagAsignacionResolucion.class, "diagAsignacionResolucion.jButton9.text")); // NOI18N
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jLabel6.setText(org.openide.util.NbBundle.getMessage(diagAsignacionResolucion.class, "diagAsignacionResolucion.jLabel6.text")); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addComponent(jButton8))
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                    .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                    .addComponent(jButton9))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton5))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton7))
                    .addComponent(jLabel5)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton9))
                    .addComponent(jLabel6)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pnCargar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(225, 225, 225)
                        .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(pnCargar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEscogerResolucionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEscogerResolucionActionPerformed
        cargarResolucion();
    }//GEN-LAST:event_btnEscogerResolucionActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        guardarResolucion();
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        agregarProyecto();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        eliminarProyecto();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        agregarInvestigador();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        eliminarInvestigador();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        agregarEvaluador();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        eliminarEvaluador();
    }//GEN-LAST:event_jButton9ActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEscogerResolucion;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JList jListEvaluadores;
    private javax.swing.JList jListInvestigadores;
    private javax.swing.JList jListProyectos;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JPanel pnCargar;
    private javax.swing.JTextField tfResolucion;
    // End of variables declaration//GEN-END:variables

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                diagAsignacionResolucion dialog = new diagAsignacionResolucion(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    private void guardarResolucion() {
        if (validarDatos()) {
            try {
                resolucion.setEvaluadores(evaluadores);
                resolucion.setInvestigadores(investigadores);
                resolucion.setProyectos(proyectos);
                EntityManagerFactory emf = Persistence.createEntityManagerFactory("ProyectoUnoPU",ConexionFacade.PROPIEDADES);
                new ResolucionJpaController(emf).edit(resolucion);
                JOptionPane.showMessageDialog(null, "La asignación de la Resolución "
                        + "se ha realizado correctamente");
                this.dispose();
            } catch (NonexistentEntityException ex) {
                JOptionPane.showMessageDialog(null, "Error en la asignación de la Resolución "
                        + ex);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "Error en la asignación de la Resolución "
                        + ex);
            }


        }
    }

    private void agregarProyecto() {
        diagProyectoBusquedaSimple proyectoBusquedaSimple = new diagProyectoBusquedaSimple(null, true);
        Comunes.centrarDialog(proyectoBusquedaSimple);
        proyectoBusquedaSimple.setVisible(true);
        if (proyectoBusquedaSimple.getProyecto() != null) {
            proyectos.add(proyectoBusquedaSimple.getProyecto());
            Comunes.cargarJList(jListProyectos, proyectos);
        }
    }

    private void eliminarProyecto() {
        if (jListProyectos.getSelectedIndex() != -1) {
            proyectos.remove((Proyecto) jListProyectos.getSelectedValue());
            Comunes.cargarJList(jListProyectos, proyectos);
        } else {
            JOptionPane.showMessageDialog(null, "Debe escoger un proyecto",
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void agregarInvestigador() {
        diagInvestigadorBusquedaSimple investigadorBusquedaSimple = new diagInvestigadorBusquedaSimple(null, true);
        Comunes.centrarDialog(investigadorBusquedaSimple);
        investigadorBusquedaSimple.setVisible(true);
        if (investigadorBusquedaSimple.getInvestigador() != null) {
            investigadores.add(investigadorBusquedaSimple.getInvestigador());
            Comunes.cargarJList(jListInvestigadores, investigadores);
        }
    }

    private void eliminarInvestigador() {
        if (jListInvestigadores.getSelectedIndex() != -1) {
            investigadores.remove((Investigador) jListInvestigadores.getSelectedValue());
            Comunes.cargarJList(jListInvestigadores, investigadores);
        } else {
            JOptionPane.showMessageDialog(null, "Debe escoger un investigador",
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void agregarEvaluador() {
        diagEvaluadorBusqueda evaluadorBusquedaSimple = new diagEvaluadorBusqueda(null, true, new Usuario());
        Comunes.centrarDialog(evaluadorBusquedaSimple);
        evaluadorBusquedaSimple.setVisible(true);
        if (evaluadorBusquedaSimple.getEvaluador() != null) {
            evaluadores.add(evaluadorBusquedaSimple.getEvaluador());
            Comunes.cargarJList(jListEvaluadores, evaluadores);
        }
    }

    private void eliminarEvaluador() {
        if (jListEvaluadores.getSelectedIndex() != -1) {
            evaluadores.remove((Evaluador) jListEvaluadores.getSelectedValue());
            Comunes.cargarJList(jListEvaluadores, evaluadores);
        } else {
            JOptionPane.showMessageDialog(null, "Debe escoger un evaluador",
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void cargarResolucion() {
        diagResolucionEleccion diEleccion = new diagResolucionEleccion(null, true);
        diEleccion.setVisible(true);
        if (diEleccion.getResolucion() != null) {
            resolucion = diEleccion.getResolucion();
            tfResolucion.setText(resolucion.toString());
            evaluadores = resolucion.getEvaluadores();
            proyectos = resolucion.getProyectos();
            investigadores = resolucion.getInvestigadores();
            Comunes.cargarJList(jListProyectos, proyectos);
            Comunes.cargarJList(jListEvaluadores, evaluadores);
            Comunes.cargarJList(jListInvestigadores, investigadores);
        }
    }

    private boolean validarDatos() {
        if (resolucion != null) {
            return true;
        } else {
            return false;
        }
    }

    private void inicializarComponentes() {
    }
}
